/**
 * Award Registry — the single source of truth for every award the league
 * can hand out. Data only — no logic. Pair with AwardEngine.ts to compute
 * races or announce winners.
 *
 * Adding a new award = add a record here. No changes to UI / scheduler /
 * persistence required.
 */
import type { AwardDefinition } from './types';

export const AWARD_REGISTRY: AwardDefinition[] = [
  // ─── SEASON AWARDS (universal) ───────────────────────────────────────────
  {
    id: 'mvp',
    category: 'season', scope: 'player',
    name: 'Most Valuable Player',
    shortName: 'MVP',
    description: 'The best player in the league across the regular season.',
    trophy: { icon: 'star', color: 'yellow', blurb: 'Maurice Podoloff Trophy (NBA) / EuroLeague MVP / Liga ACB MVP' },
    calculatorId: 'mvp',
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['nba', 'euro_isolated', 'fictional'],
    defaultAnnounceMD: { month: 5, day: 21 },
    minGamesDefault: 65,
    fatigueFactor: 0.025,
    storedType: 'MVP',
    brandedAs: {
      euro_isolated: {
        name: 'EuroLeague MVP',
        trophy: { icon: 'star', color: 'orange' },
      },
    },
  },
  {
    id: 'dpoy',
    category: 'defense', scope: 'player',
    name: 'Defensive Player of the Year',
    shortName: 'DPOY',
    description: 'Most impactful defender of the regular season.',
    trophy: { icon: 'shield', color: 'blue', blurb: 'Hakeem Olajuwon Trophy / EL Best Defender' },
    calculatorId: 'dpoy',
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['nba', 'euro_isolated', 'fictional'],
    defaultAnnounceMD: { month: 4, day: 28 },
    minGamesDefault: 65,
    fatigueFactor: 0.025,
    storedType: 'DPOY',
    brandedAs: {
      euro_isolated: { name: 'EuroLeague Best Defender' },
    },
  },
  {
    id: 'roy',
    category: 'rookie', scope: 'player',
    name: 'Rookie of the Year',
    shortName: 'ROY',
    description: 'Top performing first-year player.',
    trophy: { icon: 'sparkles', color: 'emerald', blurb: 'Wilt Chamberlain Trophy' },
    calculatorId: 'rookie',
    eligibility: ['rookie-year', 'min-games'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 5, day: 2 },
    minGamesDefault: 65,
    storedType: 'ROY',
  },
  {
    id: 'mip',
    category: 'season', scope: 'player',
    name: 'Most Improved Player',
    shortName: 'MIP',
    description: 'Largest year-over-year production jump.',
    trophy: { icon: 'trending-up', color: 'orange' },
    calculatorId: 'mip',
    eligibility: ['min-games'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 4, day: 25 },
    minGamesDefault: 65,
    storedType: 'MIP',
  },
  {
    id: 'smoy',
    category: 'season', scope: 'player',
    name: 'Sixth Man of the Year',
    shortName: 'SMOY',
    description: 'Best player off the bench.',
    trophy: { icon: 'users', color: 'purple' },
    calculatorId: 'six-man',
    eligibility: ['min-games', 'bench-role'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 4, day: 22 },
    minGamesDefault: 65,
    storedType: 'SMOY',
  },

  // ─── COACHING ─────────────────────────────────────────────────────────────
  {
    id: 'coy',
    category: 'coach', scope: 'coach',
    name: 'Coach of the Year',
    shortName: 'COY',
    description: 'Best coaching job of the regular season.',
    trophy: { icon: 'user-check', color: 'teal', blurb: 'Red Auerbach Trophy / Alexander Gomelskiy COY' },
    calculatorId: 'coy',
    eligibility: [],
    poolId: 'all-active',
    defaultActiveIn: ['nba', 'euro_isolated', 'fictional'],
    defaultAnnounceMD: { month: 4, day: 19 },
    minGamesDefault: 0,
    storedType: 'COY',
    brandedAs: {
      euro_isolated: { name: 'Alexander Gomelskiy Coach of the Year' },
    },
  },

  // ─── RISING / YOUNG (Euro-default, NBA-optional) ─────────────────────────
  {
    id: 'rising-star',
    category: 'rising', scope: 'player',
    name: 'Rising Star Award',
    shortName: 'Rising',
    description: 'Top performer under the age of 23.',
    trophy: { icon: 'sparkles', color: 'purple' },
    calculatorId: 'young',
    calculatorArgs: { ageCap: 23 },
    eligibility: ['under-23'],
    poolId: 'all-active',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 5, day: 8 },
    minGamesDefault: 20,
    storedType: 'Rising Star',
  },
  {
    id: 'young-player',
    category: 'rising', scope: 'player',
    name: 'Best Young Player',
    shortName: 'Young',
    description: 'Top performer under the age of 22.',
    trophy: { icon: 'baby', color: 'pink' },
    calculatorId: 'young',
    calculatorArgs: { ageCap: 22 },
    eligibility: ['under-22'],
    poolId: 'endesa',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 6, day: 10 },
    minGamesDefault: 20,
    storedType: 'Best Young Player',
  },

  // ─── STAT LEADERS (Inactive in NBA by default — commissioner can enable) ─
  {
    id: 'top-scorer',
    category: 'stat-leader', scope: 'player',
    name: 'Scoring Title',
    shortName: 'PPG',
    description: 'Highest points-per-game leader.',
    trophy: { icon: 'flame', color: 'orange', blurb: 'Alphonso Ford Trophy (EuroLeague)' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: 'pts' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'Scoring Title',
    brandedAs: {
      euro_isolated: { name: 'Alphonso Ford Top Scorer Trophy' },
    },
  },
  {
    id: 'rebound-leader',
    category: 'stat-leader', scope: 'player',
    name: 'Rebound Leader',
    shortName: 'RPG',
    description: 'Highest rebounds-per-game leader.',
    trophy: { icon: 'circle', color: 'amber' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: 'reb' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'Rebound Leader',
  },
  {
    id: 'assist-leader',
    category: 'stat-leader', scope: 'player',
    name: 'Assist Leader',
    shortName: 'APG',
    description: 'Highest assists-per-game leader.',
    trophy: { icon: 'share-2', color: 'sky' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: 'ast' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'Assist Leader',
  },
  {
    id: 'steals-leader',
    category: 'stat-leader', scope: 'player',
    name: 'Steals Leader',
    shortName: 'SPG',
    description: 'Highest steals-per-game leader.',
    trophy: { icon: 'zap', color: 'emerald' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: 'stl' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: [],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'Steals Leader',
  },
  {
    id: 'blocks-leader',
    category: 'stat-leader', scope: 'player',
    name: 'Blocks Leader',
    shortName: 'BPG',
    description: 'Highest blocks-per-game leader.',
    trophy: { icon: 'shield', color: 'blue' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: 'blk' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: [],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'Blocks Leader',
  },
  {
    id: 'threes-leader',
    category: 'stat-leader', scope: 'player',
    name: '3-Point Leader',
    shortName: '3PM',
    description: 'Most made three-pointers per game.',
    trophy: { icon: 'target', color: 'indigo' },
    calculatorId: 'stat-leader',
    calculatorArgs: { metric: '3p' },
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: [],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: '3-Point Leader',
  },
  {
    id: 'pir-leader',
    category: 'stat-leader', scope: 'player',
    name: 'PIR Leader',
    shortName: 'PIR',
    description: 'Performance Index Rating leader (FIBA standard formula).',
    trophy: { icon: 'award', color: 'pink' },
    calculatorId: 'pir',
    eligibility: ['min-games'],
    poolId: 'all-active',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 4, day: 30 },
    minGamesDefault: 20,
    storedType: 'PIR Leader',
  },

  // ─── ALL-LEAGUE / ALL-DEFENSE / ALL-ROOKIE ───────────────────────────────
  {
    id: 'all-league',
    category: 'all-team', scope: 'player',
    name: 'All-League Teams',
    shortName: 'All-League',
    description: '1st, 2nd, 3rd Teams — best players by position.',
    trophy: { icon: 'users', color: 'indigo' },
    calculatorId: 'all-team',
    calculatorArgs: { numTeams: 3, perTeam: 5 },
    eligibility: ['min-games'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 5, day: 7 },
    minGamesDefault: 65,
    storedType: 'All-NBA First Team',
  },
  {
    id: 'all-defensive',
    category: 'all-team', scope: 'player',
    name: 'All-Defensive Teams',
    shortName: 'All-D',
    description: '1st & 2nd Teams — best defenders by position.',
    trophy: { icon: 'shield', color: 'blue' },
    calculatorId: 'all-team',
    calculatorArgs: { numTeams: 2, perTeam: 5 },
    eligibility: ['min-games'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 5, day: 7 },
    minGamesDefault: 65,
    storedType: 'All-Defensive First Team',
  },
  {
    id: 'all-rookie',
    category: 'all-team', scope: 'player',
    name: 'All-Rookie Teams',
    shortName: 'All-R',
    description: '1st & 2nd Teams — best rookies.',
    trophy: { icon: 'sparkles', color: 'emerald' },
    calculatorId: 'all-team',
    calculatorArgs: { numTeams: 2, perTeam: 5 },
    eligibility: ['rookie-year', 'min-games'],
    poolId: 'nba',
    defaultActiveIn: ['nba', 'fictional'],
    defaultAnnounceMD: { month: 5, day: 7 },
    minGamesDefault: 65,
    storedType: 'All-Rookie First Team',
  },
  {
    id: 'all-euroleague',
    category: 'all-team', scope: 'player',
    name: 'All-EuroLeague Teams',
    shortName: 'All-EL',
    description: '1st & 2nd Teams — best EuroLeague players.',
    trophy: { icon: 'users', color: 'orange' },
    calculatorId: 'all-team',
    calculatorArgs: { numTeams: 2, perTeam: 5 },
    eligibility: ['min-games'],
    poolId: 'euroleague',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 5, day: 18 },
    minGamesDefault: 20,
    storedType: 'All-EuroLeague First Team',
  },

  // ─── POSTSEASON (written externally by playoff resolver) ─────────────────
  {
    id: 'finals-mvp',
    category: 'postseason', scope: 'player',
    name: 'Finals MVP',
    shortName: 'F-MVP',
    description: 'Most Valuable Player of the championship series.',
    trophy: { icon: 'crown', color: 'amber', blurb: 'Bill Russell Trophy' },
    calculatorId: 'postseason',
    eligibility: [],
    poolId: 'all-active',
    defaultActiveIn: ['nba', 'euro_isolated', 'fictional'],
    defaultAnnounceMD: { month: 6, day: 22 },
    minGamesDefault: 0,
    storedType: 'Finals MVP',
  },
  {
    id: 'conf-finals-mvp',
    category: 'postseason', scope: 'player',
    name: 'Conference Finals MVP',
    shortName: 'CF-MVP',
    description: 'MVP of each conference final.',
    trophy: { icon: 'medal', color: 'silver' },
    calculatorId: 'postseason',
    eligibility: [],
    poolId: 'nba',
    defaultActiveIn: ['nba'],
    defaultAnnounceMD: { month: 6, day: 1 },
    minGamesDefault: 0,
    storedType: 'Semifinals MVP',
  },
  {
    id: 'final-four-mvp',
    category: 'postseason', scope: 'player',
    name: 'Final Four MVP',
    shortName: 'F4-MVP',
    description: 'MVP of the EuroLeague Final Four weekend.',
    trophy: { icon: 'crown', color: 'orange' },
    calculatorId: 'postseason',
    eligibility: [],
    poolId: 'euroleague',
    defaultActiveIn: ['euro_isolated'],
    defaultAnnounceMD: { month: 5, day: 26 },
    minGamesDefault: 0,
    storedType: 'Final Four MVP',
  },
];

/** Lookup award by id. */
export function getAwardDefinition(id: string): AwardDefinition | undefined {
  return AWARD_REGISTRY.find(a => a.id === id);
}

/** All award ids. */
export const ALL_AWARD_IDS = AWARD_REGISTRY.map(a => a.id);
