import type { LeagueStats } from '../../../../types';
import { ruleValue } from './rulesDefaults';

export const createRulesViewDefaults = (leagueStats: LeagueStats) => ({
  playIn: leagueStats.playIn,
  inSeasonTournament: leagueStats.inSeasonTournament ?? true,
  cupPrizePoolEnabled: leagueStats.cupPrizePoolEnabled ?? true,
  cupPrizePoolAutoInflate: leagueStats.cupPrizePoolAutoInflate ?? true,
  cupPrizeWinner: leagueStats.cupPrizeWinner ?? 500_000,
  cupPrizeRunnerUp: leagueStats.cupPrizeRunnerUp ?? 200_000,
  cupPrizeSemi: leagueStats.cupPrizeSemi ?? 100_000,
  cupPrizeQuarter: leagueStats.cupPrizeQuarter ?? 50_000,
  playoffFormat: [...leagueStats.numGamesPlayoffSeries] as (number | string)[],
  draftType: leagueStats.draftType,
  eligibilityRule: leagueStats.draftEligibilityRule ?? 'one_and_done',
  minAgeRequirement: leagueStats.minAgeRequirement ?? 19,
  minGamesRequirement: leagueStats.minGamesRequirement ?? 65,
  customScheduleEnabled: leagueStats.customScheduleEnabled ?? false,
  gamesPerSeason: leagueStats.gamesPerSeason ?? 82,
  divisionGames: leagueStats.divisionGames ?? 16,
  conferenceGames: leagueStats.conferenceGames ?? 36,
  allStarGameEnabled: leagueStats.allStarGameEnabled ?? true,
  allStarFormat: leagueStats.allStarFormat ?? 'usa_vs_world',
  allStarTeams: leagueStats.allStarTeams ?? 3,
  allStarMirrorLeagueRules: leagueStats.allStarMirrorLeagueRules ?? false,
  allStarDunkContest: leagueStats.allStarDunkContest ?? true,
  allStarDunkContestPlayers: leagueStats.allStarDunkContestPlayers ?? 4,
  allStarThreePointContest: leagueStats.allStarThreePointContest ?? true,
  allStarThreePointContestPlayers: leagueStats.allStarThreePointContestPlayers ?? 8,
  allStarShootingStars: leagueStats.allStarShootingStars ?? true,
  allStarShootingStarsMode: leagueStats.allStarShootingStarsMode ?? 'team',
  allStarShootingStarsTeams: leagueStats.allStarShootingStarsTeams ?? Math.max(2, Math.round((leagueStats.allStarShootingStarsTotalPlayers ?? 12) / 3)),
  allStarShootingStarsPlayersPerTeam: leagueStats.allStarShootingStarsPlayersPerTeam ?? 3,
  allStarShootingStarsTotalPlayers: (leagueStats.allStarShootingStarsTeams ?? Math.max(2, Math.round((leagueStats.allStarShootingStarsTotalPlayers ?? 12) / 3))) * 3,
  allStarSkillsChallenge: leagueStats.allStarSkillsChallenge ?? false,
  allStarSkillsChallengeMode: leagueStats.allStarSkillsChallengeMode ?? 'individual',
  allStarSkillsChallengeTeams: leagueStats.allStarSkillsChallengeTeams ?? leagueStats.allStarSkillsChallengeTotalPlayers ?? 4,
  allStarSkillsChallengePlayersPerTeam: leagueStats.allStarSkillsChallengePlayersPerTeam ?? 1,
  allStarSkillsChallengeTotalPlayers: leagueStats.allStarSkillsChallengeTeams ?? leagueStats.allStarSkillsChallengeTotalPlayers ?? 4,
  allStarHorse: leagueStats.allStarHorse ?? false,
  allStarHorseParticipants: leagueStats.allStarHorseParticipants ?? 3,
  allStarHorseNoPlayerRepeat: leagueStats.allStarHorseNoPlayerRepeat ?? false,
  allStarHorseNoGlobalRepeat: leagueStats.allStarHorseNoGlobalRepeat ?? false,
  allStarOneOnOneEnabled: leagueStats.allStarOneOnOneEnabled ?? false,
  allStarOneOnOneParticipants: leagueStats.allStarOneOnOneParticipants ?? 8,
  allStarThroneEnabled: leagueStats.allStarThroneEnabled ?? false,
  allStarThroneFieldSize: (leagueStats.allStarThroneFieldSize ?? 16) as 8 | 16,
  allStarThroneFormat: leagueStats.allStarThroneFormat ?? 'full16',
  allStarThroneFirstPossession: leagueStats.allStarThroneFirstPossession ?? 'shootout',
  allStarThroneScoring: leagueStats.allStarThroneScoring ?? '2s_and_3s',
  allStarThroneShotClock: leagueStats.allStarThroneShotClock ?? 7,
  allStarThroneTargetScore: leagueStats.allStarThroneTargetScore ?? 12,
  allStarThroneHardCap: leagueStats.allStarThroneHardCap ?? 16,
  allStarThronePrizePool: leagueStats.allStarThronePrizePool ?? 5_000_000,
  allStarThroneMandatoryDefense: leagueStats.allStarThroneMandatoryDefense ?? true,
  risingStarsEnabled: leagueStats.risingStarsEnabled ?? true,
  risingStarsFormat: leagueStats.risingStarsFormat ?? '4team_tournament',
  risingStarsMirrorLeagueRules: leagueStats.risingStarsMirrorLeagueRules ?? false,
  risingStarsQuarterLength: leagueStats.risingStarsQuarterLength ?? 3,
  risingStarsEliminationEndings: leagueStats.risingStarsEliminationEndings ?? true,
  celebrityGameEnabled: leagueStats.celebrityGameEnabled ?? true,
  celebrityGameMirrorLeagueRules: leagueStats.celebrityGameMirrorLeagueRules ?? true,
  allStarGameFormat: leagueStats.allStarGameFormat ?? 'timed',
  allStarGameTargetScore: leagueStats.allStarGameTargetScore ?? 40,
  allStarQuarterLength: ruleValue(leagueStats, 'allStarQuarterLength'),
  allStarNumQuarters: leagueStats.allStarNumQuarters ?? 4,
  allStarOvertimeDuration: leagueStats.allStarOvertimeDuration ?? 5,
  allStarOvertimeTargetPoints: leagueStats.allStarOvertimeTargetPoints ?? 7,
  allStarShootoutRounds: leagueStats.allStarShootoutRounds ?? 3,
  allStarOvertimeType: leagueStats.allStarOvertimeType ?? 'standard',
  allStarMaxOvertimesEnabled: leagueStats.allStarMaxOvertimesEnabled ?? false,
  allStarMaxOvertimes: leagueStats.allStarMaxOvertimes ?? 3,
  allStarOvertimeTieBreaker: leagueStats.allStarOvertimeTieBreaker ?? 'shootout',
});
