import { useState, type Dispatch, type SetStateAction } from 'react';
import type { LeagueStats } from '../../../../types';
import type { createRulesViewDefaults } from './rulesStateViewDefaults';

type RulesViewDefaults = ReturnType<typeof createRulesViewDefaults>;
type StateTuple<T> = [T, Dispatch<SetStateAction<T>>];

export type MaterializedState<T extends Record<string, StateTuple<unknown>>> = {
  [K in keyof T]: T[K][0];
} & {
  [K in keyof T as `set${Capitalize<string & K>}`]: T[K][1];
};

export const materializeRulesStateSection = <T extends Record<string, StateTuple<unknown>>>(section: T): MaterializedState<T> => {
  const entries = Object.entries(section).flatMap(([key, pair]) => {
    const setterKey = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
    return [
      [key, pair[0]],
      [setterKey, pair[1]],
    ];
  });

  return Object.fromEntries(entries) as MaterializedState<T>;
};

export const useFormatRulesState = (_leagueStats: LeagueStats, viewDefaults: RulesViewDefaults) => ({
  playIn: useState(viewDefaults.playIn),
  inSeasonTournament: useState(viewDefaults.inSeasonTournament),
  cupPrizePoolEnabled: useState(viewDefaults.cupPrizePoolEnabled),
  cupPrizePoolAutoInflate: useState(viewDefaults.cupPrizePoolAutoInflate),
  cupPrizeWinner: useState(viewDefaults.cupPrizeWinner),
  cupPrizeRunnerUp: useState(viewDefaults.cupPrizeRunnerUp),
  cupPrizeSemi: useState(viewDefaults.cupPrizeSemi),
  cupPrizeQuarter: useState(viewDefaults.cupPrizeQuarter),
  playoffFormat: useState<(number | string)[]>(viewDefaults.playoffFormat),
  draftType: useState(viewDefaults.draftType),
  eligibilityRule: useState(viewDefaults.eligibilityRule),
  minAgeRequirement: useState<number | string>(viewDefaults.minAgeRequirement),
  minGamesRequirement: useState<number | string>(viewDefaults.minGamesRequirement),
  customScheduleEnabled: useState(viewDefaults.customScheduleEnabled),
  gamesPerSeason: useState(viewDefaults.gamesPerSeason),
  divisionGames: useState(viewDefaults.divisionGames),
  conferenceGames: useState(viewDefaults.conferenceGames),
});

export const useAllStarRulesState = (viewDefaults: RulesViewDefaults) => ({
  allStarGameEnabled: useState(viewDefaults.allStarGameEnabled),
  allStarFormat: useState(viewDefaults.allStarFormat),
  allStarTeams: useState(viewDefaults.allStarTeams),
  allStarMirrorLeagueRules: useState(viewDefaults.allStarMirrorLeagueRules),
  allStarDunkContest: useState(viewDefaults.allStarDunkContest),
  allStarDunkContestPlayers: useState(viewDefaults.allStarDunkContestPlayers),
  allStarThreePointContest: useState(viewDefaults.allStarThreePointContest),
  allStarThreePointContestPlayers: useState(viewDefaults.allStarThreePointContestPlayers),
  allStarShootingStars: useState(viewDefaults.allStarShootingStars),
  allStarShootingStarsMode: useState<'individual' | 'team'>(viewDefaults.allStarShootingStarsMode),
  allStarShootingStarsTeams: useState(viewDefaults.allStarShootingStarsTeams),
  allStarShootingStarsPlayersPerTeam: useState(viewDefaults.allStarShootingStarsPlayersPerTeam),
  allStarShootingStarsTotalPlayers: useState(viewDefaults.allStarShootingStarsTotalPlayers),
  allStarSkillsChallenge: useState(viewDefaults.allStarSkillsChallenge),
  allStarSkillsChallengeMode: useState<'individual' | 'team'>(viewDefaults.allStarSkillsChallengeMode),
  allStarSkillsChallengeTeams: useState(viewDefaults.allStarSkillsChallengeTeams),
  allStarSkillsChallengePlayersPerTeam: useState(viewDefaults.allStarSkillsChallengePlayersPerTeam),
  allStarSkillsChallengeTotalPlayers: useState(viewDefaults.allStarSkillsChallengeTotalPlayers),
  allStarHorse: useState(viewDefaults.allStarHorse),
  allStarHorseParticipants: useState(viewDefaults.allStarHorseParticipants),
  allStarHorseNoPlayerRepeat: useState(viewDefaults.allStarHorseNoPlayerRepeat),
  allStarHorseNoGlobalRepeat: useState(viewDefaults.allStarHorseNoGlobalRepeat),
  allStarOneOnOneEnabled: useState(viewDefaults.allStarOneOnOneEnabled),
  allStarOneOnOneParticipants: useState(viewDefaults.allStarOneOnOneParticipants),
  allStarThroneEnabled: useState(viewDefaults.allStarThroneEnabled),
  allStarThroneFieldSize: useState<8 | 16>(viewDefaults.allStarThroneFieldSize),
  allStarThroneFormat: useState<'mini8' | 'full16'>(viewDefaults.allStarThroneFormat),
  allStarThroneFirstPossession: useState<'shootout' | 'higher_seed_choice'>(viewDefaults.allStarThroneFirstPossession),
  allStarThroneScoring: useState<'2s_and_3s' | '1s_and_2s'>(viewDefaults.allStarThroneScoring),
  allStarThroneShotClock: useState(viewDefaults.allStarThroneShotClock),
  allStarThroneTargetScore: useState(viewDefaults.allStarThroneTargetScore),
  allStarThroneHardCap: useState(viewDefaults.allStarThroneHardCap),
  allStarThronePrizePool: useState(viewDefaults.allStarThronePrizePool),
  allStarThroneMandatoryDefense: useState(viewDefaults.allStarThroneMandatoryDefense),
  risingStarsEnabled: useState(viewDefaults.risingStarsEnabled),
  risingStarsFormat: useState(viewDefaults.risingStarsFormat),
  risingStarsMirrorLeagueRules: useState(viewDefaults.risingStarsMirrorLeagueRules),
  risingStarsQuarterLength: useState(viewDefaults.risingStarsQuarterLength),
  risingStarsEliminationEndings: useState(viewDefaults.risingStarsEliminationEndings),
  celebrityGameEnabled: useState(viewDefaults.celebrityGameEnabled),
  celebrityGameMirrorLeagueRules: useState(viewDefaults.celebrityGameMirrorLeagueRules),
  allStarGameFormat: useState<'timed' | 'target_score' | 'elam_ending'>(viewDefaults.allStarGameFormat),
  allStarGameTargetScore: useState(viewDefaults.allStarGameTargetScore),
  allStarQuarterLength: useState(viewDefaults.allStarQuarterLength),
  allStarNumQuarters: useState(viewDefaults.allStarNumQuarters),
  allStarOvertimeDuration: useState(viewDefaults.allStarOvertimeDuration),
  allStarOvertimeTargetPoints: useState(viewDefaults.allStarOvertimeTargetPoints),
  allStarShootoutRounds: useState(viewDefaults.allStarShootoutRounds),
  allStarOvertimeType: useState(viewDefaults.allStarOvertimeType),
  allStarMaxOvertimesEnabled: useState(viewDefaults.allStarMaxOvertimesEnabled),
  allStarMaxOvertimes: useState(viewDefaults.allStarMaxOvertimes),
  allStarOvertimeTieBreaker: useState(viewDefaults.allStarOvertimeTieBreaker),
});

export const useGameRulesState = (leagueStats: LeagueStats) => ({
  gameFormat: useState<'timed' | 'target_score' | 'elam_ending'>(leagueStats.gameFormat ?? 'timed'),
  gameTargetScore: useState(leagueStats.gameTargetScore ?? 100),
  fourPointLine: useState(leagueStats.fourPointLine ?? false),
  threePointLineEnabled: useState(leagueStats.threePointLineEnabled ?? true),
  multiballCount: useState(leagueStats.multiballCount ?? 1),
  foulOutLimit: useState(leagueStats.foulOutLimit ?? 6),
  teamFoulPenalty: useState(leagueStats.teamFoulPenalty ?? 5),
  quarterLength: useState(leagueStats.quarterLength ?? 12),
  numQuarters: useState(leagueStats.numQuarters ?? 4),
  overtimeDuration: useState(leagueStats.overtimeDuration ?? 5),
  overtimeTargetPoints: useState(leagueStats.overtimeTargetPoints ?? 0),
  shootoutRounds: useState(leagueStats.shootoutRounds ?? 0),
  overtimeType: useState(leagueStats.overtimeType ?? 'standard'),
  maxTimeouts: useState(leagueStats.maxTimeouts ?? 7),
  coachChallenges: useState(leagueStats.coachChallenges ?? true),
  maxCoachChallenges: useState(leagueStats.maxCoachChallenges ?? 2),
  challengeReimbursed: useState(leagueStats.challengeReimbursed ?? true),
  shotClockEnabled: useState(leagueStats.shotClockEnabled ?? true),
  shotClockValue: useState(leagueStats.shotClockValue ?? 24),
  backcourtTimerEnabled: useState(leagueStats.backcourtTimerEnabled ?? true),
  backcourtTimerValue: useState(leagueStats.backcourtTimerValue ?? 8),
  offensiveThreeSecondEnabled: useState(leagueStats.offensiveThreeSecondEnabled ?? true),
  offensiveThreeSecondValue: useState(leagueStats.offensiveThreeSecondValue ?? 3),
  defensiveThreeSecondEnabled: useState(leagueStats.defensiveThreeSecondEnabled ?? true),
  defensiveThreeSecondValue: useState(leagueStats.defensiveThreeSecondValue ?? 3),
  inboundTimerEnabled: useState(leagueStats.inboundTimerEnabled ?? true),
  inboundTimerValue: useState(leagueStats.inboundTimerValue ?? 5),
  backToBasketTimerEnabled: useState(leagueStats.backToBasketTimerEnabled ?? true),
  backToBasketTimerValue: useState(leagueStats.backToBasketTimerValue ?? 5),
  backcourtViolationEnabled: useState(leagueStats.backcourtViolationEnabled ?? true),
  travelingEnabled: useState(leagueStats.travelingEnabled ?? true),
  doubleDribbleEnabled: useState(leagueStats.doubleDribbleEnabled ?? true),
  goaltendingEnabled: useState(leagueStats.goaltendingEnabled ?? true),
  basketInterferenceEnabled: useState(leagueStats.basketInterferenceEnabled ?? true),
  kickedBallEnabled: useState(leagueStats.kickedBallEnabled ?? true),
  flagrantFoulPenaltyEnabled: useState(leagueStats.flagrantFoulPenaltyEnabled ?? true),
  clearPathFoulEnabled: useState(leagueStats.clearPathFoulEnabled ?? true),
  illegalScreenEnabled: useState(leagueStats.illegalScreenEnabled ?? true),
  overTheBackFoulEnabled: useState(leagueStats.overTheBackFoulEnabled ?? true),
  looseBallFoulEnabled: useState(leagueStats.looseBallFoulEnabled ?? true),
  chargingEnabled: useState(leagueStats.chargingEnabled ?? true),
  overtimeEnabled: useState(leagueStats.overtimeEnabled ?? true),
  maxOvertimesEnabled: useState(leagueStats.maxOvertimesEnabled ?? false),
  maxOvertimes: useState(leagueStats.maxOvertimes ?? 0),
  overtimeTieBreaker: useState(leagueStats.overtimeTieBreaker ?? 'sudden_death'),
  maxPlayersOnCourt: useState(leagueStats.maxPlayersOnCourt ?? 5),
  substitutionLimitEnabled: useState(leagueStats.substitutionLimitEnabled ?? false),
  maxSubstitutions: useState(leagueStats.maxSubstitutions ?? 0),
  noDribbleRule: useState(leagueStats.noDribbleRule ?? false),
  multiballEnabled: useState(leagueStats.multiballEnabled ?? false),
  threePointLineDistance: useState(leagueStats.threePointLineDistance ?? 23.75),
  fourPointLineDistance: useState(leagueStats.fourPointLineDistance ?? 27),
  dunkValue: useState(leagueStats.dunkValue ?? 2),
  midrangeValue: useState(leagueStats.midrangeValue ?? 2),
  heaveRuleEnabled: useState(leagueStats.heaveRuleEnabled ?? false),
  halfCourtShotValue: useState(leagueStats.halfCourtShotValue ?? 3),
  clutchTimeoutLimit: useState(leagueStats.clutchTimeoutLimit ?? 2),
  handcheckingEnabled: useState(leagueStats.handcheckingEnabled ?? false),
  illegalZoneDefenseEnabled: useState(leagueStats.illegalZoneDefenseEnabled ?? false),
  outOfBoundsEnabled: useState(leagueStats.outOfBoundsEnabled ?? true),
  freeThrowDistance: useState(leagueStats.freeThrowDistance ?? 15),
  rimHeight: useState(leagueStats.rimHeight ?? 10),
  ballWeight: useState(leagueStats.ballWeight ?? 1.4),
  startOfPossessionMethod: useState(leagueStats.startOfPossessionMethod ?? 'jump_ball'),
  possessionPattern: useState(leagueStats.possessionPattern ?? 'nba'),
  courtLength: useState(leagueStats.courtLength ?? 94),
  baselineLength: useState(leagueStats.baselineLength ?? 50),
  keyWidth: useState(leagueStats.keyWidth ?? 16),
  cornerThrowInEnabled: useState(leagueStats.cornerThrowInEnabled ?? false),
  techEjectionLimit: useState(leagueStats.techEjectionLimit ?? 2),
  flagrant1EjectionLimit: useState(leagueStats.flagrant1EjectionLimit ?? 2),
  flagrant2EjectionLimit: useState(leagueStats.flagrant2EjectionLimit ?? 1),
  fightingInstantEjection: useState(leagueStats.fightingInstantEjection ?? true),
  useYellowRedCards: useState(leagueStats.useYellowRedCards ?? false),
  shotClockResetOffensiveRebound: useState(leagueStats.shotClockResetOffensiveRebound ?? 14),
});

export const useEconomyRulesState = (leagueStats: LeagueStats) => ({
  currency: useState(leagueStats.currency ?? 'USD'),
  tradesAllowed: useState(leagueStats.tradesAllowed ?? true),
  pbaLocalEligibilityMode: useState(leagueStats.pbaLocalEligibilityMode ?? 'registered_roster'),
  salaryCap: useState(leagueStats.salaryCap ?? 154647000),
  salaryCapEnabled: useState(leagueStats.salaryCapEnabled ?? true),
  salaryCapType: useState(leagueStats.salaryCapType ?? 'soft'),
  minimumPayrollEnabled: useState(leagueStats.minimumPayrollEnabled ?? true),
  minimumPayrollPercentage: useState(leagueStats.minimumPayrollPercentage ?? 90),
  luxuryTaxEnabled: useState(leagueStats.luxuryTaxEnabled ?? true),
  luxuryTaxThresholdPercentage: useState(leagueStats.luxuryTaxThresholdPercentage ?? 121.5),
  apronsEnabled: useState(leagueStats.apronsEnabled ?? true),
  numberOfAprons: useState(leagueStats.numberOfAprons ?? 2),
  firstApronPercentage: useState(leagueStats.firstApronPercentage ?? 126.7),
  secondApronPercentage: useState(leagueStats.secondApronPercentage ?? 134.4),
  tradeMatchingRatioUnder: useState(leagueStats.tradeMatchingRatioUnder ?? 1.25),
  tradeMatchingRatioOver1st: useState(leagueStats.tradeMatchingRatioOver1st ?? 1.10),
  tradeMatchingRatioOver2nd: useState(leagueStats.tradeMatchingRatioOver2nd ?? 1.00),
  restrictCashSendOver2ndApron: useState(leagueStats.restrictCashSendOver2ndApron ?? true),
  restrictAggregationOver2ndApron: useState(leagueStats.restrictAggregationOver2ndApron ?? true),
  restrictSignAndTradeAcquisitionOver1stApron: useState(leagueStats.restrictSignAndTradeAcquisitionOver1stApron ?? true),
  freezePickAt2ndApron: useState(leagueStats.freezePickAt2ndApron ?? true),
  restrictTPEProvenanceOver2ndApron: useState(leagueStats.restrictTPEProvenanceOver2ndApron ?? true),
  postSigningMoratoriumEnabled: useState(leagueStats.postSigningMoratoriumEnabled ?? true),
  twoWayContractsEnabled: useState(leagueStats.twoWayContractsEnabled ?? true),
  nonGuaranteedContractsEnabled: useState(leagueStats.nonGuaranteedContractsEnabled ?? true),
  minPlayersPerTeam: useState(leagueStats.minPlayersPerTeam ?? 14),
  maxPlayersPerTeam: useState(leagueStats.maxPlayersPerTeam ?? 17),
  maxStandardPlayersPerTeam: useState(leagueStats.maxStandardPlayersPerTeam ?? 15),
  maxTwoWayPlayersPerTeam: useState(leagueStats.maxTwoWayPlayersPerTeam ?? 3),
  maxTrainingCampRoster: useState(leagueStats.maxTrainingCampRoster ?? 21),
  minContractType: useState(leagueStats.minContractType ?? 'dynamic'),
  minContractStaticAmount: useState(leagueStats.minContractStaticAmount ?? 1.27287),
  maxContractType: useState(leagueStats.maxContractType ?? 'service_tiered'),
  maxContractStaticPercentage: useState(leagueStats.maxContractStaticPercentage ?? 30),
  supermaxEnabled: useState(leagueStats.supermaxEnabled ?? true),
  supermaxPercentage: useState(leagueStats.supermaxPercentage ?? 35),
  supermaxMinYears: useState(leagueStats.supermaxMinYears ?? 8),
  rookieExtEnabled: useState(leagueStats.rookieExtEnabled ?? true),
  rookieExtPct: useState(leagueStats.rookieExtPct ?? 25),
  rookieExtRosePct: useState(leagueStats.rookieExtRosePct ?? 30),
  birdRightsEnabled: useState(leagueStats.birdRightsEnabled ?? true),
  minContractLength: useState(leagueStats.minContractLength ?? 1),
  maxContractLengthStandard: useState(leagueStats.maxContractLengthStandard ?? 4),
  maxContractLengthBird: useState(leagueStats.maxContractLengthBird ?? 5),
  playerOptionsEnabled: useState(leagueStats.playerOptionsEnabled ?? true),
  tenDayContractsEnabled: useState(leagueStats.tenDayContractsEnabled ?? true),
  inflationEnabled: useState(leagueStats.inflationEnabled ?? true),
  inflationMin: useState(leagueStats.inflationMin ?? 0),
  inflationMax: useState(leagueStats.inflationMax ?? 10),
  inflationAverage: useState(leagueStats.inflationAverage ?? 5.5),
  inflationStdDev: useState(leagueStats.inflationStdDev ?? 2.0),
  mleEnabled: useState(leagueStats.mleEnabled ?? true),
  roomMleAmount: useState(leagueStats.roomMleAmount ?? 8_781_000),
  nonTaxpayerMleAmount: useState(leagueStats.nonTaxpayerMleAmount ?? 14_104_000),
  taxpayerMleAmount: useState(leagueStats.taxpayerMleAmount ?? 5_685_000),
  biannualEnabled: useState(leagueStats.biannualEnabled ?? true),
  biannualAmount: useState(leagueStats.biannualAmount ?? 4_767_000),
  roomMlePercentage: useState((leagueStats as any).roomMlePercentage ?? 5.68),
  nonTaxpayerMlePercentage: useState((leagueStats as any).nonTaxpayerMlePercentage ?? 9.12),
  taxpayerMlePercentage: useState((leagueStats as any).taxpayerMlePercentage ?? 3.68),
  biannualPercentage: useState((leagueStats as any).biannualPercentage ?? 3.08),
  tradableDraftPickSeasons: useState(leagueStats.tradableDraftPickSeasons ?? 7),
  stepienRuleEnabled: useState(leagueStats.stepienRuleEnabled ?? true),
  tradeExceptionsEnabled: useState(leagueStats.tradeExceptionsEnabled ?? true),
  disabledPlayerExceptionEnabled: useState(leagueStats.disabledPlayerExceptionEnabled ?? false),
  deadMoneyEnabled: useState((leagueStats as any).deadMoneyEnabled ?? true),
  ngGuaranteeDeadlineMonth: useState((leagueStats as any).ngGuaranteeDeadlineMonth ?? 1),
  ngGuaranteeDeadlineDay: useState((leagueStats as any).ngGuaranteeDeadlineDay ?? 10),
  stretchProvisionEnabled: useState((leagueStats as any).stretchProvisionEnabled ?? true),
  stretchProvisionMultiplier: useState((leagueStats as any).stretchProvisionMultiplier ?? 2),
  stretchedDeadMoneyCapPct: useState((leagueStats as any).stretchedDeadMoneyCapPct ?? 15),
  rfaMatchingEnabled: useState((leagueStats as any).rfaMatchingEnabled ?? true),
  rfaMatchWindowDays: useState((leagueStats as any).rfaMatchWindowDays ?? 2),
  rfaAutoDeclineOver2ndApron: useState((leagueStats as any).rfaAutoDeclineOver2ndApron ?? true),
  tradeDeadlineMonth: useState(leagueStats.tradeDeadlineMonth ?? 2),
  tradeDeadlineOrdinal: useState(leagueStats.tradeDeadlineOrdinal ?? 1),
  tradeDeadlineDayOfWeek: useState<'Sun' | 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat'>(leagueStats.tradeDeadlineDayOfWeek ?? 'Thu'),
  faStartMonth: useState(leagueStats.faStartMonth ?? 7),
  faStartDay: useState(leagueStats.faStartDay ?? 1),
  faMoratoriumDays: useState(leagueStats.faMoratoriumDays ?? 0),
  regularSeasonFAEnabled: useState(leagueStats.regularSeasonFAEnabled ?? true),
  postDeadlineMultiYearContracts: useState(leagueStats.postDeadlineMultiYearContracts ?? true),
  rookieScaleType: useState(leagueStats.rookieScaleType ?? 'dynamic'),
  rookieStaticAmount: useState(leagueStats.rookieStaticAmount ?? 5.0),
  rookieMaxContractPercentage: useState(leagueStats.rookieMaxContractPercentage ?? 9),
  rookieScaleAppliesTo: useState(leagueStats.rookieScaleAppliesTo ?? 'first_round'),
  rookieContractLength: useState(leagueStats.rookieContractLength ?? 2),
  rookieTeamOptionsEnabled: useState(leagueStats.rookieTeamOptionsEnabled ?? true),
  rookieTeamOptionYears: useState(leagueStats.rookieTeamOptionYears ?? 2),
  rookieRestrictedFreeAgentEligibility: useState(leagueStats.rookieRestrictedFreeAgentEligibility ?? true),
  rookieContractCapException: useState(leagueStats.rookieContractCapException ?? true),
  r2ContractsNonGuaranteed: useState(leagueStats.r2ContractsNonGuaranteed ?? true),
});

export const useHonorsRulesState = (leagueStats: LeagueStats) => ({
  allNbaTeams: useState(leagueStats.allNbaTeams ?? 3),
  allNbaPlayersPerTeam: useState(leagueStats.allNbaPlayersPerTeam ?? 5),
  allDefenseTeams: useState(leagueStats.allDefenseTeams ?? 2),
  allDefensePlayersPerTeam: useState(leagueStats.allDefensePlayersPerTeam ?? 5),
  allRookieTeams: useState(leagueStats.allRookieTeams ?? 2),
  allRookiePlayersPerTeam: useState(leagueStats.allRookiePlayersPerTeam ?? 5),
  positionlessAwards: useState(leagueStats.positionlessAwards ?? false),
});
