// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

import { twoKAssetManifestCategoriesA } from './assetManifestCategoriesA';
import { twoKAssetManifestCategoriesB } from './assetManifestCategoriesB';
import { twoKAssetManifestSampleUnmatched } from './assetManifestSampleUnmatched';
import { twoKAssetManifestStaffTeamA } from './assetManifestStaffTeamA';
import { twoKAssetManifestStaffTeamB } from './assetManifestStaffTeamB';
import { twoKAssetManifestStaffTeamC } from './assetManifestStaffTeamC';

export const twoKAssetManifest = {
  sourceRoot: 'C:\\Program Files (x86)\\2K Sports\\NBA 2K14',
  categories: {
    ...twoKAssetManifestCategoriesA,
    ...twoKAssetManifestCategoriesB,
    staff_team: [
      ...twoKAssetManifestStaffTeamA,
      ...twoKAssetManifestStaffTeamB,
      ...twoKAssetManifestStaffTeamC,
    ],
  },
  counts: {
    career: 5,
    coaches: 4,
    draft: 66,
    franchise: 3,
    presentation: 67,
    schedule: 2,
    social: 2,
    staff_team: 200,
    tutorial: 3,
  },
  sampleUnmatched: twoKAssetManifestSampleUnmatched,
} as const;
