// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifestCategoriesB = {
    "presentation": [
      {
        "name": "2kbackendwipe.iff",
        "size": 2435609,
        "extension": ".iff"
      },
      {
        "name": "3ptcontestscorebug.iff",
        "size": 202153,
        "extension": ".iff"
      },
      {
        "name": "allstar_loading.iff",
        "size": 380673,
        "extension": ".iff"
      },
      {
        "name": "assdrillsloading.iff",
        "size": 215514,
        "extension": ".iff"
      },
      {
        "name": "cardgameloading.iff",
        "size": 654329,
        "extension": ".iff"
      },
      {
        "name": "careerdrillsloading.iff",
        "size": 423942,
        "extension": ".iff"
      },
      {
        "name": "defaultloadingscreen.iff",
        "size": 65800,
        "extension": ".iff"
      },
      {
        "name": "director2_loadinganimation.iff",
        "size": 37460,
        "extension": ".iff"
      },
      {
        "name": "drillsknockoutscorebug.iff",
        "size": 316939,
        "extension": ".iff"
      },
      {
        "name": "drillsscorebug.iff",
        "size": 131410,
        "extension": ".iff"
      },
      {
        "name": "drillsshootoutscorebug.iff",
        "size": 180134,
        "extension": ".iff"
      },
      {
        "name": "dunkcontestoverlay.iff",
        "size": 624073,
        "extension": ".iff"
      },
      {
        "name": "dunkcontestscorebug.iff",
        "size": 184551,
        "extension": ".iff"
      },
      {
        "name": "fastbreakscorebug1.iff",
        "size": 185171,
        "extension": ".iff"
      },
      {
        "name": "gooeyoverlaysstatic.iff",
        "size": 1458858,
        "extension": ".iff"
      },
      {
        "name": "halftimerookieshowcase.iff",
        "size": 246670,
        "extension": ".iff"
      },
      {
        "name": "halftimesponsorwatermark.iff",
        "size": 15022,
        "extension": ".iff"
      },
      {
        "name": "lebronmodeloading.iff",
        "size": 621419,
        "extension": ".iff"
      },
      {
        "name": "loading_audio.iff",
        "size": 150378,
        "extension": ".iff"
      },
      {
        "name": "loading_static.iff",
        "size": 721451,
        "extension": ".iff"
      },
      {
        "name": "loadingflow.iff",
        "size": 351383,
        "extension": ".iff"
      },
      {
        "name": "loadingsequence.bin",
        "size": 443974,
        "extension": ".bin"
      },
      {
        "name": "loadingsequencejz.bin",
        "size": 91222,
        "extension": ".bin"
      },
      {
        "name": "loadingsequencelebron.bin",
        "size": 92710,
        "extension": ".bin"
      },
      {
        "name": "loadingvo.bin",
        "size": 30337168,
        "extension": ".bin"
      },
      {
        "name": "loadingvo_ps.bin",
        "size": 12846028,
        "extension": ".bin"
      },
      {
        "name": "loadingvo_ts.bin",
        "size": 16011208,
        "extension": ".bin"
      },
      {
        "name": "myplayerloading.iff",
        "size": 1118908,
        "extension": ".iff"
      },
      {
        "name": "nbablacktoploading.iff",
        "size": 644434,
        "extension": ".iff"
      },
      {
        "name": "newscorebug.iff",
        "size": 304556,
        "extension": ".iff"
      },
      {
        "name": "onlinecrewloading.iff",
        "size": 286078,
        "extension": ".iff"
      },
      {
        "name": "onlinehalftimepanel.iff",
        "size": 342474,
        "extension": ".iff"
      },
      {
        "name": "onlinehalftimevs.iff",
        "size": 308947,
        "extension": ".iff"
      },
      {
        "name": "onlinepickuploading.iff",
        "size": 286632,
        "extension": ".iff"
      },
      {
        "name": "onlineteamuploading.iff",
        "size": 408420,
        "extension": ".iff"
      },
      {
        "name": "onlineversusloading.iff",
        "size": 375731,
        "extension": ".iff"
      },
      {
        "name": "overlay_extra.iff",
        "size": 215123,
        "extension": ".iff"
      },
      {
        "name": "overlay_gooey.iff",
        "size": 2916,
        "extension": ".iff"
      },
      {
        "name": "overlay_loaded.iff",
        "size": 477,
        "extension": ".iff"
      },
      {
        "name": "overlay_static.iff",
        "size": 42182,
        "extension": ".iff"
      },
      {
        "name": "playerwipe.iff",
        "size": 286376,
        "extension": ".iff"
      },
      {
        "name": "scorebugstreet.iff",
        "size": 120456,
        "extension": ".iff"
      },
      {
        "name": "singleplayerdrillsscorebug.iff",
        "size": 179564,
        "extension": ".iff"
      },
      {
        "name": "singleplayerdrillsscorebug2.iff",
        "size": 175336,
        "extension": ".iff"
      },
      {
        "name": "slaboverlay.iff",
        "size": 243421,
        "extension": ".iff"
      },
      {
        "name": "studioshow.iff",
        "size": 801920,
        "extension": ".iff"
      },
      {
        "name": "studioshowwipes.iff",
        "size": 222648,
        "extension": ".iff"
      },
      {
        "name": "teamwipe.iff",
        "size": 266352,
        "extension": ".iff"
      },
      {
        "name": "titlecardoverlay.iff",
        "size": 260495,
        "extension": ".iff"
      },
      {
        "name": "tombstoneoverlay.iff",
        "size": 233335,
        "extension": ".iff"
      },
      {
        "name": "trainingcamploading.iff",
        "size": 245337,
        "extension": ".iff"
      },
      {
        "name": "trainingcampscorebug.iff",
        "size": 133967,
        "extension": ".iff"
      },
      {
        "name": "wipeallstargeneric.iff",
        "size": 335858,
        "extension": ".iff"
      },
      {
        "name": "wipeallstarweekend.iff",
        "size": 539772,
        "extension": ".iff"
      },
      {
        "name": "wipedayofweek.iff",
        "size": 285383,
        "extension": ".iff"
      },
      {
        "name": "wipedirectorcut.iff",
        "size": 313650,
        "extension": ".iff"
      },
      {
        "name": "wipefinals.iff",
        "size": 621700,
        "extension": ".iff"
      },
      {
        "name": "wipenikeplus.iff",
        "size": 75211,
        "extension": ".iff"
      },
      {
        "name": "wipeonthemove.iff",
        "size": 289316,
        "extension": ".iff"
      },
      {
        "name": "wipeplayoffs.iff",
        "size": 468493,
        "extension": ".iff"
      },
      {
        "name": "wipereplayreview.iff",
        "size": 246360,
        "extension": ".iff"
      },
      {
        "name": "wipesprite.iff",
        "size": 114029,
        "extension": ".iff"
      },
      {
        "name": "wipespriteallstarweekend.iff",
        "size": 542545,
        "extension": ".iff"
      },
      {
        "name": "wipespritedunkcontest.iff",
        "size": 123699,
        "extension": ".iff"
      },
      {
        "name": "wipespriteuncontainable.iff",
        "size": 144592,
        "extension": ".iff"
      },
      {
        "name": "wipeteammatchup.iff",
        "size": 129573,
        "extension": ".iff"
      },
      {
        "name": "wipewarpdunk3pt.iff",
        "size": 172759,
        "extension": ".iff"
      }
    ],
    "schedule": [
      {
        "name": "lastseasonschedule.iff",
        "size": 16010,
        "extension": ".iff"
      },
      {
        "name": "upcomingschedule.iff",
        "size": 190854,
        "extension": ".iff"
      }
    ],
    "social": [
      {
        "name": "socialmedia_profilepics.iff",
        "size": 379300,
        "extension": ".iff"
      },
      {
        "name": "twitter_messages.iff",
        "size": 965743,
        "extension": ".iff"
      }
    ],
    "tutorial": [
      {
        "name": "tutorial_screenshots.iff",
        "size": 377208,
        "extension": ".iff"
      },
      {
        "name": "tutorialcontrollerdisplay.iff",
        "size": 935043,
        "extension": ".iff"
      },
      {
        "name": "tutorialmenulist.iff",
        "size": 199700,
        "extension": ".iff"
      }
    ]
} as const;
