// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifestStaffTeamA = [
      {
        "name": "team_000.iff",
        "size": 645485,
        "extension": ".iff"
      },
      {
        "name": "team_001.iff",
        "size": 656798,
        "extension": ".iff"
      },
      {
        "name": "team_002.iff",
        "size": 2335843,
        "extension": ".iff"
      },
      {
        "name": "team_003.iff",
        "size": 2840807,
        "extension": ".iff"
      },
      {
        "name": "team_004.iff",
        "size": 670131,
        "extension": ".iff"
      },
      {
        "name": "team_005.iff",
        "size": 656958,
        "extension": ".iff"
      },
      {
        "name": "team_006.iff",
        "size": 665049,
        "extension": ".iff"
      },
      {
        "name": "team_007.iff",
        "size": 624962,
        "extension": ".iff"
      },
      {
        "name": "team_008.iff",
        "size": 2763661,
        "extension": ".iff"
      },
      {
        "name": "team_009.iff",
        "size": 2928331,
        "extension": ".iff"
      },
      {
        "name": "team_010.iff",
        "size": 627700,
        "extension": ".iff"
      },
      {
        "name": "team_011.iff",
        "size": 628646,
        "extension": ".iff"
      },
      {
        "name": "team_012.iff",
        "size": 627481,
        "extension": ".iff"
      },
      {
        "name": "team_013.iff",
        "size": 3012681,
        "extension": ".iff"
      },
      {
        "name": "team_014.iff",
        "size": 636158,
        "extension": ".iff"
      },
      {
        "name": "team_015.iff",
        "size": 654292,
        "extension": ".iff"
      },
      {
        "name": "team_016.iff",
        "size": 662140,
        "extension": ".iff"
      },
      {
        "name": "team_017.iff",
        "size": 2813907,
        "extension": ".iff"
      },
      {
        "name": "team_018.iff",
        "size": 617282,
        "extension": ".iff"
      },
      {
        "name": "team_019.iff",
        "size": 2653113,
        "extension": ".iff"
      },
      {
        "name": "team_020.iff",
        "size": 2882974,
        "extension": ".iff"
      },
      {
        "name": "team_021.iff",
        "size": 666711,
        "extension": ".iff"
      },
      {
        "name": "team_022.iff",
        "size": 2877202,
        "extension": ".iff"
      },
      {
        "name": "team_023.iff",
        "size": 2887811,
        "extension": ".iff"
      },
      {
        "name": "team_024.iff",
        "size": 2839982,
        "extension": ".iff"
      },
      {
        "name": "team_025.iff",
        "size": 632226,
        "extension": ".iff"
      },
      {
        "name": "team_026.iff",
        "size": 2891023,
        "extension": ".iff"
      },
      {
        "name": "team_027.iff",
        "size": 2752860,
        "extension": ".iff"
      },
      {
        "name": "team_028.iff",
        "size": 2647106,
        "extension": ".iff"
      },
      {
        "name": "team_029.iff",
        "size": 633772,
        "extension": ".iff"
      },
      {
        "name": "team_030.iff",
        "size": 624630,
        "extension": ".iff"
      },
      {
        "name": "team_031.iff",
        "size": 2862472,
        "extension": ".iff"
      },
      {
        "name": "team_070.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_071.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_072.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_073.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_074.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_075.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_076.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_077.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_078.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_079.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_080.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_081.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_082.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_083.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_100.iff",
        "size": 627632,
        "extension": ".iff"
      },
      {
        "name": "team_101.iff",
        "size": 627065,
        "extension": ".iff"
      },
      {
        "name": "team_102.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_103.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_104.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_105.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_106.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_108.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_109.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_110.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_111.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_112.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_113.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_114.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_115.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_116.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_117.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_118.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_119.iff",
        "size": 625204,
        "extension": ".iff"
      },
];
