// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifestStaffTeamB = [
      {
        "name": "team_120.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_121.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_122.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_123.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_124.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_125.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_126.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_127.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_128.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_129.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_131.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_401.iff",
        "size": 2942986,
        "extension": ".iff"
      },
      {
        "name": "team_402.iff",
        "size": 592448,
        "extension": ".iff"
      },
      {
        "name": "team_403.iff",
        "size": 546727,
        "extension": ".iff"
      },
      {
        "name": "team_404.iff",
        "size": 600803,
        "extension": ".iff"
      },
      {
        "name": "team_405.iff",
        "size": 559436,
        "extension": ".iff"
      },
      {
        "name": "team_406.iff",
        "size": 575647,
        "extension": ".iff"
      },
      {
        "name": "team_407.iff",
        "size": 554722,
        "extension": ".iff"
      },
      {
        "name": "team_408.iff",
        "size": 2840676,
        "extension": ".iff"
      },
      {
        "name": "team_409.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_410.iff",
        "size": 615189,
        "extension": ".iff"
      },
      {
        "name": "team_411.iff",
        "size": 597098,
        "extension": ".iff"
      },
      {
        "name": "team_412.iff",
        "size": 2815304,
        "extension": ".iff"
      },
      {
        "name": "team_413.iff",
        "size": 2577282,
        "extension": ".iff"
      },
      {
        "name": "team_414.iff",
        "size": 592448,
        "extension": ".iff"
      },
      {
        "name": "team_415.iff",
        "size": 2787136,
        "extension": ".iff"
      },
      {
        "name": "team_416.iff",
        "size": 2740123,
        "extension": ".iff"
      },
      {
        "name": "team_417.iff",
        "size": 2781559,
        "extension": ".iff"
      },
      {
        "name": "team_418.iff",
        "size": 575647,
        "extension": ".iff"
      },
      {
        "name": "team_419.iff",
        "size": 2807037,
        "extension": ".iff"
      },
      {
        "name": "team_420.iff",
        "size": 559436,
        "extension": ".iff"
      },
      {
        "name": "team_421.iff",
        "size": 596342,
        "extension": ".iff"
      },
      {
        "name": "team_422.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_423.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_424.iff",
        "size": 2809812,
        "extension": ".iff"
      },
      {
        "name": "team_425.iff",
        "size": 598113,
        "extension": ".iff"
      },
      {
        "name": "team_426.iff",
        "size": 654292,
        "extension": ".iff"
      },
      {
        "name": "team_427.iff",
        "size": 585155,
        "extension": ".iff"
      },
      {
        "name": "team_428.iff",
        "size": 2653113,
        "extension": ".iff"
      },
      {
        "name": "team_500.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_501.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_502.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_503.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_504.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_505.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_506.iff",
        "size": 437457,
        "extension": ".iff"
      },
      {
        "name": "team_507.iff",
        "size": 445593,
        "extension": ".iff"
      },
      {
        "name": "team_508.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_509.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_510.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_511.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_515.iff",
        "size": 531696,
        "extension": ".iff"
      },
      {
        "name": "team_516.iff",
        "size": 667245,
        "extension": ".iff"
      },
      {
        "name": "team_517.iff",
        "size": 561768,
        "extension": ".iff"
      },
      {
        "name": "team_518.iff",
        "size": 659793,
        "extension": ".iff"
      },
      {
        "name": "team_519.iff",
        "size": 678290,
        "extension": ".iff"
      },
      {
        "name": "team_520.iff",
        "size": 560044,
        "extension": ".iff"
      },
      {
        "name": "team_521.iff",
        "size": 532927,
        "extension": ".iff"
      },
      {
        "name": "team_522.iff",
        "size": 668632,
        "extension": ".iff"
      },
      {
        "name": "team_523.iff",
        "size": 654926,
        "extension": ".iff"
      },
      {
        "name": "team_524.iff",
        "size": 675633,
        "extension": ".iff"
      },
      {
        "name": "team_525.iff",
        "size": 664119,
        "extension": ".iff"
      },
      {
        "name": "team_526.iff",
        "size": 648672,
        "extension": ".iff"
      },
      {
        "name": "team_527.iff",
        "size": 668507,
        "extension": ".iff"
      },
      {
        "name": "team_528.iff",
        "size": 683317,
        "extension": ".iff"
      },
      {
        "name": "team_529.iff",
        "size": 657465,
        "extension": ".iff"
      },
      {
        "name": "team_530.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_531.iff",
        "size": 577611,
        "extension": ".iff"
      },
];
