// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifestStaffTeamC = [
      {
        "name": "team_532.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_533.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_534.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_535.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_536.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_537.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_551.iff",
        "size": 2831823,
        "extension": ".iff"
      },
      {
        "name": "team_552.iff",
        "size": 645704,
        "extension": ".iff"
      },
      {
        "name": "team_553.iff",
        "size": 2667998,
        "extension": ".iff"
      },
      {
        "name": "team_555.iff",
        "size": 621968,
        "extension": ".iff"
      },
      {
        "name": "team_557.iff",
        "size": 622671,
        "extension": ".iff"
      },
      {
        "name": "team_560.iff",
        "size": 623861,
        "extension": ".iff"
      },
      {
        "name": "team_561.iff",
        "size": 2832063,
        "extension": ".iff"
      },
      {
        "name": "team_562.iff",
        "size": 622622,
        "extension": ".iff"
      },
      {
        "name": "team_563.iff",
        "size": 663764,
        "extension": ".iff"
      },
      {
        "name": "team_564.iff",
        "size": 667947,
        "extension": ".iff"
      },
      {
        "name": "team_565.iff",
        "size": 2832058,
        "extension": ".iff"
      },
      {
        "name": "team_566.iff",
        "size": 627906,
        "extension": ".iff"
      },
      {
        "name": "team_567.iff",
        "size": 2831489,
        "extension": ".iff"
      },
      {
        "name": "team_568.iff",
        "size": 2831457,
        "extension": ".iff"
      },
      {
        "name": "team_569.iff",
        "size": 656855,
        "extension": ".iff"
      },
      {
        "name": "team_570.iff",
        "size": 618286,
        "extension": ".iff"
      },
      {
        "name": "team_571.iff",
        "size": 651512,
        "extension": ".iff"
      },
      {
        "name": "team_572.iff",
        "size": 625566,
        "extension": ".iff"
      },
      {
        "name": "team_573.iff",
        "size": 625513,
        "extension": ".iff"
      },
      {
        "name": "team_574.iff",
        "size": 630483,
        "extension": ".iff"
      },
      {
        "name": "team_575.iff",
        "size": 638900,
        "extension": ".iff"
      },
      {
        "name": "team_576.iff",
        "size": 653874,
        "extension": ".iff"
      },
      {
        "name": "team_577.iff",
        "size": 649488,
        "extension": ".iff"
      },
      {
        "name": "team_578.iff",
        "size": 625552,
        "extension": ".iff"
      },
      {
        "name": "team_579.iff",
        "size": 645694,
        "extension": ".iff"
      },
      {
        "name": "team_580.iff",
        "size": 2831731,
        "extension": ".iff"
      },
      {
        "name": "team_582.iff",
        "size": 624074,
        "extension": ".iff"
      },
      {
        "name": "team_583.iff",
        "size": 621348,
        "extension": ".iff"
      },
      {
        "name": "team_584.iff",
        "size": 2581480,
        "extension": ".iff"
      },
      {
        "name": "team_585.iff",
        "size": 627350,
        "extension": ".iff"
      },
      {
        "name": "team_586.iff",
        "size": 636547,
        "extension": ".iff"
      },
      {
        "name": "team_588.iff",
        "size": 624128,
        "extension": ".iff"
      },
      {
        "name": "team_589.iff",
        "size": 640680,
        "extension": ".iff"
      },
      {
        "name": "team_590.iff",
        "size": 646345,
        "extension": ".iff"
      },
      {
        "name": "team_591.iff",
        "size": 625414,
        "extension": ".iff"
      },
      {
        "name": "team_592.iff",
        "size": 632373,
        "extension": ".iff"
      },
      {
        "name": "team_594.iff",
        "size": 622304,
        "extension": ".iff"
      },
      {
        "name": "team_595.iff",
        "size": 644318,
        "extension": ".iff"
      },
      {
        "name": "team_604.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_605.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_800.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_801.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_802.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_803.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_804.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_805.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_806.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_807.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_808.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_809.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_810.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_811.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_812.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_813.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_814.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_815.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_816.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_817.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_818.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_819.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_820.iff",
        "size": 577611,
        "extension": ".iff"
      }
];
