// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifestCategoriesA = {
    "career": [
      {
        "name": "career.iff",
        "size": 2968860,
        "extension": ".iff"
      },
      {
        "name": "career_endorsements.iff",
        "size": 66793052,
        "extension": ".iff"
      },
      {
        "name": "careerdrillsloading.iff",
        "size": 423942,
        "extension": ".iff"
      },
      {
        "name": "careerupdaterecap.iff",
        "size": 297557,
        "extension": ".iff"
      },
      {
        "name": "gooeycareermode.iff",
        "size": 210743,
        "extension": ".iff"
      }
    ],
    "coaches": [
      {
        "name": "animations_teaser_anm_2k11_amb_intro_locker_room_coach.iff",
        "size": 197127,
        "extension": ".iff"
      },
      {
        "name": "coaches.bin",
        "size": 3116578,
        "extension": ".bin"
      },
      {
        "name": "snapshot_coach_1.iff",
        "size": 582,
        "extension": ".iff"
      },
      {
        "name": "snapshot_coach_2.iff",
        "size": 568,
        "extension": ".iff"
      }
    ],
    "draft": [
      {
        "name": "cwdresloop_idle_draft_01.iff",
        "size": 2144585,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_ahh-front.cdf",
        "size": 227952,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_ahh-front.iff",
        "size": 646,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_ahh-rear.cdf",
        "size": 227778,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_ahh-rear.iff",
        "size": 636,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_boo-front.cdf",
        "size": 1472438,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_boo-front.iff",
        "size": 1518,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_boo-rear.cdf",
        "size": 1531490,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_boo-rear.iff",
        "size": 1492,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-explode.cdf",
        "size": 348506,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-explode.iff",
        "size": 920,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-front.cdf",
        "size": 4957870,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-front.iff",
        "size": 3126,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-rear.cdf",
        "size": 5004973,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-rear.iff",
        "size": 3076,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-med-front.cdf",
        "size": 2416924,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-med-front.iff",
        "size": 3126,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-med-rear.cdf",
        "size": 2274769,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-med-rear.iff",
        "size": 3076,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-front.cdf",
        "size": 623415,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-front.iff",
        "size": 1190,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-rear.cdf",
        "size": 626262,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-rear.iff",
        "size": 1172,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_freethrow-front.cdf",
        "size": 263233,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_freethrow-front.iff",
        "size": 706,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_freethrow-rear.cdf",
        "size": 262143,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_freethrow-rear.iff",
        "size": 696,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-lrg.cdf",
        "size": 2139110,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-lrg.iff",
        "size": 2926,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-med.cdf",
        "size": 1374174,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-med.iff",
        "size": 2248,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-lrg.cdf",
        "size": 1608835,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-lrg.iff",
        "size": 2474,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-med.cdf",
        "size": 1316681,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-med.iff",
        "size": 2248,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-fast.cdf",
        "size": 343257,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-fast.iff",
        "size": 850,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-hsc-lrg.cdf",
        "size": 377356,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-hsc-lrg.iff",
        "size": 892,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-lrg.cdf",
        "size": 1599149,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-lrg.iff",
        "size": 2096,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-med.cdf",
        "size": 1058129,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-med.iff",
        "size": 1886,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-shoot.cdf",
        "size": 667607,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-shoot.iff",
        "size": 1300,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-sml.cdf",
        "size": 1042708,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-sml.iff",
        "size": 1676,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_small-ahh-front.cdf",
        "size": 482610,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_small-ahh-front.iff",
        "size": 1190,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_small-ahh-rear.cdf",
        "size": 463104,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_small-ahh-rear.iff",
        "size": 1172,
        "extension": ".iff"
      },
      {
        "name": "director2_draft.iff",
        "size": 23435,
        "extension": ".iff"
      },
      {
        "name": "draft_lines.bin",
        "size": 26472314,
        "extension": ".bin"
      },
      {
        "name": "draft_players.bin",
        "size": 28592874,
        "extension": ".bin"
      },
      {
        "name": "draft_ps.bin",
        "size": 12824650,
        "extension": ".bin"
      },
      {
        "name": "draft_ts.bin",
        "size": 6691156,
        "extension": ".bin"
      },
      {
        "name": "draftroom.iff",
        "size": 4142215,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions.iff",
        "size": 759814,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_english.iff",
        "size": 47637,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_french.iff",
        "size": 43844,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_german.iff",
        "size": 47185,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_italian.iff",
        "size": 42392,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_japanese.iff",
        "size": 37198,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_spanish.iff",
        "size": 43099,
        "extension": ".iff"
      },
      {
        "name": "snapshot_background_2013draftclass.iff",
        "size": 491712,
        "extension": ".iff"
      },
      {
        "name": "snapshot_background_draft_lottery.iff",
        "size": 403311,
        "extension": ".iff"
      }
    ],
    "franchise": [
      {
        "name": "franchise.iff",
        "size": 1612117,
        "extension": ".iff"
      },
      {
        "name": "franchiseserver.iff",
        "size": 69954,
        "extension": ".iff"
      },
      {
        "name": "gooey_franchise.iff",
        "size": 467920,
        "extension": ".iff"
      }
    ],
} as const;
