// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKAssetManifest = {
  "sourceRoot": "C:\\Program Files (x86)\\2K Sports\\NBA 2K14",
  "categories": {
    "career": [
      {
        "name": "career.iff",
        "size": 2968860,
        "extension": ".iff"
      },
      {
        "name": "career_endorsements.iff",
        "size": 66793052,
        "extension": ".iff"
      },
      {
        "name": "careerdrillsloading.iff",
        "size": 423942,
        "extension": ".iff"
      },
      {
        "name": "careerupdaterecap.iff",
        "size": 297557,
        "extension": ".iff"
      },
      {
        "name": "gooeycareermode.iff",
        "size": 210743,
        "extension": ".iff"
      }
    ],
    "coaches": [
      {
        "name": "animations_teaser_anm_2k11_amb_intro_locker_room_coach.iff",
        "size": 197127,
        "extension": ".iff"
      },
      {
        "name": "coaches.bin",
        "size": 3116578,
        "extension": ".bin"
      },
      {
        "name": "snapshot_coach_1.iff",
        "size": 582,
        "extension": ".iff"
      },
      {
        "name": "snapshot_coach_2.iff",
        "size": 568,
        "extension": ".iff"
      }
    ],
    "draft": [
      {
        "name": "cwdresloop_idle_draft_01.iff",
        "size": 2144585,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_ahh-front.cdf",
        "size": 227952,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_ahh-front.iff",
        "size": 646,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_ahh-rear.cdf",
        "size": 227778,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_ahh-rear.iff",
        "size": 636,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_boo-front.cdf",
        "size": 1472438,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_boo-front.iff",
        "size": 1518,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_boo-rear.cdf",
        "size": 1531490,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_boo-rear.iff",
        "size": 1492,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-explode.cdf",
        "size": 348506,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-explode.iff",
        "size": 920,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-front.cdf",
        "size": 4957870,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-front.iff",
        "size": 3126,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-rear.cdf",
        "size": 5004973,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-lrg-rear.iff",
        "size": 3076,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-med-front.cdf",
        "size": 2416924,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-med-front.iff",
        "size": 3126,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-med-rear.cdf",
        "size": 2274769,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-med-rear.iff",
        "size": 3076,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-front.cdf",
        "size": 623415,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-front.iff",
        "size": 1190,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-rear.cdf",
        "size": 626262,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_cheer-sml-rear.iff",
        "size": 1172,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_freethrow-front.cdf",
        "size": 263233,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_freethrow-front.iff",
        "size": 706,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_freethrow-rear.cdf",
        "size": 262143,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_freethrow-rear.iff",
        "size": 696,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-lrg.cdf",
        "size": 2139110,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-lrg.iff",
        "size": 2926,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-med.cdf",
        "size": 1374174,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-brk-med.iff",
        "size": 2248,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-lrg.cdf",
        "size": 1608835,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-lrg.iff",
        "size": 2474,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-med.cdf",
        "size": 1316681,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-cnc-med.iff",
        "size": 2248,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-fast.cdf",
        "size": 343257,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-fast.iff",
        "size": 850,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-hsc-lrg.cdf",
        "size": 377356,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-hsc-lrg.iff",
        "size": 892,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-lrg.cdf",
        "size": 1599149,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-lrg.iff",
        "size": 2096,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-med.cdf",
        "size": 1058129,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-med.iff",
        "size": 1886,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-shoot.cdf",
        "size": 667607,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-shoot.iff",
        "size": 1300,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_rmp-sml.cdf",
        "size": 1042708,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_rmp-sml.iff",
        "size": 1676,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_small-ahh-front.cdf",
        "size": 482610,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_small-ahh-front.iff",
        "size": 1190,
        "extension": ".iff"
      },
      {
        "name": "cwdressfx_draft_small-ahh-rear.cdf",
        "size": 463104,
        "extension": ".cdf"
      },
      {
        "name": "cwdressfx_draft_small-ahh-rear.iff",
        "size": 1172,
        "extension": ".iff"
      },
      {
        "name": "director2_draft.iff",
        "size": 23435,
        "extension": ".iff"
      },
      {
        "name": "draft_lines.bin",
        "size": 26472314,
        "extension": ".bin"
      },
      {
        "name": "draft_players.bin",
        "size": 28592874,
        "extension": ".bin"
      },
      {
        "name": "draft_ps.bin",
        "size": 12824650,
        "extension": ".bin"
      },
      {
        "name": "draft_ts.bin",
        "size": 6691156,
        "extension": ".bin"
      },
      {
        "name": "draftroom.iff",
        "size": 4142215,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions.iff",
        "size": 759814,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_english.iff",
        "size": 47637,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_french.iff",
        "size": 43844,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_german.iff",
        "size": 47185,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_italian.iff",
        "size": 42392,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_japanese.iff",
        "size": 37198,
        "extension": ".iff"
      },
      {
        "name": "predraft_conference_questions_spanish.iff",
        "size": 43099,
        "extension": ".iff"
      },
      {
        "name": "snapshot_background_2013draftclass.iff",
        "size": 491712,
        "extension": ".iff"
      },
      {
        "name": "snapshot_background_draft_lottery.iff",
        "size": 403311,
        "extension": ".iff"
      }
    ],
    "franchise": [
      {
        "name": "franchise.iff",
        "size": 1612117,
        "extension": ".iff"
      },
      {
        "name": "franchiseserver.iff",
        "size": 69954,
        "extension": ".iff"
      },
      {
        "name": "gooey_franchise.iff",
        "size": 467920,
        "extension": ".iff"
      }
    ],
    "presentation": [
      {
        "name": "2kbackendwipe.iff",
        "size": 2435609,
        "extension": ".iff"
      },
      {
        "name": "3ptcontestscorebug.iff",
        "size": 202153,
        "extension": ".iff"
      },
      {
        "name": "allstar_loading.iff",
        "size": 380673,
        "extension": ".iff"
      },
      {
        "name": "assdrillsloading.iff",
        "size": 215514,
        "extension": ".iff"
      },
      {
        "name": "cardgameloading.iff",
        "size": 654329,
        "extension": ".iff"
      },
      {
        "name": "careerdrillsloading.iff",
        "size": 423942,
        "extension": ".iff"
      },
      {
        "name": "defaultloadingscreen.iff",
        "size": 65800,
        "extension": ".iff"
      },
      {
        "name": "director2_loadinganimation.iff",
        "size": 37460,
        "extension": ".iff"
      },
      {
        "name": "drillsknockoutscorebug.iff",
        "size": 316939,
        "extension": ".iff"
      },
      {
        "name": "drillsscorebug.iff",
        "size": 131410,
        "extension": ".iff"
      },
      {
        "name": "drillsshootoutscorebug.iff",
        "size": 180134,
        "extension": ".iff"
      },
      {
        "name": "dunkcontestoverlay.iff",
        "size": 624073,
        "extension": ".iff"
      },
      {
        "name": "dunkcontestscorebug.iff",
        "size": 184551,
        "extension": ".iff"
      },
      {
        "name": "fastbreakscorebug1.iff",
        "size": 185171,
        "extension": ".iff"
      },
      {
        "name": "gooeyoverlaysstatic.iff",
        "size": 1458858,
        "extension": ".iff"
      },
      {
        "name": "halftimerookieshowcase.iff",
        "size": 246670,
        "extension": ".iff"
      },
      {
        "name": "halftimesponsorwatermark.iff",
        "size": 15022,
        "extension": ".iff"
      },
      {
        "name": "lebronmodeloading.iff",
        "size": 621419,
        "extension": ".iff"
      },
      {
        "name": "loading_audio.iff",
        "size": 150378,
        "extension": ".iff"
      },
      {
        "name": "loading_static.iff",
        "size": 721451,
        "extension": ".iff"
      },
      {
        "name": "loadingflow.iff",
        "size": 351383,
        "extension": ".iff"
      },
      {
        "name": "loadingsequence.bin",
        "size": 443974,
        "extension": ".bin"
      },
      {
        "name": "loadingsequencejz.bin",
        "size": 91222,
        "extension": ".bin"
      },
      {
        "name": "loadingsequencelebron.bin",
        "size": 92710,
        "extension": ".bin"
      },
      {
        "name": "loadingvo.bin",
        "size": 30337168,
        "extension": ".bin"
      },
      {
        "name": "loadingvo_ps.bin",
        "size": 12846028,
        "extension": ".bin"
      },
      {
        "name": "loadingvo_ts.bin",
        "size": 16011208,
        "extension": ".bin"
      },
      {
        "name": "myplayerloading.iff",
        "size": 1118908,
        "extension": ".iff"
      },
      {
        "name": "nbablacktoploading.iff",
        "size": 644434,
        "extension": ".iff"
      },
      {
        "name": "newscorebug.iff",
        "size": 304556,
        "extension": ".iff"
      },
      {
        "name": "onlinecrewloading.iff",
        "size": 286078,
        "extension": ".iff"
      },
      {
        "name": "onlinehalftimepanel.iff",
        "size": 342474,
        "extension": ".iff"
      },
      {
        "name": "onlinehalftimevs.iff",
        "size": 308947,
        "extension": ".iff"
      },
      {
        "name": "onlinepickuploading.iff",
        "size": 286632,
        "extension": ".iff"
      },
      {
        "name": "onlineteamuploading.iff",
        "size": 408420,
        "extension": ".iff"
      },
      {
        "name": "onlineversusloading.iff",
        "size": 375731,
        "extension": ".iff"
      },
      {
        "name": "overlay_extra.iff",
        "size": 215123,
        "extension": ".iff"
      },
      {
        "name": "overlay_gooey.iff",
        "size": 2916,
        "extension": ".iff"
      },
      {
        "name": "overlay_loaded.iff",
        "size": 477,
        "extension": ".iff"
      },
      {
        "name": "overlay_static.iff",
        "size": 42182,
        "extension": ".iff"
      },
      {
        "name": "playerwipe.iff",
        "size": 286376,
        "extension": ".iff"
      },
      {
        "name": "scorebugstreet.iff",
        "size": 120456,
        "extension": ".iff"
      },
      {
        "name": "singleplayerdrillsscorebug.iff",
        "size": 179564,
        "extension": ".iff"
      },
      {
        "name": "singleplayerdrillsscorebug2.iff",
        "size": 175336,
        "extension": ".iff"
      },
      {
        "name": "slaboverlay.iff",
        "size": 243421,
        "extension": ".iff"
      },
      {
        "name": "studioshow.iff",
        "size": 801920,
        "extension": ".iff"
      },
      {
        "name": "studioshowwipes.iff",
        "size": 222648,
        "extension": ".iff"
      },
      {
        "name": "teamwipe.iff",
        "size": 266352,
        "extension": ".iff"
      },
      {
        "name": "titlecardoverlay.iff",
        "size": 260495,
        "extension": ".iff"
      },
      {
        "name": "tombstoneoverlay.iff",
        "size": 233335,
        "extension": ".iff"
      },
      {
        "name": "trainingcamploading.iff",
        "size": 245337,
        "extension": ".iff"
      },
      {
        "name": "trainingcampscorebug.iff",
        "size": 133967,
        "extension": ".iff"
      },
      {
        "name": "wipeallstargeneric.iff",
        "size": 335858,
        "extension": ".iff"
      },
      {
        "name": "wipeallstarweekend.iff",
        "size": 539772,
        "extension": ".iff"
      },
      {
        "name": "wipedayofweek.iff",
        "size": 285383,
        "extension": ".iff"
      },
      {
        "name": "wipedirectorcut.iff",
        "size": 313650,
        "extension": ".iff"
      },
      {
        "name": "wipefinals.iff",
        "size": 621700,
        "extension": ".iff"
      },
      {
        "name": "wipenikeplus.iff",
        "size": 75211,
        "extension": ".iff"
      },
      {
        "name": "wipeonthemove.iff",
        "size": 289316,
        "extension": ".iff"
      },
      {
        "name": "wipeplayoffs.iff",
        "size": 468493,
        "extension": ".iff"
      },
      {
        "name": "wipereplayreview.iff",
        "size": 246360,
        "extension": ".iff"
      },
      {
        "name": "wipesprite.iff",
        "size": 114029,
        "extension": ".iff"
      },
      {
        "name": "wipespriteallstarweekend.iff",
        "size": 542545,
        "extension": ".iff"
      },
      {
        "name": "wipespritedunkcontest.iff",
        "size": 123699,
        "extension": ".iff"
      },
      {
        "name": "wipespriteuncontainable.iff",
        "size": 144592,
        "extension": ".iff"
      },
      {
        "name": "wipeteammatchup.iff",
        "size": 129573,
        "extension": ".iff"
      },
      {
        "name": "wipewarpdunk3pt.iff",
        "size": 172759,
        "extension": ".iff"
      }
    ],
    "schedule": [
      {
        "name": "lastseasonschedule.iff",
        "size": 16010,
        "extension": ".iff"
      },
      {
        "name": "upcomingschedule.iff",
        "size": 190854,
        "extension": ".iff"
      }
    ],
    "social": [
      {
        "name": "socialmedia_profilepics.iff",
        "size": 379300,
        "extension": ".iff"
      },
      {
        "name": "twitter_messages.iff",
        "size": 965743,
        "extension": ".iff"
      }
    ],
    "staff_team": [
      {
        "name": "team_000.iff",
        "size": 645485,
        "extension": ".iff"
      },
      {
        "name": "team_001.iff",
        "size": 656798,
        "extension": ".iff"
      },
      {
        "name": "team_002.iff",
        "size": 2335843,
        "extension": ".iff"
      },
      {
        "name": "team_003.iff",
        "size": 2840807,
        "extension": ".iff"
      },
      {
        "name": "team_004.iff",
        "size": 670131,
        "extension": ".iff"
      },
      {
        "name": "team_005.iff",
        "size": 656958,
        "extension": ".iff"
      },
      {
        "name": "team_006.iff",
        "size": 665049,
        "extension": ".iff"
      },
      {
        "name": "team_007.iff",
        "size": 624962,
        "extension": ".iff"
      },
      {
        "name": "team_008.iff",
        "size": 2763661,
        "extension": ".iff"
      },
      {
        "name": "team_009.iff",
        "size": 2928331,
        "extension": ".iff"
      },
      {
        "name": "team_010.iff",
        "size": 627700,
        "extension": ".iff"
      },
      {
        "name": "team_011.iff",
        "size": 628646,
        "extension": ".iff"
      },
      {
        "name": "team_012.iff",
        "size": 627481,
        "extension": ".iff"
      },
      {
        "name": "team_013.iff",
        "size": 3012681,
        "extension": ".iff"
      },
      {
        "name": "team_014.iff",
        "size": 636158,
        "extension": ".iff"
      },
      {
        "name": "team_015.iff",
        "size": 654292,
        "extension": ".iff"
      },
      {
        "name": "team_016.iff",
        "size": 662140,
        "extension": ".iff"
      },
      {
        "name": "team_017.iff",
        "size": 2813907,
        "extension": ".iff"
      },
      {
        "name": "team_018.iff",
        "size": 617282,
        "extension": ".iff"
      },
      {
        "name": "team_019.iff",
        "size": 2653113,
        "extension": ".iff"
      },
      {
        "name": "team_020.iff",
        "size": 2882974,
        "extension": ".iff"
      },
      {
        "name": "team_021.iff",
        "size": 666711,
        "extension": ".iff"
      },
      {
        "name": "team_022.iff",
        "size": 2877202,
        "extension": ".iff"
      },
      {
        "name": "team_023.iff",
        "size": 2887811,
        "extension": ".iff"
      },
      {
        "name": "team_024.iff",
        "size": 2839982,
        "extension": ".iff"
      },
      {
        "name": "team_025.iff",
        "size": 632226,
        "extension": ".iff"
      },
      {
        "name": "team_026.iff",
        "size": 2891023,
        "extension": ".iff"
      },
      {
        "name": "team_027.iff",
        "size": 2752860,
        "extension": ".iff"
      },
      {
        "name": "team_028.iff",
        "size": 2647106,
        "extension": ".iff"
      },
      {
        "name": "team_029.iff",
        "size": 633772,
        "extension": ".iff"
      },
      {
        "name": "team_030.iff",
        "size": 624630,
        "extension": ".iff"
      },
      {
        "name": "team_031.iff",
        "size": 2862472,
        "extension": ".iff"
      },
      {
        "name": "team_070.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_071.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_072.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_073.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_074.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_075.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_076.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_077.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_078.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_079.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_080.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_081.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_082.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_083.iff",
        "size": 626055,
        "extension": ".iff"
      },
      {
        "name": "team_100.iff",
        "size": 627632,
        "extension": ".iff"
      },
      {
        "name": "team_101.iff",
        "size": 627065,
        "extension": ".iff"
      },
      {
        "name": "team_102.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_103.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_104.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_105.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_106.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_108.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_109.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_110.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_111.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_112.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_113.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_114.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_115.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_116.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_117.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_118.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_119.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_120.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_121.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_122.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_123.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_124.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_125.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_126.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_127.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_128.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_129.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_131.iff",
        "size": 625204,
        "extension": ".iff"
      },
      {
        "name": "team_401.iff",
        "size": 2942986,
        "extension": ".iff"
      },
      {
        "name": "team_402.iff",
        "size": 592448,
        "extension": ".iff"
      },
      {
        "name": "team_403.iff",
        "size": 546727,
        "extension": ".iff"
      },
      {
        "name": "team_404.iff",
        "size": 600803,
        "extension": ".iff"
      },
      {
        "name": "team_405.iff",
        "size": 559436,
        "extension": ".iff"
      },
      {
        "name": "team_406.iff",
        "size": 575647,
        "extension": ".iff"
      },
      {
        "name": "team_407.iff",
        "size": 554722,
        "extension": ".iff"
      },
      {
        "name": "team_408.iff",
        "size": 2840676,
        "extension": ".iff"
      },
      {
        "name": "team_409.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_410.iff",
        "size": 615189,
        "extension": ".iff"
      },
      {
        "name": "team_411.iff",
        "size": 597098,
        "extension": ".iff"
      },
      {
        "name": "team_412.iff",
        "size": 2815304,
        "extension": ".iff"
      },
      {
        "name": "team_413.iff",
        "size": 2577282,
        "extension": ".iff"
      },
      {
        "name": "team_414.iff",
        "size": 592448,
        "extension": ".iff"
      },
      {
        "name": "team_415.iff",
        "size": 2787136,
        "extension": ".iff"
      },
      {
        "name": "team_416.iff",
        "size": 2740123,
        "extension": ".iff"
      },
      {
        "name": "team_417.iff",
        "size": 2781559,
        "extension": ".iff"
      },
      {
        "name": "team_418.iff",
        "size": 575647,
        "extension": ".iff"
      },
      {
        "name": "team_419.iff",
        "size": 2807037,
        "extension": ".iff"
      },
      {
        "name": "team_420.iff",
        "size": 559436,
        "extension": ".iff"
      },
      {
        "name": "team_421.iff",
        "size": 596342,
        "extension": ".iff"
      },
      {
        "name": "team_422.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_423.iff",
        "size": 570005,
        "extension": ".iff"
      },
      {
        "name": "team_424.iff",
        "size": 2809812,
        "extension": ".iff"
      },
      {
        "name": "team_425.iff",
        "size": 598113,
        "extension": ".iff"
      },
      {
        "name": "team_426.iff",
        "size": 654292,
        "extension": ".iff"
      },
      {
        "name": "team_427.iff",
        "size": 585155,
        "extension": ".iff"
      },
      {
        "name": "team_428.iff",
        "size": 2653113,
        "extension": ".iff"
      },
      {
        "name": "team_500.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_501.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_502.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_503.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_504.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_505.iff",
        "size": 560388,
        "extension": ".iff"
      },
      {
        "name": "team_506.iff",
        "size": 437457,
        "extension": ".iff"
      },
      {
        "name": "team_507.iff",
        "size": 445593,
        "extension": ".iff"
      },
      {
        "name": "team_508.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_509.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_510.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_511.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_515.iff",
        "size": 531696,
        "extension": ".iff"
      },
      {
        "name": "team_516.iff",
        "size": 667245,
        "extension": ".iff"
      },
      {
        "name": "team_517.iff",
        "size": 561768,
        "extension": ".iff"
      },
      {
        "name": "team_518.iff",
        "size": 659793,
        "extension": ".iff"
      },
      {
        "name": "team_519.iff",
        "size": 678290,
        "extension": ".iff"
      },
      {
        "name": "team_520.iff",
        "size": 560044,
        "extension": ".iff"
      },
      {
        "name": "team_521.iff",
        "size": 532927,
        "extension": ".iff"
      },
      {
        "name": "team_522.iff",
        "size": 668632,
        "extension": ".iff"
      },
      {
        "name": "team_523.iff",
        "size": 654926,
        "extension": ".iff"
      },
      {
        "name": "team_524.iff",
        "size": 675633,
        "extension": ".iff"
      },
      {
        "name": "team_525.iff",
        "size": 664119,
        "extension": ".iff"
      },
      {
        "name": "team_526.iff",
        "size": 648672,
        "extension": ".iff"
      },
      {
        "name": "team_527.iff",
        "size": 668507,
        "extension": ".iff"
      },
      {
        "name": "team_528.iff",
        "size": 683317,
        "extension": ".iff"
      },
      {
        "name": "team_529.iff",
        "size": 657465,
        "extension": ".iff"
      },
      {
        "name": "team_530.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_531.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_532.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_533.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_534.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_535.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_536.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_537.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_551.iff",
        "size": 2831823,
        "extension": ".iff"
      },
      {
        "name": "team_552.iff",
        "size": 645704,
        "extension": ".iff"
      },
      {
        "name": "team_553.iff",
        "size": 2667998,
        "extension": ".iff"
      },
      {
        "name": "team_555.iff",
        "size": 621968,
        "extension": ".iff"
      },
      {
        "name": "team_557.iff",
        "size": 622671,
        "extension": ".iff"
      },
      {
        "name": "team_560.iff",
        "size": 623861,
        "extension": ".iff"
      },
      {
        "name": "team_561.iff",
        "size": 2832063,
        "extension": ".iff"
      },
      {
        "name": "team_562.iff",
        "size": 622622,
        "extension": ".iff"
      },
      {
        "name": "team_563.iff",
        "size": 663764,
        "extension": ".iff"
      },
      {
        "name": "team_564.iff",
        "size": 667947,
        "extension": ".iff"
      },
      {
        "name": "team_565.iff",
        "size": 2832058,
        "extension": ".iff"
      },
      {
        "name": "team_566.iff",
        "size": 627906,
        "extension": ".iff"
      },
      {
        "name": "team_567.iff",
        "size": 2831489,
        "extension": ".iff"
      },
      {
        "name": "team_568.iff",
        "size": 2831457,
        "extension": ".iff"
      },
      {
        "name": "team_569.iff",
        "size": 656855,
        "extension": ".iff"
      },
      {
        "name": "team_570.iff",
        "size": 618286,
        "extension": ".iff"
      },
      {
        "name": "team_571.iff",
        "size": 651512,
        "extension": ".iff"
      },
      {
        "name": "team_572.iff",
        "size": 625566,
        "extension": ".iff"
      },
      {
        "name": "team_573.iff",
        "size": 625513,
        "extension": ".iff"
      },
      {
        "name": "team_574.iff",
        "size": 630483,
        "extension": ".iff"
      },
      {
        "name": "team_575.iff",
        "size": 638900,
        "extension": ".iff"
      },
      {
        "name": "team_576.iff",
        "size": 653874,
        "extension": ".iff"
      },
      {
        "name": "team_577.iff",
        "size": 649488,
        "extension": ".iff"
      },
      {
        "name": "team_578.iff",
        "size": 625552,
        "extension": ".iff"
      },
      {
        "name": "team_579.iff",
        "size": 645694,
        "extension": ".iff"
      },
      {
        "name": "team_580.iff",
        "size": 2831731,
        "extension": ".iff"
      },
      {
        "name": "team_582.iff",
        "size": 624074,
        "extension": ".iff"
      },
      {
        "name": "team_583.iff",
        "size": 621348,
        "extension": ".iff"
      },
      {
        "name": "team_584.iff",
        "size": 2581480,
        "extension": ".iff"
      },
      {
        "name": "team_585.iff",
        "size": 627350,
        "extension": ".iff"
      },
      {
        "name": "team_586.iff",
        "size": 636547,
        "extension": ".iff"
      },
      {
        "name": "team_588.iff",
        "size": 624128,
        "extension": ".iff"
      },
      {
        "name": "team_589.iff",
        "size": 640680,
        "extension": ".iff"
      },
      {
        "name": "team_590.iff",
        "size": 646345,
        "extension": ".iff"
      },
      {
        "name": "team_591.iff",
        "size": 625414,
        "extension": ".iff"
      },
      {
        "name": "team_592.iff",
        "size": 632373,
        "extension": ".iff"
      },
      {
        "name": "team_594.iff",
        "size": 622304,
        "extension": ".iff"
      },
      {
        "name": "team_595.iff",
        "size": 644318,
        "extension": ".iff"
      },
      {
        "name": "team_604.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_605.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_800.iff",
        "size": 628833,
        "extension": ".iff"
      },
      {
        "name": "team_801.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_802.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_803.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_804.iff",
        "size": 577843,
        "extension": ".iff"
      },
      {
        "name": "team_805.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_806.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_807.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_808.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_809.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_810.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_811.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_812.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_813.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_814.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_815.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_816.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_817.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_818.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_819.iff",
        "size": 577611,
        "extension": ".iff"
      },
      {
        "name": "team_820.iff",
        "size": 577611,
        "extension": ".iff"
      }
    ],
    "tutorial": [
      {
        "name": "tutorial_screenshots.iff",
        "size": 377208,
        "extension": ".iff"
      },
      {
        "name": "tutorialcontrollerdisplay.iff",
        "size": 935043,
        "extension": ".iff"
      },
      {
        "name": "tutorialmenulist.iff",
        "size": 199700,
        "extension": ".iff"
      }
    ]
  },
  "counts": {
    "career": 5,
    "coaches": 4,
    "draft": 66,
    "franchise": 3,
    "presentation": 67,
    "schedule": 2,
    "social": 2,
    "staff_team": 200,
    "tutorial": 3
  },
  "sampleUnmatched": [
    "3ptcontestlowerthird.iff",
    "3ptcontestmeter.iff",
    "3ptshootouttitlecard.iff",
    "ababall.iff",
    "accessoriesicons.iff",
    "admiral_dunk_1.iff",
    "aistreet.bin",
    "alb_cvr_cont_fcb780e2.iff",
    "allstarcontesttitlecard.iff",
    "amazing_commercial_music.iff",
    "ambient.iff",
    "and1celeb_12.iff",
    "and1celeb_15.iff",
    "and1celeb_16.iff",
    "and1celeb_2.iff",
    "and1celeb_4.iff",
    "and1celeb_5.iff",
    "and1celeb_6.iff",
    "and1celeb_7.iff",
    "and1celeb_9.iff",
    "animations_cheerleaders.cdf",
    "animations_cheerleaders.iff",
    "animations_dunkcontest.iff",
    "animations_horse_contest.iff",
    "animations_jumpball_multi.cdf",
    "animations_jumpball_multi.iff",
    "animations_legends_long_anims.cdf",
    "animations_legends_long_anims.iff",
    "animations_legends_streetstyle.iff",
    "animations_mascot_big.iff",
    "animations_mascot_small.iff",
    "animations_photo_op.iff",
    "animations_pregame_multi.cdf",
    "animations_pregame_multi.iff",
    "animations_pregame_preview.iff",
    "animations_pregame_single.cdf",
    "animations_pregame_single.iff",
    "animations_promo_crawl.cdf",
    "animations_promo_crawl.iff",
    "animations_streetstyle.iff",
    "animations_teaser_amb_int_ring_ceremony.iff",
    "animations_teaser_anm_2k11_amb_intro_garage_bus.iff",
    "animations_teaser_anm_2k11_amb_intro_garage_car.iff",
    "animations_teaser_anm_2k11_amb_intro_hallway_huddle.iff",
    "animations_teaser_anm_2k11_amb_intro_hallway_walk.iff",
    "animations_teaser_anm_2k11_amb_locker_intro_star_focus_v2.iff",
    "animaudio.iff",
    "animaudio000.bnk",
    "animaudio001.bnk",
    "animaudio002.bnk",
    "animaudio003.bnk",
    "animaudio004.bnk",
    "animaudio005.bnk",
    "animaudio006.bnk",
    "animaudio007.bnk",
    "animgraph_bodyup.iff",
    "animgraph_deny.iff",
    "animgraph_dribbler.iff",
    "aostreet.bin",
    "asstreet.bin",
    "audio_42004.cdf",
    "audio_42004.iff",
    "audio_42005.cdf",
    "audio_42005.iff",
    "audio_42010.cdf",
    "audio_42010.iff",
    "audio_42011.cdf",
    "audio_42011.iff",
    "audio_42012.cdf",
    "audio_42012.iff",
    "audio_42013.cdf",
    "audio_42013.iff",
    "audio_42014.cdf",
    "audio_42014.iff",
    "audio_42015.cdf",
    "audio_42015.iff",
    "audio_42016.cdf",
    "audio_42016.iff",
    "audio_42017.cdf",
    "audio_42017.iff",
    "audio_42018.cdf",
    "audio_42018.iff",
    "audio_42019.cdf",
    "audio_42019.iff",
    "audio_42021.cdf",
    "audio_42021.iff",
    "audio_42022.cdf",
    "audio_42022.iff",
    "audio_42024.cdf",
    "audio_42024.iff",
    "audio_42025.cdf",
    "audio_42025.iff",
    "audio_42026.cdf",
    "audio_42026.iff",
    "audio_42027.cdf",
    "audio_42027.iff",
    "audio_42028.cdf",
    "audio_42028.iff",
    "audio_42029.cdf",
    "audio_42029.iff"
  ]
} as const;
