// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKCoachSchema = {
  "source": "RED MC NBA2K14 staff + coach stat captions",
  "identity": [
    {
      "code": "Last_Name",
      "label": "Last Name",
      "description": "This field indicates staff member's Last Name"
    },
    {
      "code": "First_Name",
      "label": "First Name",
      "description": "This field indicates staff member's First Name"
    },
    {
      "code": "SType",
      "label": "Staff Type",
      "description": "Stands for the type of the staff member"
    },
    {
      "code": "Experience",
      "label": "Experience",
      "description": "How many years the coach has been in the NBA."
    },
    {
      "code": "PortrID",
      "label": "Portrait ID",
      "description": "Staff member�s portrait is defined by this ID value"
    },
    {
      "code": "CF_ID",
      "label": "CyberFace ID",
      "description": "Staff member�s in-match face is defined by this ID value"
    },
    {
      "code": "Height",
      "label": "Height",
      "description": "Represents staff member�s height"
    },
    {
      "code": "AudioID",
      "label": "Audio ID",
      "description": "Audio stories, told by commentators about the staff member during matches"
    }
  ],
  "contract": [
    {
      "code": "CStatus",
      "label": "Status",
      "description": "Contract Status"
    },
    {
      "code": "CTeamGID",
      "label": "Team (GID)",
      "description": "Defines the team, responsible for the staff member's contract, by its GID. Set to -1, so no team will be responsible for his contract anymore"
    },
    {
      "code": "CYears",
      "label": "Years",
      "description": "Number of staff member�s contract years"
    },
    {
      "code": "CSalary",
      "label": "Salary",
      "description": "Salary"
    },
    {
      "code": "PlaybookID",
      "label": "Playbook ID",
      "description": "ID of the default Playbook, used by the coach"
    }
  ],
  "ratings": [
    {
      "code": "SOffense",
      "label": "Offense",
      "description": "Offensive Skill (used by coaches)"
    },
    {
      "code": "SDefense",
      "label": "Defense",
      "description": "Defensive Skill (used by coaches)"
    },
    {
      "code": "STeacher",
      "label": "Teacher",
      "description": "Teaching Skill (used by coaches)"
    },
    {
      "code": "SSct_Trn",
      "label": "Scout / Trainer",
      "description": "Scouting skill for scouts and Medical skill for Trainers"
    },
    {
      "code": "SPotential",
      "label": "Potential",
      "description": "Potential of the staff member"
    }
  ],
  "playstyle": [
    {
      "code": "POffTempo",
      "label": "Offensive Tempo",
      "description": "How quickly the team will move the ball around"
    },
    {
      "code": "POnBlDefP",
      "label": "On-Ball Defensive Pressure",
      "description": "Sets how quickly the team will move on the defensive side of the ball"
    },
    {
      "code": "POfBlDefP",
      "label": "Off-Ball Defensive Pressure",
      "description": "Sets how quickly the team will move on the defensive side of the ball"
    },
    {
      "code": "PHelpDef",
      "label": "Help Defense",
      "description": "Sets how often players will help out others on defense"
    },
    {
      "code": "PFastBrk",
      "label": "Fast Break",
      "description": "Sets how quickly the team will carry the ball up the court"
    },
    {
      "code": "PCrashGls",
      "label": "Crash Offensive Glass",
      "description": "Sets how aggressively the team will rebound"
    },
    {
      "code": "PRunPlays",
      "label": "Run Plays",
      "description": "Sets how often the team will run set plays"
    },
    {
      "code": "PErlyOff",
      "label": "Early Offense",
      "description": "Sets how often the team will run early offense plays"
    },
    {
      "code": "PDblTeams",
      "label": "Double Teams",
      "description": "Sets how often the team will employ double teams on defense"
    },
    {
      "code": "PZoneUsg",
      "label": "Zone Usage",
      "description": "Sets how often the team will use a zone defense"
    },
    {
      "code": "PBnchDpth",
      "label": "Bench Depth",
      "description": "Sets how many minutes the bench will play in an average game"
    },
    {
      "code": "PLnUpPerf",
      "label": "LineUp Perfomance Factor",
      "description": "Sets how much perfomance affects minutes played in a game"
    },
    {
      "code": "PTkInsSht",
      "label": "Take Inside Shots",
      "description": "Sets how often the team will take shots under the hoop"
    },
    {
      "code": "PTkClsSht",
      "label": "Take Close Shots",
      "description": "Sets how often the team will take shots near the hoop"
    },
    {
      "code": "PTkMidSht",
      "label": "Take Mid-Range Shots",
      "description": "Sets how often the team will take shots mid-range"
    },
    {
      "code": "PTk3PTSht",
      "label": "Take 3PT Shots",
      "description": "Sets how often the team will take shots from beyond the 3-Point line"
    },
    {
      "code": "PAttBskt",
      "label": "Attack The Basket",
      "description": "Sets how often the team will drive to the hoop"
    },
    {
      "code": "PLkPostPl",
      "label": "Look For Post Players",
      "description": "Sets how often the team will pass the ball to players under the basket"
    },
    {
      "code": "PThrwAOs",
      "label": "Throw Alley-Oops",
      "description": "Sets how often the team will pass to the hoop for a player to dunk"
    },
    {
      "code": "PSizeSpd",
      "label": "Size - Speed",
      "description": "Determines which types of players will be favored"
    },
    {
      "code": "PAthlSkill",
      "label": "Athleticism vs. Skill",
      "description": "Profile - Athleticism vs. Skill"
    },
    {
      "code": "POffDef",
      "label": "Offense vs. Defense",
      "description": "Profile - Offense vs. Defense"
    },
    {
      "code": "PGrdsFrwds",
      "label": "Guards vs. Forwards",
      "description": "Profile - Guards vs. Forwards"
    },
    {
      "code": "PInsOuts",
      "label": "Inside vs. Outside",
      "description": "Profile - Inside vs. Outside"
    }
  ],
  "simControl": [
    {
      "code": "TOShotSel",
      "label": "Shot Selection",
      "description": "Total Sim Control - Offense - Shot Selection"
    },
    {
      "code": "TOFocus",
      "label": "Offensive Focus",
      "description": "Total Sim Control - Offense - Offensive Focus"
    },
    {
      "code": "TORebound",
      "label": "Offensive Rebounding",
      "description": "Total Sim Control - Offense - Offensive Rebounding"
    },
    {
      "code": "TDPressure",
      "label": "Defensive Pressure",
      "description": "Total Sim Control - Defense - Defensive Pressure"
    },
    {
      "code": "TDStyle",
      "label": "Defensive Style",
      "description": "Total Sim Control - Defense - Defensive Style"
    },
    {
      "code": "TDRebound",
      "label": "Defensive Rebounding",
      "description": "Total Sim Control - Defense - Defensive Rebounding"
    }
  ],
  "other": [],
  "seasonHistory": [
    {
      "code": "RegSWins",
      "label": "Regular Season Wins",
      "description": ""
    },
    {
      "code": "RegSLosses",
      "label": "Regular Season Losses",
      "description": ""
    },
    {
      "code": "POWins",
      "label": "PlayOff Wins",
      "description": ""
    },
    {
      "code": "POLosses",
      "label": "PlayOff Losses",
      "description": ""
    },
    {
      "code": "WonPOs",
      "label": "Won PlayOffs",
      "description": "Determines, if the coach won the PlayOffs that year"
    },
    {
      "code": "IsCoachOfYr",
      "label": "Is Coach Of The Year",
      "description": "Determines, if the coach was selected as the Coach Of The Year that season"
    }
  ],
  "hiddenCoachAudio": [
    {
      "raw": "Hidden Coach Audio",
      "parts": [
        "Hidden Coach Audio"
      ]
    },
    {
      "raw": "100-O'Brien\tJim",
      "parts": [
        "100-O'Brien",
        "Jim"
      ]
    },
    {
      "raw": "103- Skiles\tScott",
      "parts": [
        "103- Skiles",
        "Scott"
      ]
    },
    {
      "raw": "106-Dunleavy\tMike",
      "parts": [
        "106-Dunleavy",
        "Mike"
      ]
    },
    {
      "raw": "109-Van Gundy\tStan",
      "parts": [
        "109-Van Gundy",
        "Stan"
      ]
    },
    {
      "raw": "111-Sloan\tJerry",
      "parts": [
        "111-Sloan",
        "Jerry"
      ]
    },
    {
      "raw": "136-Jackson\tPhil",
      "parts": [
        "136-Jackson",
        "Phil"
      ]
    },
    {
      "raw": "160 - Jones\tRob",
      "parts": [
        "160 - Jones",
        "Rob"
      ]
    },
    {
      "raw": "179-Triano\tJay",
      "parts": [
        "179-Triano",
        "Jay"
      ]
    },
    {
      "raw": "183-Westphal\tPaul",
      "parts": [
        "183-Westphal",
        "Paul"
      ]
    },
    {
      "raw": "211-Jinks\tLynell",
      "parts": [
        "211-Jinks",
        "Lynell"
      ]
    },
    {
      "raw": "316-Silas\tPaul",
      "parts": [
        "316-Silas",
        "Paul"
      ]
    },
    {
      "raw": "321-Vogel\tFrank",
      "parts": [
        "321-Vogel",
        "Frank"
      ]
    },
    {
      "raw": "516-Casey\tDwane",
      "parts": [
        "516-Casey",
        "Dwane"
      ]
    },
    {
      "raw": "565-kurt Rambis",
      "parts": [
        "565-kurt Rambis"
      ]
    }
  ],
  "notes": [
    "This is translated schema metadata, not parsed coach rows from coaches.bin or FXG.",
    "The playstyle and sim-control fields line up well with nba-commish coach tendency systems."
  ]
} as const;
