// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKImportIndex = {
  "generatedAtUtc": "2026-04-23T15:46:22.291226+00:00",
  "projectRoot": "C:\\Users\\user-MSI\\Downloads\\nba-commish",
  "sources": {
    "gameRoot": "C:\\Program Files (x86)\\2K Sports\\NBA 2K14",
    "redMcRoot": "C:\\Editing Tools\\RED MC"
  },
  "copiedRawFiles": [
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\Enums.txt",
      "relativePath": "Text/Enums.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/Enums.txt",
      "size": 91392
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\IFF\\Contents.txt",
      "relativePath": "Text/IFF/Contents.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/IFF/Contents.txt",
      "size": 213
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\GridNames.txt",
      "relativePath": "Text/NBA2K14/GridNames.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/GridNames.txt",
      "size": 531
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Tutorials\\NBA 2K14\\List Of Text Values.txt",
      "relativePath": "Tutorials/NBA 2K14/List Of Text Values.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Tutorials/NBA 2K14/List Of Text Values.txt",
      "size": 3856654
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Tutorials\\NBA 2K14\\XBox 360 Disc Contents (by Rondo is GOD)\\HIDDEN ARENA IDs.txt",
      "relativePath": "Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/HIDDEN ARENA IDs.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/HIDDEN ARENA IDs.txt",
      "size": 229
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Tutorials\\NBA 2K14\\XBox 360 Disc Contents (by Rondo is GOD)\\Hidden Coach Audio.txt",
      "relativePath": "Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/Hidden Coach Audio.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/Hidden Coach Audio.txt",
      "size": 271
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Tutorials\\NBA 2K14\\XBox 360 Disc Contents (by Rondo is GOD)\\HIDDEN LOGOS.txt",
      "relativePath": "Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/HIDDEN LOGOS.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Tutorials/NBA 2K14/XBox 360 Disc Contents (by Rondo is GOD)/HIDDEN LOGOS.txt",
      "size": 3709
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Arena.txt",
      "relativePath": "Text/NBA2K14/Captions/Arena.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Arena.txt",
      "size": 2314
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Award.txt",
      "relativePath": "Text/NBA2K14/Captions/Award.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Award.txt",
      "size": 1404
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\CoachStat.txt",
      "relativePath": "Text/NBA2K14/Captions/CoachStat.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/CoachStat.txt",
      "size": 313
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\College.txt",
      "relativePath": "Text/NBA2K14/Captions/College.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/College.txt",
      "size": 1453
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\CustomName.txt",
      "relativePath": "Text/NBA2K14/Captions/CustomName.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/CustomName.txt",
      "size": 20
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\DraftData.txt",
      "relativePath": "Text/NBA2K14/Captions/DraftData.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/DraftData.txt",
      "size": 49
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Draftees.txt",
      "relativePath": "Text/NBA2K14/Captions/Draftees.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Draftees.txt",
      "size": 31367
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\FreeAgentsList.txt",
      "relativePath": "Text/NBA2K14/Captions/FreeAgentsList.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/FreeAgentsList.txt",
      "size": 33693
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\GameRecord.txt",
      "relativePath": "Text/NBA2K14/Captions/GameRecord.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/GameRecord.txt",
      "size": 293
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\HallOfFamer.txt",
      "relativePath": "Text/NBA2K14/Captions/HallOfFamer.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/HallOfFamer.txt",
      "size": 1990
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Headshape.txt",
      "relativePath": "Text/NBA2K14/Captions/Headshape.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Headshape.txt",
      "size": 2552
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Jersey.txt",
      "relativePath": "Text/NBA2K14/Captions/Jersey.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Jersey.txt",
      "size": 2500
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Matchup.txt",
      "relativePath": "Text/NBA2K14/Captions/Matchup.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Matchup.txt",
      "size": 180
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\NameData.txt",
      "relativePath": "Text/NBA2K14/Captions/NameData.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/NameData.txt",
      "size": 321
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\OnlineTeamup.txt",
      "relativePath": "Text/NBA2K14/Captions/OnlineTeamup.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/OnlineTeamup.txt",
      "size": 47
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Playbook.txt",
      "relativePath": "Text/NBA2K14/Captions/Playbook.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Playbook.txt",
      "size": 1322
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Player.txt",
      "relativePath": "Text/NBA2K14/Captions/Player.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Player.txt",
      "size": 28763
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\PlayerRating.txt",
      "relativePath": "Text/NBA2K14/Captions/PlayerRating.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/PlayerRating.txt",
      "size": 640
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\PlayerStat.txt",
      "relativePath": "Text/NBA2K14/Captions/PlayerStat.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/PlayerStat.txt",
      "size": 3332
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Rotation.txt",
      "relativePath": "Text/NBA2K14/Captions/Rotation.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Rotation.txt",
      "size": 316
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Schedule.txt",
      "relativePath": "Text/NBA2K14/Captions/Schedule.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Schedule.txt",
      "size": 624
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\SkillsBoost.txt",
      "relativePath": "Text/NBA2K14/Captions/SkillsBoost.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/SkillsBoost.txt",
      "size": 3105
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Staff.txt",
      "relativePath": "Text/NBA2K14/Captions/Staff.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Staff.txt",
      "size": 3839
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Struct44.txt",
      "relativePath": "Text/NBA2K14/Captions/Struct44.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Struct44.txt",
      "size": 4
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Struct735767AE.txt",
      "relativePath": "Text/NBA2K14/Captions/Struct735767AE.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Struct735767AE.txt",
      "size": 32
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Team.txt",
      "relativePath": "Text/NBA2K14/Captions/Team.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Team.txt",
      "size": 11306
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\TeamStat.txt",
      "relativePath": "Text/NBA2K14/Captions/TeamStat.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/TeamStat.txt",
      "size": 1808
    },
    {
      "label": "red_mc",
      "sourcePath": "C:\\Editing Tools\\RED MC\\Text\\NBA2K14\\Captions\\Transaction.txt",
      "relativePath": "Text/NBA2K14/Captions/Transaction.txt",
      "copiedTo": "src/data/2kImport/raw/red_mc/Text/NBA2K14/Captions/Transaction.txt",
      "size": 6772
    }
  ],
  "generatedModules": [
    "assetManifest.ts",
    "captions.ts",
    "coachSchema.ts",
    "coachesBinaryAnalysis.ts",
    "fxgBinaryAnalysis.ts",
    "tables.ts",
    "textTemplateSources.ts",
    "transactionSchema.ts",
    "index.ts"
  ]
} as const;
