// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKTextTemplateHiddenArenaIds = [
    {
      "raw": "032\t\t\t2012(?) All-Star Court",
      "parts": [
        "032",
        "2012(?) All-Star Court"
      ]
    },
    {
      "raw": "033\t\t\t2013 Houstin All-Star Court",
      "parts": [
        "033",
        "2013 Houstin All-Star Court"
      ]
    },
    {
      "raw": "550\t\t\tJordan Brand Arena (No Arena, just floor)",
      "parts": [
        "550",
        "Jordan Brand Arena (No Arena, just floor)"
      ]
    },
    {
      "raw": "611\t\t\tRucker Park (Model3D voids floor ID)",
      "parts": [
        "611",
        "Rucker Park (Model3D voids floor ID)"
      ]
    },
    {
      "raw": "733\t\t\tNBA 2K Arena (No arena, just floor)",
      "parts": [
        "733",
        "NBA 2K Arena (No arena, just floor)"
      ]
    },
    {
      "raw": "735\t\t\tSummer Circuit Arena",
      "parts": [
        "735",
        "Summer Circuit Arena"
      ]
    }
] as const;
