// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKTextTemplateHiddenLogosA = [
    {
      "raw": "logo300\t\t\t\t50s-60s Legends",
      "parts": [
        "logo300",
        "50s-60s Legends"
      ]
    },
    {
      "raw": "logo301\t\t\t\t70s-East Legends",
      "parts": [
        "logo301",
        "70s-East Legends"
      ]
    },
    {
      "raw": "logo302\t\t\t\t70s-West Legends",
      "parts": [
        "logo302",
        "70s-West Legends"
      ]
    },
    {
      "raw": "logo303\t\t\t\t80s-East Legends",
      "parts": [
        "logo303",
        "80s-East Legends"
      ]
    },
    {
      "raw": "logo304\t\t\t\t80s-West Legends",
      "parts": [
        "logo304",
        "80s-West Legends"
      ]
    },
    {
      "raw": "logo305\t\t\t\t90s-East Legends",
      "parts": [
        "logo305",
        "90s-East Legends"
      ]
    },
    {
      "raw": "logo306\t\t\t\t90s-West Legends",
      "parts": [
        "logo306",
        "90s-West Legends"
      ]
    },
    {
      "raw": "logo500\t\t\t\tNBA 2K13 Logo",
      "parts": [
        "logo500",
        "NBA 2K13 Logo"
      ]
    },
    {
      "raw": "logo501\t\t\t\t2K Sports Logo",
      "parts": [
        "logo501",
        "2K Sports Logo"
      ]
    },
    {
      "raw": "logo502\t\t\t\tVisual Concepts",
      "parts": [
        "logo502",
        "Visual Concepts"
      ]
    },
    {
      "raw": "logo503\t\t\t\tInternational All-Stars",
      "parts": [
        "logo503",
        "International All-Stars"
      ]
    },
    {
      "raw": "logo504\t\t\t\tRookies",
      "parts": [
        "logo504",
        "Rookies"
      ]
    },
    {
      "raw": "logo505\t\t\t\tSophomore",
      "parts": [
        "logo505",
        "Sophomore"
      ]
    },
    {
      "raw": "logo506\t\t\t\tSuperstars",
      "parts": [
        "logo506",
        "Superstars"
      ]
    },
    {
      "raw": "logo509\t\t\t\tOld Knicks Logo",
      "parts": [
        "logo509",
        "Old Knicks Logo"
      ]
    },
    {
      "raw": "logo510\t\t\t\tRetro 76ers Logo",
      "parts": [
        "logo510",
        "Retro 76ers Logo"
      ]
    },
    {
      "raw": "logo511\t\t\t\tSupersonics Logo (S)",
      "parts": [
        "logo511",
        "Supersonics Logo (S)"
      ]
    },
    {
      "raw": "logo512\t\t\t\t2K China Logo",
      "parts": [
        "logo512",
        "2K China Logo"
      ]
    },
    {
      "raw": "logo513\t\t\t\t2K Sphere Logo",
      "parts": [
        "logo513",
        "2K Sphere Logo"
      ]
    },
    {
      "raw": "logo515\t\t\t\tCelebrity Team Logo",
      "parts": [
        "logo515",
        "Celebrity Team Logo"
      ]
    },
    {
      "raw": "logo516\t\t\t\tDream Team Logo",
      "parts": [
        "logo516",
        "Dream Team Logo"
      ]
    },
    {
      "raw": "logo517\t\t\t\tTeam USA Logo",
      "parts": [
        "logo517",
        "Team USA Logo"
      ]
    },
    {
      "raw": "logo520\t\t\t\t2000 Draft Class Logo",
      "parts": [
        "logo520",
        "2000 Draft Class Logo"
      ]
    },
    {
      "raw": "logo521\t\t\t\t2001 Draft Class Logo",
      "parts": [
        "logo521",
        "2001 Draft Class Logo"
      ]
    },
    {
      "raw": "logo522\t\t\t\t2002 Draft Class Logo",
      "parts": [
        "logo522",
        "2002 Draft Class Logo"
      ]
    },
    {
      "raw": "logo523\t\t\t\t2003 Draft Class Logo",
      "parts": [
        "logo523",
        "2003 Draft Class Logo"
      ]
    },
    {
      "raw": "logo524\t\t\t\t2004 Draft Class Logo",
      "parts": [
        "logo524",
        "2004 Draft Class Logo"
      ]
    },
    {
      "raw": "logo525\t\t\t\t2005 Draft Class Logo",
      "parts": [
        "logo525",
        "2005 Draft Class Logo"
      ]
    },
    {
      "raw": "logo526\t\t\t\t2006 Draft Class Logo",
      "parts": [
        "logo526",
        "2006 Draft Class Logo"
      ]
    },
    {
      "raw": "logo527\t\t\t\t2007 Draft Class Logo",
      "parts": [
        "logo527",
        "2007 Draft Class Logo"
      ]
    },
    {
      "raw": "logo550\t\t\t\tJordan- Jumpman Logo",
      "parts": [
        "logo550",
        "Jordan- Jumpman Logo"
      ]
    },
    {
      "raw": "logo600\t\t\t\tHome Logo",
      "parts": [
        "logo600",
        "Home Logo"
      ]
    },
    {
      "raw": "logo601\t\t\t\tAway Logo",
      "parts": [
        "logo601",
        "Away Logo"
      ]
    },
    {
      "raw": "logo602\t\t\t\tRookie Showcase Logo",
      "parts": [
        "logo602",
        "Rookie Showcase Logo"
      ]
    },
    {
      "raw": "logo603\t\t\t\tNBA '09 Logo (White BG)",
      "parts": [
        "logo603",
        "NBA '09 Logo (White BG)"
      ]
    },
    {
      "raw": "logo604\t\t\t\tThe Elites Logo",
      "parts": [
        "logo604",
        "The Elites Logo"
      ]
    },
    {
      "raw": "logo605\t\t\t\tRookie Stars Logo",
      "parts": [
        "logo605",
        "Rookie Stars Logo"
      ]
    },
    {
      "raw": "logo610\t\t\t\tAll Net Logo",
      "parts": [
        "logo610",
        "All Net Logo"
      ]
    },
    {
      "raw": "logo611\t\t\t\tAnkle Breakers Logo",
      "parts": [
        "logo611",
        "Ankle Breakers Logo"
      ]
    },
    {
      "raw": "logo612\t\t\t\tBuckets Logo",
      "parts": [
        "logo612",
        "Buckets Logo"
      ]
    },
    {
      "raw": "logo613\t\t\t\tClutch Boyz Logo",
      "parts": [
        "logo613",
        "Clutch Boyz Logo"
      ]
    },
    {
      "raw": "logo614\t\t\t\tDroppin' Dimes Logo",
      "parts": [
        "logo614",
        "Droppin' Dimes Logo"
      ]
    },
    {
      "raw": "logo615\t\t\t\tLights Out Logo",
      "parts": [
        "logo615",
        "Lights Out Logo"
      ]
    },
    {
      "raw": "logo616\t\t\t\tMad Handles Logo",
      "parts": [
        "logo616",
        "Mad Handles Logo"
      ]
    },
    {
      "raw": "logo617\t\t\t\tBoats Show Logo",
      "parts": [
        "logo617",
        "Boats Show Logo"
      ]
    },
    {
      "raw": "logo618\t\t\t\tThe Ringers Logo",
      "parts": [
        "logo618",
        "The Ringers Logo"
      ]
    },
    {
      "raw": "logo619\t\t\t\tThe Ballerz Logo",
      "parts": [
        "logo619",
        "The Ballerz Logo"
      ]
    },
    {
      "raw": "logo800\t\t\t\tCAT Power Plant (?) Logo",
      "parts": [
        "logo800",
        "CAT Power Plant (?) Logo"
      ]
    },
    {
      "raw": "logo801\t\t\t\tCAT Train Logo",
      "parts": [
        "logo801",
        "CAT Train Logo"
      ]
    },
    {
      "raw": "logo802\t\t\t\tCAT Lightning Logo",
      "parts": [
        "logo802",
        "CAT Lightning Logo"
      ]
    },
    {
      "raw": "logo803\t\t\t\tCAT Snake Logo",
      "parts": [
        "logo803",
        "CAT Snake Logo"
      ]
    },
    {
      "raw": "logo804\t\t\t\tCAT Erasers Logo",
      "parts": [
        "logo804",
        "CAT Erasers Logo"
      ]
    },
    {
      "raw": "logo805\t\t\t\tCAT Hawks Logo",
      "parts": [
        "logo805",
        "CAT Hawks Logo"
      ]
    },
    {
      "raw": "logo806\t\t\t\tCAT Galaxy Logo",
      "parts": [
        "logo806",
        "CAT Galaxy Logo"
      ]
    },
    {
      "raw": "logo807\t\t\t\t\tCAT ....I don't even know Logo",
      "parts": [
        "logo807",
        "CAT ....I don't even know Logo"
      ]
    },
    {
      "raw": "logo808\t\t\t\tCAT Panther Logo",
      "parts": [
        "logo808",
        "CAT Panther Logo"
      ]
    },
    {
      "raw": "logo809\t\t\t\tCAT Mirage Logo",
      "parts": [
        "logo809",
        "CAT Mirage Logo"
      ]
    },
    {
      "raw": "logo810\t\t\t\t\tCAT A-Hoop Logo",
      "parts": [
        "logo810",
        "CAT A-Hoop Logo"
      ]
    },
    {
      "raw": "logo811\t\t\t\tRhythm Logo",
      "parts": [
        "logo811",
        "Rhythm Logo"
      ]
    },
    {
      "raw": "logo998\t\t\t\tNBA Logo",
      "parts": [
        "logo998",
        "NBA Logo"
      ]
    },
    {
      "raw": "logo999\t\t\t\tFree Agent Logo",
      "parts": [
        "logo999",
        "Free Agent Logo"
      ]
    },
    {
      "raw": "logo_2k_square\t\t\tHQ 2K Logo",
      "parts": [
        "logo_2k_square",
        "HQ 2K Logo"
      ]
    },
    {
      "raw": "logo_adidas_square\t\tAdidas Logo",
      "parts": [
        "logo_adidas_square",
        "Adidas Logo"
      ]
    },
    {
      "raw": "logo_all_star\t\t\tAll Star New Orleans Logo",
      "parts": [
        "logo_all_star",
        "All Star New Orleans Logo"
      ]
    },
    {
      "raw": "logo_all_star_generic\t\tAll Star Generic",
      "parts": [
        "logo_all_star_generic",
        "All Star Generic"
      ]
    }
] as const;
