// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKTextTemplateHiddenLogosB = [
    {
      "raw": "logo_all_star_wm\t\tAll Star (Jersey Logo?)",
      "parts": [
        "logo_all_star_wm",
        "All Star (Jersey Logo?)"
      ]
    },
    {
      "raw": "logo_bbva\t\t\tOffical Bank of NBA Logo",
      "parts": [
        "logo_bbva",
        "Offical Bank of NBA Logo"
      ]
    },
    {
      "raw": "logo_converse_square\t\tConverse Logo",
      "parts": [
        "logo_converse_square",
        "Converse Logo"
      ]
    },
    {
      "raw": "logo_footlocker\t\t\tFootlocker Ref Logo",
      "parts": [
        "logo_footlocker",
        "Footlocker Ref Logo"
      ]
    },
    {
      "raw": "logo_gatorade\t\t\tGatorade G w/ Lightning Bolt",
      "parts": [
        "logo_gatorade",
        "Gatorade G w/ Lightning Bolt"
      ]
    },
    {
      "raw": "logo_jordan\t\t\tHQ Jumpman",
      "parts": [
        "logo_jordan",
        "HQ Jumpman"
      ]
    },
    {
      "raw": "logo_jordan_square\t\tHQ Jumpman w/ Jordan Text",
      "parts": [
        "logo_jordan_square",
        "HQ Jumpman w/ Jordan Text"
      ]
    },
    {
      "raw": "logo_nba_finals\t\t\tThe Finals text",
      "parts": [
        "logo_nba_finals",
        "The Finals text"
      ]
    },
    {
      "raw": "logo_nba_finals_white\t\tThe Finals text white",
      "parts": [
        "logo_nba_finals_white",
        "The Finals text white"
      ]
    },
    {
      "raw": "logo_nba_playoffs\t\tPlayoffs court logo",
      "parts": [
        "logo_nba_playoffs",
        "Playoffs court logo"
      ]
    },
    {
      "raw": "logo_nba_playoffs_white\t\tPlayoffs court logo white",
      "parts": [
        "logo_nba_playoffs_white",
        "Playoffs court logo white"
      ]
    },
    {
      "raw": "logo_nbdl\t\t\tD League Logo",
      "parts": [
        "logo_nbdl",
        "D League Logo"
      ]
    },
    {
      "raw": "logo_nike\t\t\tNike text w/ Swoosh Logo",
      "parts": [
        "logo_nike",
        "Nike text w/ Swoosh Logo"
      ]
    },
    {
      "raw": "logo_nike_swoosh_square\t\tNike Swoosh",
      "parts": [
        "logo_nike_swoosh_square",
        "Nike Swoosh"
      ]
    },
    {
      "raw": "logo_reebok_square\t\tReebok text",
      "parts": [
        "logo_reebok_square",
        "Reebok text"
      ]
    },
    {
      "raw": "logo_spalding_square\t\tSpalding True to the Game",
      "parts": [
        "logo_spalding_square",
        "Spalding True to the Game"
      ]
    },
    {
      "raw": "logo_sprite\t\t\tSprite Logo",
      "parts": [
        "logo_sprite",
        "Sprite Logo"
      ]
    },
    {
      "raw": "logo_statefarm\t\t\tState Farm Text",
      "parts": [
        "logo_statefarm",
        "State Farm Text"
      ]
    },
    {
      "raw": "logo_under_armour_square\tUA Logo",
      "parts": [
        "logo_under_armour_square",
        "UA Logo"
      ]
    },
    {
      "raw": "Text Based Logos",
      "parts": [
        "Text Based Logos"
      ]
    },
    {
      "raw": "logo000_wm\t\t\tSixers Text Logo",
      "parts": [
        "logo000_wm",
        "Sixers Text Logo"
      ]
    },
    {
      "raw": "logo001_wm\t\t\tBucks Text Logo",
      "parts": [
        "logo001_wm",
        "Bucks Text Logo"
      ]
    },
    {
      "raw": "logo002_wm\t\t\tWizards Text Logo",
      "parts": [
        "logo002_wm",
        "Wizards Text Logo"
      ]
    },
    {
      "raw": "logo003_wm\t\t\tBulls Text Logo",
      "parts": [
        "logo003_wm",
        "Bulls Text Logo"
      ]
    },
    {
      "raw": "logo004_wm\t\t\tOld Cavs Text Logo",
      "parts": [
        "logo004_wm",
        "Old Cavs Text Logo"
      ]
    },
    {
      "raw": "logo005_wm\t\t\tCeltics Text Logo",
      "parts": [
        "logo005_wm",
        "Celtics Text Logo"
      ]
    },
    {
      "raw": "logo006_wm\t\t\tClippers Text Logo",
      "parts": [
        "logo006_wm",
        "Clippers Text Logo"
      ]
    },
    {
      "raw": "logo007_wm\t\t\tEastern Text Logo",
      "parts": [
        "logo007_wm",
        "Eastern Text Logo"
      ]
    },
    {
      "raw": "logo008_wm\t\t\tGrizzlies Text Logo",
      "parts": [
        "logo008_wm",
        "Grizzlies Text Logo"
      ]
    },
    {
      "raw": "logo009_wm\t\t\tHawks Text Logo",
      "parts": [
        "logo009_wm",
        "Hawks Text Logo"
      ]
    },
    {
      "raw": "logo010_wm\t\t\tHeat Text Logo",
      "parts": [
        "logo010_wm",
        "Heat Text Logo"
      ]
    },
    {
      "raw": "logo011_wm\t\t\tPelicans Text Logo",
      "parts": [
        "logo011_wm",
        "Pelicans Text Logo"
      ]
    },
    {
      "raw": "logo012_wm\t\t\tJazz Text Logo",
      "parts": [
        "logo012_wm",
        "Jazz Text Logo"
      ]
    },
    {
      "raw": "logo013_wm\t\t\tKings Text Logo",
      "parts": [
        "logo013_wm",
        "Kings Text Logo"
      ]
    },
    {
      "raw": "logo014_wm\t\t\tKnicks Text Logo",
      "parts": [
        "logo014_wm",
        "Knicks Text Logo"
      ]
    },
    {
      "raw": "logo015_wm\t\t\tLakers Text Logo",
      "parts": [
        "logo015_wm",
        "Lakers Text Logo"
      ]
    },
    {
      "raw": "logo016_wm\t\t\tMagic Text Logo",
      "parts": [
        "logo016_wm",
        "Magic Text Logo"
      ]
    },
    {
      "raw": "logo017_wm\t\t\tMavericks Text Logo",
      "parts": [
        "logo017_wm",
        "Mavericks Text Logo"
      ]
    },
    {
      "raw": "logo018_wm\t\t\tNets Text Logo",
      "parts": [
        "logo018_wm",
        "Nets Text Logo"
      ]
    },
    {
      "raw": "logo019_wm\t\t\tNuggets Text Logo",
      "parts": [
        "logo019_wm",
        "Nuggets Text Logo"
      ]
    },
    {
      "raw": "logo020_wm\t\t\tPacers Text Logo",
      "parts": [
        "logo020_wm",
        "Pacers Text Logo"
      ]
    },
    {
      "raw": "logo021_wm\t\t\tPistons Text Logo",
      "parts": [
        "logo021_wm",
        "Pistons Text Logo"
      ]
    },
    {
      "raw": "logo022_wm\t\t\tRaptors Text Logo",
      "parts": [
        "logo022_wm",
        "Raptors Text Logo"
      ]
    },
    {
      "raw": "logo023_wm\t\t\tRockets Text Logo",
      "parts": [
        "logo023_wm",
        "Rockets Text Logo"
      ]
    },
    {
      "raw": "logo024_wm\t\t\tThunder Text Logo",
      "parts": [
        "logo024_wm",
        "Thunder Text Logo"
      ]
    },
    {
      "raw": "logo025_wm\t\t\tSpurs Text Logo",
      "parts": [
        "logo025_wm",
        "Spurs Text Logo"
      ]
    },
    {
      "raw": "logo026_wm\t\t\tSuns Text Logo",
      "parts": [
        "logo026_wm",
        "Suns Text Logo"
      ]
    },
    {
      "raw": "logo027_wm\t\t\tTimberwolves Text Logo",
      "parts": [
        "logo027_wm",
        "Timberwolves Text Logo"
      ]
    },
    {
      "raw": "logo028_wm\t\t\tTrailblazers Text Logo",
      "parts": [
        "logo028_wm",
        "Trailblazers Text Logo"
      ]
    },
    {
      "raw": "logo029_wm\t\t\tWarriors Text Logo",
      "parts": [
        "logo029_wm",
        "Warriors Text Logo"
      ]
    },
    {
      "raw": "logo030_wm\t\t\tWestern Text Logo",
      "parts": [
        "logo030_wm",
        "Western Text Logo"
      ]
    },
    {
      "raw": "logo031_wm\t\t\tBobcats Text Logo",
      "parts": [
        "logo031_wm",
        "Bobcats Text Logo"
      ]
    }
] as const;
