// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKTextTemplateSources = {
  "source": "Local RED MC tutorial/docs and discovered 2K14 files",
  "gridNames": [
    "Players",
    "Rookie_Templates",
    "CAP_Templates",
    "MP_Templates",
    "My_Legend",
    "Arenas",
    "Teams",
    "Colleges",
    "ScheduleBase_82",
    "ScheduleBase_58",
    "ScheduleBase_29",
    "ScheduleBase_14",
    "ScheduleBase_PreSeason",
    "Staff",
    "Old_Coach_Stats",
    "Playbooks_actual",
    "Playbooks_default",
    "Player_Stats",
    "Team_Stats",
    "First_Names",
    "Last_Names",
    "City_Names",
    "Jerseys",
    "Headshapes",
    "Overriding_Rotations",
    "Player_Ratings0",
    "Player_Ratings1",
    "Player_Ratings2",
    "Player_Ratings3",
    "Player_Ratings4",
    "Records",
    "Awards",
    "Draft_Projection",
    "Trades",
    "Matchups",
    "Hall_Of_Fame",
    "OnLine_TeamUp",
    "Skills Boosts"
  ],
  "hiddenArenaIds": [
    {
      "raw": "032\t\t\t2012(?) All-Star Court",
      "parts": [
        "032",
        "2012(?) All-Star Court"
      ]
    },
    {
      "raw": "033\t\t\t2013 Houstin All-Star Court",
      "parts": [
        "033",
        "2013 Houstin All-Star Court"
      ]
    },
    {
      "raw": "550\t\t\tJordan Brand Arena (No Arena, just floor)",
      "parts": [
        "550",
        "Jordan Brand Arena (No Arena, just floor)"
      ]
    },
    {
      "raw": "611\t\t\tRucker Park (Model3D voids floor ID)",
      "parts": [
        "611",
        "Rucker Park (Model3D voids floor ID)"
      ]
    },
    {
      "raw": "733\t\t\tNBA 2K Arena (No arena, just floor)",
      "parts": [
        "733",
        "NBA 2K Arena (No arena, just floor)"
      ]
    },
    {
      "raw": "735\t\t\tSummer Circuit Arena",
      "parts": [
        "735",
        "Summer Circuit Arena"
      ]
    }
  ],
  "hiddenLogos": [
    {
      "raw": "logo300\t\t\t\t50s-60s Legends",
      "parts": [
        "logo300",
        "50s-60s Legends"
      ]
    },
    {
      "raw": "logo301\t\t\t\t70s-East Legends",
      "parts": [
        "logo301",
        "70s-East Legends"
      ]
    },
    {
      "raw": "logo302\t\t\t\t70s-West Legends",
      "parts": [
        "logo302",
        "70s-West Legends"
      ]
    },
    {
      "raw": "logo303\t\t\t\t80s-East Legends",
      "parts": [
        "logo303",
        "80s-East Legends"
      ]
    },
    {
      "raw": "logo304\t\t\t\t80s-West Legends",
      "parts": [
        "logo304",
        "80s-West Legends"
      ]
    },
    {
      "raw": "logo305\t\t\t\t90s-East Legends",
      "parts": [
        "logo305",
        "90s-East Legends"
      ]
    },
    {
      "raw": "logo306\t\t\t\t90s-West Legends",
      "parts": [
        "logo306",
        "90s-West Legends"
      ]
    },
    {
      "raw": "logo500\t\t\t\tNBA 2K13 Logo",
      "parts": [
        "logo500",
        "NBA 2K13 Logo"
      ]
    },
    {
      "raw": "logo501\t\t\t\t2K Sports Logo",
      "parts": [
        "logo501",
        "2K Sports Logo"
      ]
    },
    {
      "raw": "logo502\t\t\t\tVisual Concepts",
      "parts": [
        "logo502",
        "Visual Concepts"
      ]
    },
    {
      "raw": "logo503\t\t\t\tInternational All-Stars",
      "parts": [
        "logo503",
        "International All-Stars"
      ]
    },
    {
      "raw": "logo504\t\t\t\tRookies",
      "parts": [
        "logo504",
        "Rookies"
      ]
    },
    {
      "raw": "logo505\t\t\t\tSophomore",
      "parts": [
        "logo505",
        "Sophomore"
      ]
    },
    {
      "raw": "logo506\t\t\t\tSuperstars",
      "parts": [
        "logo506",
        "Superstars"
      ]
    },
    {
      "raw": "logo509\t\t\t\tOld Knicks Logo",
      "parts": [
        "logo509",
        "Old Knicks Logo"
      ]
    },
    {
      "raw": "logo510\t\t\t\tRetro 76ers Logo",
      "parts": [
        "logo510",
        "Retro 76ers Logo"
      ]
    },
    {
      "raw": "logo511\t\t\t\tSupersonics Logo (S)",
      "parts": [
        "logo511",
        "Supersonics Logo (S)"
      ]
    },
    {
      "raw": "logo512\t\t\t\t2K China Logo",
      "parts": [
        "logo512",
        "2K China Logo"
      ]
    },
    {
      "raw": "logo513\t\t\t\t2K Sphere Logo",
      "parts": [
        "logo513",
        "2K Sphere Logo"
      ]
    },
    {
      "raw": "logo515\t\t\t\tCelebrity Team Logo",
      "parts": [
        "logo515",
        "Celebrity Team Logo"
      ]
    },
    {
      "raw": "logo516\t\t\t\tDream Team Logo",
      "parts": [
        "logo516",
        "Dream Team Logo"
      ]
    },
    {
      "raw": "logo517\t\t\t\tTeam USA Logo",
      "parts": [
        "logo517",
        "Team USA Logo"
      ]
    },
    {
      "raw": "logo520\t\t\t\t2000 Draft Class Logo",
      "parts": [
        "logo520",
        "2000 Draft Class Logo"
      ]
    },
    {
      "raw": "logo521\t\t\t\t2001 Draft Class Logo",
      "parts": [
        "logo521",
        "2001 Draft Class Logo"
      ]
    },
    {
      "raw": "logo522\t\t\t\t2002 Draft Class Logo",
      "parts": [
        "logo522",
        "2002 Draft Class Logo"
      ]
    },
    {
      "raw": "logo523\t\t\t\t2003 Draft Class Logo",
      "parts": [
        "logo523",
        "2003 Draft Class Logo"
      ]
    },
    {
      "raw": "logo524\t\t\t\t2004 Draft Class Logo",
      "parts": [
        "logo524",
        "2004 Draft Class Logo"
      ]
    },
    {
      "raw": "logo525\t\t\t\t2005 Draft Class Logo",
      "parts": [
        "logo525",
        "2005 Draft Class Logo"
      ]
    },
    {
      "raw": "logo526\t\t\t\t2006 Draft Class Logo",
      "parts": [
        "logo526",
        "2006 Draft Class Logo"
      ]
    },
    {
      "raw": "logo527\t\t\t\t2007 Draft Class Logo",
      "parts": [
        "logo527",
        "2007 Draft Class Logo"
      ]
    },
    {
      "raw": "logo550\t\t\t\tJordan- Jumpman Logo",
      "parts": [
        "logo550",
        "Jordan- Jumpman Logo"
      ]
    },
    {
      "raw": "logo600\t\t\t\tHome Logo",
      "parts": [
        "logo600",
        "Home Logo"
      ]
    },
    {
      "raw": "logo601\t\t\t\tAway Logo",
      "parts": [
        "logo601",
        "Away Logo"
      ]
    },
    {
      "raw": "logo602\t\t\t\tRookie Showcase Logo",
      "parts": [
        "logo602",
        "Rookie Showcase Logo"
      ]
    },
    {
      "raw": "logo603\t\t\t\tNBA '09 Logo (White BG)",
      "parts": [
        "logo603",
        "NBA '09 Logo (White BG)"
      ]
    },
    {
      "raw": "logo604\t\t\t\tThe Elites Logo",
      "parts": [
        "logo604",
        "The Elites Logo"
      ]
    },
    {
      "raw": "logo605\t\t\t\tRookie Stars Logo",
      "parts": [
        "logo605",
        "Rookie Stars Logo"
      ]
    },
    {
      "raw": "logo610\t\t\t\tAll Net Logo",
      "parts": [
        "logo610",
        "All Net Logo"
      ]
    },
    {
      "raw": "logo611\t\t\t\tAnkle Breakers Logo",
      "parts": [
        "logo611",
        "Ankle Breakers Logo"
      ]
    },
    {
      "raw": "logo612\t\t\t\tBuckets Logo",
      "parts": [
        "logo612",
        "Buckets Logo"
      ]
    },
    {
      "raw": "logo613\t\t\t\tClutch Boyz Logo",
      "parts": [
        "logo613",
        "Clutch Boyz Logo"
      ]
    },
    {
      "raw": "logo614\t\t\t\tDroppin' Dimes Logo",
      "parts": [
        "logo614",
        "Droppin' Dimes Logo"
      ]
    },
    {
      "raw": "logo615\t\t\t\tLights Out Logo",
      "parts": [
        "logo615",
        "Lights Out Logo"
      ]
    },
    {
      "raw": "logo616\t\t\t\tMad Handles Logo",
      "parts": [
        "logo616",
        "Mad Handles Logo"
      ]
    },
    {
      "raw": "logo617\t\t\t\tBoats Show Logo",
      "parts": [
        "logo617",
        "Boats Show Logo"
      ]
    },
    {
      "raw": "logo618\t\t\t\tThe Ringers Logo",
      "parts": [
        "logo618",
        "The Ringers Logo"
      ]
    },
    {
      "raw": "logo619\t\t\t\tThe Ballerz Logo",
      "parts": [
        "logo619",
        "The Ballerz Logo"
      ]
    },
    {
      "raw": "logo800\t\t\t\tCAT Power Plant (?) Logo",
      "parts": [
        "logo800",
        "CAT Power Plant (?) Logo"
      ]
    },
    {
      "raw": "logo801\t\t\t\tCAT Train Logo",
      "parts": [
        "logo801",
        "CAT Train Logo"
      ]
    },
    {
      "raw": "logo802\t\t\t\tCAT Lightning Logo",
      "parts": [
        "logo802",
        "CAT Lightning Logo"
      ]
    },
    {
      "raw": "logo803\t\t\t\tCAT Snake Logo",
      "parts": [
        "logo803",
        "CAT Snake Logo"
      ]
    },
    {
      "raw": "logo804\t\t\t\tCAT Erasers Logo",
      "parts": [
        "logo804",
        "CAT Erasers Logo"
      ]
    },
    {
      "raw": "logo805\t\t\t\tCAT Hawks Logo",
      "parts": [
        "logo805",
        "CAT Hawks Logo"
      ]
    },
    {
      "raw": "logo806\t\t\t\tCAT Galaxy Logo",
      "parts": [
        "logo806",
        "CAT Galaxy Logo"
      ]
    },
    {
      "raw": "logo807\t\t\t\t\tCAT ....I don't even know Logo",
      "parts": [
        "logo807",
        "CAT ....I don't even know Logo"
      ]
    },
    {
      "raw": "logo808\t\t\t\tCAT Panther Logo",
      "parts": [
        "logo808",
        "CAT Panther Logo"
      ]
    },
    {
      "raw": "logo809\t\t\t\tCAT Mirage Logo",
      "parts": [
        "logo809",
        "CAT Mirage Logo"
      ]
    },
    {
      "raw": "logo810\t\t\t\t\tCAT A-Hoop Logo",
      "parts": [
        "logo810",
        "CAT A-Hoop Logo"
      ]
    },
    {
      "raw": "logo811\t\t\t\tRhythm Logo",
      "parts": [
        "logo811",
        "Rhythm Logo"
      ]
    },
    {
      "raw": "logo998\t\t\t\tNBA Logo",
      "parts": [
        "logo998",
        "NBA Logo"
      ]
    },
    {
      "raw": "logo999\t\t\t\tFree Agent Logo",
      "parts": [
        "logo999",
        "Free Agent Logo"
      ]
    },
    {
      "raw": "logo_2k_square\t\t\tHQ 2K Logo",
      "parts": [
        "logo_2k_square",
        "HQ 2K Logo"
      ]
    },
    {
      "raw": "logo_adidas_square\t\tAdidas Logo",
      "parts": [
        "logo_adidas_square",
        "Adidas Logo"
      ]
    },
    {
      "raw": "logo_all_star\t\t\tAll Star New Orleans Logo",
      "parts": [
        "logo_all_star",
        "All Star New Orleans Logo"
      ]
    },
    {
      "raw": "logo_all_star_generic\t\tAll Star Generic",
      "parts": [
        "logo_all_star_generic",
        "All Star Generic"
      ]
    },
    {
      "raw": "logo_all_star_wm\t\tAll Star (Jersey Logo?)",
      "parts": [
        "logo_all_star_wm",
        "All Star (Jersey Logo?)"
      ]
    },
    {
      "raw": "logo_bbva\t\t\tOffical Bank of NBA Logo",
      "parts": [
        "logo_bbva",
        "Offical Bank of NBA Logo"
      ]
    },
    {
      "raw": "logo_converse_square\t\tConverse Logo",
      "parts": [
        "logo_converse_square",
        "Converse Logo"
      ]
    },
    {
      "raw": "logo_footlocker\t\t\tFootlocker Ref Logo",
      "parts": [
        "logo_footlocker",
        "Footlocker Ref Logo"
      ]
    },
    {
      "raw": "logo_gatorade\t\t\tGatorade G w/ Lightning Bolt",
      "parts": [
        "logo_gatorade",
        "Gatorade G w/ Lightning Bolt"
      ]
    },
    {
      "raw": "logo_jordan\t\t\tHQ Jumpman",
      "parts": [
        "logo_jordan",
        "HQ Jumpman"
      ]
    },
    {
      "raw": "logo_jordan_square\t\tHQ Jumpman w/ Jordan Text",
      "parts": [
        "logo_jordan_square",
        "HQ Jumpman w/ Jordan Text"
      ]
    },
    {
      "raw": "logo_nba_finals\t\t\tThe Finals text",
      "parts": [
        "logo_nba_finals",
        "The Finals text"
      ]
    },
    {
      "raw": "logo_nba_finals_white\t\tThe Finals text white",
      "parts": [
        "logo_nba_finals_white",
        "The Finals text white"
      ]
    },
    {
      "raw": "logo_nba_playoffs\t\tPlayoffs court logo",
      "parts": [
        "logo_nba_playoffs",
        "Playoffs court logo"
      ]
    },
    {
      "raw": "logo_nba_playoffs_white\t\tPlayoffs court logo white",
      "parts": [
        "logo_nba_playoffs_white",
        "Playoffs court logo white"
      ]
    },
    {
      "raw": "logo_nbdl\t\t\tD League Logo",
      "parts": [
        "logo_nbdl",
        "D League Logo"
      ]
    },
    {
      "raw": "logo_nike\t\t\tNike text w/ Swoosh Logo",
      "parts": [
        "logo_nike",
        "Nike text w/ Swoosh Logo"
      ]
    },
    {
      "raw": "logo_nike_swoosh_square\t\tNike Swoosh",
      "parts": [
        "logo_nike_swoosh_square",
        "Nike Swoosh"
      ]
    },
    {
      "raw": "logo_reebok_square\t\tReebok text",
      "parts": [
        "logo_reebok_square",
        "Reebok text"
      ]
    },
    {
      "raw": "logo_spalding_square\t\tSpalding True to the Game",
      "parts": [
        "logo_spalding_square",
        "Spalding True to the Game"
      ]
    },
    {
      "raw": "logo_sprite\t\t\tSprite Logo",
      "parts": [
        "logo_sprite",
        "Sprite Logo"
      ]
    },
    {
      "raw": "logo_statefarm\t\t\tState Farm Text",
      "parts": [
        "logo_statefarm",
        "State Farm Text"
      ]
    },
    {
      "raw": "logo_under_armour_square\tUA Logo",
      "parts": [
        "logo_under_armour_square",
        "UA Logo"
      ]
    },
    {
      "raw": "Text Based Logos",
      "parts": [
        "Text Based Logos"
      ]
    },
    {
      "raw": "logo000_wm\t\t\tSixers Text Logo",
      "parts": [
        "logo000_wm",
        "Sixers Text Logo"
      ]
    },
    {
      "raw": "logo001_wm\t\t\tBucks Text Logo",
      "parts": [
        "logo001_wm",
        "Bucks Text Logo"
      ]
    },
    {
      "raw": "logo002_wm\t\t\tWizards Text Logo",
      "parts": [
        "logo002_wm",
        "Wizards Text Logo"
      ]
    },
    {
      "raw": "logo003_wm\t\t\tBulls Text Logo",
      "parts": [
        "logo003_wm",
        "Bulls Text Logo"
      ]
    },
    {
      "raw": "logo004_wm\t\t\tOld Cavs Text Logo",
      "parts": [
        "logo004_wm",
        "Old Cavs Text Logo"
      ]
    },
    {
      "raw": "logo005_wm\t\t\tCeltics Text Logo",
      "parts": [
        "logo005_wm",
        "Celtics Text Logo"
      ]
    },
    {
      "raw": "logo006_wm\t\t\tClippers Text Logo",
      "parts": [
        "logo006_wm",
        "Clippers Text Logo"
      ]
    },
    {
      "raw": "logo007_wm\t\t\tEastern Text Logo",
      "parts": [
        "logo007_wm",
        "Eastern Text Logo"
      ]
    },
    {
      "raw": "logo008_wm\t\t\tGrizzlies Text Logo",
      "parts": [
        "logo008_wm",
        "Grizzlies Text Logo"
      ]
    },
    {
      "raw": "logo009_wm\t\t\tHawks Text Logo",
      "parts": [
        "logo009_wm",
        "Hawks Text Logo"
      ]
    },
    {
      "raw": "logo010_wm\t\t\tHeat Text Logo",
      "parts": [
        "logo010_wm",
        "Heat Text Logo"
      ]
    },
    {
      "raw": "logo011_wm\t\t\tPelicans Text Logo",
      "parts": [
        "logo011_wm",
        "Pelicans Text Logo"
      ]
    },
    {
      "raw": "logo012_wm\t\t\tJazz Text Logo",
      "parts": [
        "logo012_wm",
        "Jazz Text Logo"
      ]
    },
    {
      "raw": "logo013_wm\t\t\tKings Text Logo",
      "parts": [
        "logo013_wm",
        "Kings Text Logo"
      ]
    },
    {
      "raw": "logo014_wm\t\t\tKnicks Text Logo",
      "parts": [
        "logo014_wm",
        "Knicks Text Logo"
      ]
    },
    {
      "raw": "logo015_wm\t\t\tLakers Text Logo",
      "parts": [
        "logo015_wm",
        "Lakers Text Logo"
      ]
    },
    {
      "raw": "logo016_wm\t\t\tMagic Text Logo",
      "parts": [
        "logo016_wm",
        "Magic Text Logo"
      ]
    },
    {
      "raw": "logo017_wm\t\t\tMavericks Text Logo",
      "parts": [
        "logo017_wm",
        "Mavericks Text Logo"
      ]
    },
    {
      "raw": "logo018_wm\t\t\tNets Text Logo",
      "parts": [
        "logo018_wm",
        "Nets Text Logo"
      ]
    },
    {
      "raw": "logo019_wm\t\t\tNuggets Text Logo",
      "parts": [
        "logo019_wm",
        "Nuggets Text Logo"
      ]
    },
    {
      "raw": "logo020_wm\t\t\tPacers Text Logo",
      "parts": [
        "logo020_wm",
        "Pacers Text Logo"
      ]
    },
    {
      "raw": "logo021_wm\t\t\tPistons Text Logo",
      "parts": [
        "logo021_wm",
        "Pistons Text Logo"
      ]
    },
    {
      "raw": "logo022_wm\t\t\tRaptors Text Logo",
      "parts": [
        "logo022_wm",
        "Raptors Text Logo"
      ]
    },
    {
      "raw": "logo023_wm\t\t\tRockets Text Logo",
      "parts": [
        "logo023_wm",
        "Rockets Text Logo"
      ]
    },
    {
      "raw": "logo024_wm\t\t\tThunder Text Logo",
      "parts": [
        "logo024_wm",
        "Thunder Text Logo"
      ]
    },
    {
      "raw": "logo025_wm\t\t\tSpurs Text Logo",
      "parts": [
        "logo025_wm",
        "Spurs Text Logo"
      ]
    },
    {
      "raw": "logo026_wm\t\t\tSuns Text Logo",
      "parts": [
        "logo026_wm",
        "Suns Text Logo"
      ]
    },
    {
      "raw": "logo027_wm\t\t\tTimberwolves Text Logo",
      "parts": [
        "logo027_wm",
        "Timberwolves Text Logo"
      ]
    },
    {
      "raw": "logo028_wm\t\t\tTrailblazers Text Logo",
      "parts": [
        "logo028_wm",
        "Trailblazers Text Logo"
      ]
    },
    {
      "raw": "logo029_wm\t\t\tWarriors Text Logo",
      "parts": [
        "logo029_wm",
        "Warriors Text Logo"
      ]
    },
    {
      "raw": "logo030_wm\t\t\tWestern Text Logo",
      "parts": [
        "logo030_wm",
        "Western Text Logo"
      ]
    },
    {
      "raw": "logo031_wm\t\t\tBobcats Text Logo",
      "parts": [
        "logo031_wm",
        "Bobcats Text Logo"
      ]
    }
  ],
  "candidateAssetBuckets": {
    "career": 5,
    "coaches": 4,
    "draft": 66,
    "franchise": 3,
    "presentation": 67,
    "schedule": 2,
    "social": 2,
    "staff_team": 200,
    "tutorial": 3
  },
  "headlineSeedFiles": [
    "careerupdaterecap.iff",
    "draft_lines.bin",
    "socialmedia_profilepics.iff",
    "franchise.iff",
    "career_endorsements.iff"
  ],
  "notes": [
    "Most headline/news text in NBA 2K14 is not exposed as plain text in this install, so these are source hints and schema references rather than extracted prose.",
    "Use the caption labels and transaction structure as generators for nba-commish-native templates."
  ]
} as const;
