// Auto-generated by python/extract_2k_importables.py. Edit the generator, not this file.

export const twoKTransactionSchema = {
  "source": "RED MC NBA2K14 transaction captions",
  "baseFields": [
    {
      "code": "Year",
      "label": "Year",
      "description": "Year"
    },
    {
      "code": "Month",
      "label": "Month",
      "description": "Month"
    },
    {
      "code": "Day",
      "label": "Day",
      "description": "Day"
    },
    {
      "code": "Hour",
      "label": "Hour",
      "description": "Hour"
    },
    {
      "code": "Minute",
      "label": "Minute",
      "description": "Minute"
    },
    {
      "code": "Order",
      "label": "Order",
      "description": "If several transactions take place at the same time, this defines their order."
    }
  ],
  "items": [
    {
      "itemNumber": 1,
      "fields": [
        {
          "code": "I1_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 1,
          "subCode": "DPRnd"
        },
        {
          "code": "I1_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 1,
          "subCode": "DPTm"
        },
        {
          "code": "I1_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 1,
          "subCode": "FrmTm"
        },
        {
          "code": "I1_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 1,
          "subCode": "ItmT"
        },
        {
          "code": "I1_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 1,
          "subCode": "Plyr"
        },
        {
          "code": "I1_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 1,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 2,
      "fields": [
        {
          "code": "I2_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 2,
          "subCode": "DPRnd"
        },
        {
          "code": "I2_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 2,
          "subCode": "DPTm"
        },
        {
          "code": "I2_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 2,
          "subCode": "FrmTm"
        },
        {
          "code": "I2_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 2,
          "subCode": "ItmT"
        },
        {
          "code": "I2_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 2,
          "subCode": "Plyr"
        },
        {
          "code": "I2_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 2,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 3,
      "fields": [
        {
          "code": "I3_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 3,
          "subCode": "DPRnd"
        },
        {
          "code": "I3_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 3,
          "subCode": "DPTm"
        },
        {
          "code": "I3_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 3,
          "subCode": "FrmTm"
        },
        {
          "code": "I3_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 3,
          "subCode": "ItmT"
        },
        {
          "code": "I3_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 3,
          "subCode": "Plyr"
        },
        {
          "code": "I3_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 3,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 4,
      "fields": [
        {
          "code": "I4_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 4,
          "subCode": "DPRnd"
        },
        {
          "code": "I4_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 4,
          "subCode": "DPTm"
        },
        {
          "code": "I4_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 4,
          "subCode": "FrmTm"
        },
        {
          "code": "I4_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 4,
          "subCode": "ItmT"
        },
        {
          "code": "I4_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 4,
          "subCode": "Plyr"
        },
        {
          "code": "I4_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 4,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 5,
      "fields": [
        {
          "code": "I5_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 5,
          "subCode": "DPRnd"
        },
        {
          "code": "I5_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 5,
          "subCode": "DPTm"
        },
        {
          "code": "I5_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 5,
          "subCode": "FrmTm"
        },
        {
          "code": "I5_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 5,
          "subCode": "ItmT"
        },
        {
          "code": "I5_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 5,
          "subCode": "Plyr"
        },
        {
          "code": "I5_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 5,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 6,
      "fields": [
        {
          "code": "I6_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 6,
          "subCode": "DPRnd"
        },
        {
          "code": "I6_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 6,
          "subCode": "DPTm"
        },
        {
          "code": "I6_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 6,
          "subCode": "FrmTm"
        },
        {
          "code": "I6_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 6,
          "subCode": "ItmT"
        },
        {
          "code": "I6_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 6,
          "subCode": "Plyr"
        },
        {
          "code": "I6_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 6,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 7,
      "fields": [
        {
          "code": "I7_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 7,
          "subCode": "DPRnd"
        },
        {
          "code": "I7_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 7,
          "subCode": "DPTm"
        },
        {
          "code": "I7_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 7,
          "subCode": "FrmTm"
        },
        {
          "code": "I7_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 7,
          "subCode": "ItmT"
        },
        {
          "code": "I7_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 7,
          "subCode": "Plyr"
        },
        {
          "code": "I7_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 7,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 8,
      "fields": [
        {
          "code": "I8_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 8,
          "subCode": "DPRnd"
        },
        {
          "code": "I8_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 8,
          "subCode": "DPTm"
        },
        {
          "code": "I8_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 8,
          "subCode": "FrmTm"
        },
        {
          "code": "I8_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 8,
          "subCode": "ItmT"
        },
        {
          "code": "I8_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 8,
          "subCode": "Plyr"
        },
        {
          "code": "I8_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 8,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 9,
      "fields": [
        {
          "code": "I9_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 9,
          "subCode": "DPRnd"
        },
        {
          "code": "I9_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 9,
          "subCode": "DPTm"
        },
        {
          "code": "I9_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 9,
          "subCode": "FrmTm"
        },
        {
          "code": "I9_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 9,
          "subCode": "ItmT"
        },
        {
          "code": "I9_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 9,
          "subCode": "Plyr"
        },
        {
          "code": "I9_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 9,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 10,
      "fields": [
        {
          "code": "I10_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 10,
          "subCode": "DPRnd"
        },
        {
          "code": "I10_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 10,
          "subCode": "DPTm"
        },
        {
          "code": "I10_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 10,
          "subCode": "FrmTm"
        },
        {
          "code": "I10_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 10,
          "subCode": "ItmT"
        },
        {
          "code": "I10_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 10,
          "subCode": "Plyr"
        },
        {
          "code": "I10_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 10,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 11,
      "fields": [
        {
          "code": "I11_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 11,
          "subCode": "DPRnd"
        },
        {
          "code": "I11_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 11,
          "subCode": "DPTm"
        },
        {
          "code": "I11_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 11,
          "subCode": "FrmTm"
        },
        {
          "code": "I11_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 11,
          "subCode": "ItmT"
        },
        {
          "code": "I11_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 11,
          "subCode": "Plyr"
        },
        {
          "code": "I11_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 11,
          "subCode": "ToTm"
        }
      ]
    },
    {
      "itemNumber": 12,
      "fields": [
        {
          "code": "I12_DPRnd",
          "label": "Draft Pick Round",
          "description": "If the item is a draft pick, then this field indicates draft round",
          "itemNumber": 12,
          "subCode": "DPRnd"
        },
        {
          "code": "I12_DPTm",
          "label": "Draft Pick Team (GID)",
          "description": "If the item is a draft pick, then this field contains the GID of its original holder team.",
          "itemNumber": 12,
          "subCode": "DPTm"
        },
        {
          "code": "I12_FrmTm",
          "label": "From Team (GID)",
          "description": "Defines the team, which sold the 1st item, by its GID.",
          "itemNumber": 12,
          "subCode": "FrmTm"
        },
        {
          "code": "I12_ItmT",
          "label": "Item Type",
          "description": "Defines the type of the item",
          "itemNumber": 12,
          "subCode": "ItmT"
        },
        {
          "code": "I12_Plyr",
          "label": "Player (ASA_ID)",
          "description": "If the item is a player, then this field is used to identify him by his ASA_ID",
          "itemNumber": 12,
          "subCode": "Plyr"
        },
        {
          "code": "I12_ToTm",
          "label": "To Team (GID)",
          "description": "Defines the team, which bought the 1st item, by its GID.",
          "itemNumber": 12,
          "subCode": "ToTm"
        }
      ]
    }
  ],
  "notes": [
    "These fields are useful for building Football Manager-style transaction logs and headline generators.",
    "The schema is grouped into base timestamp/order fields plus repeating item slots."
  ]
} as const;
