export const DRIVING_DUNK: Record<string, number> = {
  // 90+ TIER
  'Anthony Edwards':      97,
  'Jalen Johnson':        96,
  'Ja Morant':            96,
  'Amen Thompson':        96,
  'Jalen Duren':          95,
  'Shaedon Sharpe':       95,
  'Jaylen Brown':         94,
  'Aaron Gordon':         94,
  'Zach LaVine':          94,
  'Derrick Jones Jr.':    94,
  'Mac McClung':          94,
  'Zion Williamson':      93,
  'Donovan Mitchell':     92,
  'Giannis Antetokounmpo':91,
  'Ausar Thompson':       91,
  'Jalen Green':          91,
  'John Collins':         90,
  'Obi Toppin':           90,

  // 85–89 TIER
  'Jayson Tatum':         89,
  'VJ Edgecombe':         89,
  'Matas Buzelis':        89,
  'Anfernee Simons':      89,
  'Jericho Sims':         89,
  'Trey Murphy III':      88,
  'Stephon Castle':       88,
  'Miles Bridges':        88,
  'Scoot Henderson':      88,
  'Jaime Jaquez Jr.':     88,
  'Jaxson Hayes':         88,
  'Carter Bryant':        88,
  'Adou Thiero':          88,
  'Brandon Miller':       87,
  'Jase Richardson':      87,
  'Andre Jackson Jr.':    87,
  'Dylan Harper':         86,
  "Kel'el Ware":          86,
  'Pat Connaughton':      86,
  'Blake Wesley':         86,
  'Keshad Johnson':       86,
  'Victor Wembanyama':    85,
  'Kevin Durant':         85,
  'LeBron James':         85,
  'Anthony Davis':        85,
  'Damian Lillard':       85,
  'Evan Mobley':          85,
  'Jarrett Allen':        85,
  'Paolo Banchero':       85,
  'OG Anunoby':           85,
  'Alexandre Sarr':       85,
  'Jerami Grant':         85,
  'Onyeka Okongwu':       85,
  'Andrew Wiggins':       85,
  'Jabari Smith Jr.':     85,
  'Jarace Walker':        85,
  'Jonathan Kuminga':     85,
  'Luguentz Dort':        85,
  'Christian Braun':      85,
  'GG Jackson':           85,
  'Bilal Coulibaly':      85,
  'Jaden Ivey':           85,
  'Javonte Green':        85,
  'Kobe Sanders':         85,
  'Guerschon Yabusele':   85,
  'Asa Newell':           85,
  'Olivier-Maxence Prosper': 85,
  'Mohamed Diawara':      85,
  'Jamir Watkins':        85,
  'Drake Powell':         85,
  'Terrence Shannon Jr.': 85,
  'Trayce Jackson-Davis': 85,
  'Leonard Miller':       85,
  'Alijah Martin':        85,
  'Thanasis Antetokounmpo': 85,
  'Chaney Johnson':       85,
  'JD Davison':           85,
  'Chris Manon':          85,

  // 80–84 TIER
  'Brandon Clarke':       84,
  'Kelly Oubre Jr.':      84,
  'Dorian Finney-Smith':  84,
  'Dereck Lively II':     83,
  'Jamal Murray':         82,
  'Kawhi Leonard':        80,
  'Joel Embiid':          80,
  'Bam Adebayo':          80,
  'Cooper Flagg':         80,
  'Julius Randle':        80,
  'Alperen Sengun':       80,
  'Lauri Markkanen':      80,
  'Pascal Siakam':        80,
  'Brandon Ingram':       80,
  'Scottie Barnes':       80,
  'Franz Wagner':         80,
  'Jalen Williams':       80,
  'Michael Porter Jr.':   80,
  'Jaren Jackson Jr.':    80,
  'Norman Powell':        80,
  'Ivica Zubac':          80,
  "De'Aaron Fox":         80,
  'DeMar DeRozan':        80,
  'Kevin Porter Jr.':     80,
};
