import type { DraftPick, NBAPlayer } from './player';

export interface TransactionDto {
  teams: {
    [tid: number]: {
      playersSent: NBAPlayer[];
      picksSent: DraftPick[];
      cashSentUSD?: number;
    };
  };
}

export type ActionType =
  | 'SET_TRAINING_DAILY_PLAN'
  | 'SET_TRAINING_NORMAL_DEFAULT'
  | 'SET_PLAYER_DEV_FOCUS'
  | 'SET_PLAYER_MENTOR'
  | 'RESET_PLAYER_FAMILIARITY'
  | 'SET_PLAYER_TRAINING_INTENSITY'
  | 'AUTOFILL_TEAM_TRAINING_CALENDAR'
  | 'REPLY_EMAIL'
  | 'BRIBE'
  | 'HYPNOTIZE'
  | 'PUBLIC_STATEMENT'
  | 'ADVANCE_DAY'
  | 'DIRECT_MESSAGE'
  | 'SEND_MESSAGE'
  | 'SEND_CHAT_MESSAGE'
  | 'UPDATE_RULES'
  | 'SUSPEND_PLAYER'
  | 'CLEAR_OUTCOME'
  | 'SAVE_SOCIAL_THREAD'
  | 'FINE_PERSON'
  | 'BRIBE_PERSON'
  | 'GLOBAL_GAMES'
  | 'LEAK_SCANDAL'
  | 'HYPNOTIC_BROADCAST'
  | 'RIG_LOTTERY'
  | 'CELEBRITY_ROSTER'
  | 'OWNER_DINNER'
  | 'PUBLIC_ANNOUNCEMENT'
  | 'SUSPEND_PERSON'
  | 'DRUG_TEST_PERSON'
  | 'INVITE_DINNER'
  | 'EXPANSION_DRAFT'
  | 'ANNOUNCE_CHANGE'
  | 'START_GAME'
  | 'INIT_EURO_CAREER'
  | 'INIT_PBA_CAREER'
  | 'LOAD_GAME'
  | 'UPDATE_SAVE_ID'
  | 'SIGN_FREE_AGENT'
  | 'EXECUTIVE_TRADE'
  | 'TRAVEL'
  | 'GIVE_MONEY'
  | 'VISIT_NON_NBA_TEAM'
  | 'INVITE_PERFORMANCE'
  | 'FORCE_TRADE'
  | 'ADJUST_FINANCIALS'
  | 'FOLLOW_USER'
  | 'UNFOLLOW_USER'
  | 'ADD_PENDING_HYPNOSIS'
  | 'MARK_PAYSLIPS_READ'
  | 'TRANSFER_FUNDS'
  | 'SET_CHRISTMAS_GAMES'
  | 'SABOTAGE_PLAYER'
  | 'GO_TO_CLUB'
  | 'ENDORSE_HOF'
  | 'SIMULATE_TO_DATE'
  | 'ADD_PRESEASON_INTERNATIONAL'
  | 'ALL_STAR_ADVANCE_VOTES'
  | 'ALL_STAR_ANNOUNCE_STARTERS'
  | 'ALL_STAR_ANNOUNCE_RESERVES'
  | 'ALL_STAR_SIMULATE_WEEKEND'
  | 'GENERATE_PLAYOFF_BRACKET'
  | 'SIM_PLAYOFF_ROUND'
  | 'SAVE_CONTEST_RESULT'
  | 'SAVE_THRONE_RESULT'
  | 'MERGE_THRONE_LIFECYCLE'
  | 'RECORD_WATCHED_GAME'
  | 'WAIVE_PLAYER'
  | 'FIRE_PERSONNEL'
  | 'STORE_PURCHASE'
  | 'RIG_ALL_STAR_VOTING'
  | 'SET_ALL_STAR_REPLACEMENT'
  | 'SET_DUNK_CONTESTANTS'
  | 'SET_THREE_POINT_CONTESTANTS'
  | 'ADD_ALL_STAR_REPLACEMENT'
  | 'REAL_ESTATE_INVENTORY_UPDATE'
  | 'COMMISH_STORE_INVENTORY_UPDATE'
  | 'CACHE_PROFILE'
  | 'UPDATE_USER_PROFILE'
  | 'ADD_USER_POST'
  | 'ADD_REPLIES'
  | 'SET_FEED'
  | 'UPDATE_STATE'
  | 'SUBMIT_FA_BID'
  | 'RETIRE_JERSEY_NUMBER'
  | 'MATCH_RFA_OFFER'
  | 'DECLINE_RFA_OFFER'
  | 'TOGGLE_LIKE'
  | 'TOGGLE_RETWEET'
  | 'ADD_POST'
  | 'ADD_REPLY'
  | 'EXERCISE_TEAM_OPTION'
  | 'DECLINE_TEAM_OPTION'
  | 'CONVERT_CONTRACT_TYPE'
  | 'ADVANCE_PBA_CONFERENCE'
  | 'RECORD_PBA_CHAMPION'
  | 'OFFSEASON_ENTER_PHASE'
  | 'OFFSEASON_COMPLETE_PHASE'
  | 'OFFSEASON_SKIP_PHASE'
  | 'OFFSEASON_AUTO_RESOLVE_ALL'
  | 'OFFSEASON_ADVANCE_FA_TAG'
  | 'OFFSEASON_EXIT'
  | 'OFFSEASON_RESOLVE_DECISION'
  | 'OFFSEASON_RESET_CHECKLIST'
  | 'SUBMIT_QUALIFYING_OFFER'
  | 'SKIP_QUALIFYING_OFFER'
  | 'SCHEDULE_EXPANSION'
  | 'ACTIVATE_EXPANSION_NOW'
  | 'CLEAR_EXPANSION_SCHEDULE'
  | 'SET_EXPANSION_PROTECTIONS'
  | 'APPLY_EXPANSION_REALIGNMENT'
  | 'EXPANSION_DRAFT_PICK'
  | 'UPDATE_TEAM_POP'
  | 'EXPANSION_DRAFT_COMPLETE'
  | 'PROMOTE_YOUTH'
  | 'LIST_PLAYER_FOR_TRANSFER'
  | 'CANCEL_TRANSFER_LISTING'
  | 'SUBMIT_TRANSFER_BID'
  | 'ACCEPT_TRANSFER_BID'
  | 'REJECT_TRANSFER_BID'
  | 'TICK_TRANSFER_MARKET'
  | 'LIST_PLAYER_TRANSFER';

export interface UserAction {
  type: ActionType;
  payload?: any;
}

export interface TradeProposal {
  id: string;
  proposingTeamId: number;
  receivingTeamId: number;
  proposingGMName: string;
  playersOffered: string[];
  playersRequested: string[];
  picksOffered: number[];
  picksRequested: number[];
  cashOfferedUSD?: number;
  cashRequestedUSD?: number;
  proposedDate: string;
  status: 'pending' | 'accepted' | 'rejected' | 'expired' | 'executed';
  isAIvsAI: boolean;
  tradeText?: string;
  isSignAndTrade?: boolean;
  cbaValid?: boolean;
  cbaReason?: string;
  cbaOffendingSide?: 'A' | 'B';
}
