export type SocialSource = 'TwitterX' | 'Feddit';

export type Conference = 'East' | 'West';

export type GamePhase =
  | 'Preseason'
  | 'Opening Week'
  | 'Regular Season (Early)'
  | 'Regular Season (Mid)'
  | 'All-Star Break'
  | 'Trade Deadline'
  | 'Regular Season (Late)'
  | 'Play-In Tournament'
  | 'Playoffs (Round 1)'
  | 'Playoffs (Round 2)'
  | 'Conference Finals'
  | 'NBA Finals'
  | 'Offseason'
  | 'Draft'
  | 'Draft Lottery'
  | 'Free Agency'
  | 'Schedule Planning'
  | 'Schedule Release'
  | 'Training Camp';

export type Tab =
  | 'Inbox'
  | 'Messages'
  | 'Social Feed'
  | 'NBA Central'
  | 'Schedule'
  | 'Commissioner'
  | 'League News'
  | 'Player Stats'
  | 'Award Races'
  | 'Actions'
  | 'League Settings'
  | 'Personal'
  | 'Player Search'
  | 'Free Agents'
  | 'Team Stats'
  | 'All-Star'
  | 'NBA Cup'
  | 'Playoffs'
  | 'League Office'
  | 'League Leaders'
  | 'Injuries'
  | 'Broadcasting'
  | 'Approvals'
  | 'Viewership'
  | 'Finances'
  | 'League Finances'
  | 'Team Finances'
  | 'Front Office'
  | 'Front Office Finances'
  | 'Front Office Sponsorships'
  | 'Front Office Travel'
  | 'Front Office Medical'
  | 'Front Office Facilities'
  | 'Front Office Staff'
  | 'Front Office Transfer Market'
  | 'Draft Scouting'
  | 'Draft Lottery'
  | 'Standings'
  | 'Statistical Feats'
  | 'Transactions'
  | 'Trade Machine'
  | 'Trade Finder'
  | 'Trade Proposals'
  | 'Commish Store'
  | 'Events'
  | 'Seasonal'
  | 'Real Stern'
  | 'Sports Book'
  | 'Player Ratings'
  | 'Player Creator'
  | 'League History'
  | 'Player Bios'
  | 'Player Comparison'
  | 'Team History'
  | 'Season Preview'
  | 'Power Rankings'
  | 'Draft Board'
  | 'Draft History'
  | 'Team Office'
  | 'Coaching'
  | 'Training Center'
  | 'Hall of Fame'
  | 'Euroleague'
  | 'Liga Endesa'
  | 'Euroleague Hub'
  | 'Endesa Hub'
  | 'G-League Hub'
  | 'WNBA Hub'
  | 'B-League Hub'
  | 'China CBA Hub'
  | 'NBL Australia Hub'
  | 'PBA Hub'
  | 'PBA Philippine Hub'
  | 'PBA Commissioners Hub'
  | 'PBA Governors Hub';

export type CommissionerTab = 'Approvals' | 'Viewership' | 'Finances';
