import type { NBAConf, NBADiv } from './team';

export interface Morale {
  fans: number;
  players: number;
  owners: number;
  legacy: number;
}

export interface Rule {
  id: string;
  title: string;
  description: string;
}

export interface MediaRights {
  activeBroadcasters: string[];
  lpPrice: number;
  lpPriceMonthly?: number;
  totalRev: number;
  mediaRev: number;
  lpRev: number;
  salaryCap: number;
  phaseAssignments?: Record<string, string[]>;
  scheduleAssignments?: Record<string, string[]>;
  isLocked: boolean;
}

export interface LeagueStats {
  revenue: number;
  mediaRights?: MediaRights;
  viewership: number;
  viewershipHistory?: { date: string; viewers: number }[];
  revenueHistory?: { date: string; revenue: number }[];
  baseViewershipModifier?: number;
  salaryCap: number;
  luxuryPayroll: number;
  luxuryTax: number;
  minContract: number;
  maxContract: number;
  numGamesPlayoffSeries: number[];
  playIn: boolean;
  inSeasonTournament: boolean;
  cupPrizePoolEnabled?: boolean;
  cupPrizePoolAutoInflate?: boolean;
  cupPrizeWinner?: number;
  cupPrizeRunnerUp?: number;
  cupPrizeSemi?: number;
  cupPrizeQuarter?: number;
  minAgeRequirement: number;
  rules: Rule[];
  morale: Morale;
  year: number;
  uiMode?: 'nba' | 'euro_isolated' | 'pba_isolated';
  currency?: 'USD' | 'EUR' | 'GBP' | 'JPY' | 'CNY' | 'AUD' | 'PHP';
  tradesAllowed?: boolean;
  euroMinSalaryUSD?: number;
  euroMaxSalaryUSD?: number;
  euroleagueBRL?: number;
  transferMarket?: {
    enabled: boolean;
    summerStart: string;
    summerEnd: string;
    winterStart: string;
    winterEnd: string;
    auctionDays: number;
    tierGating: boolean;
    bidderPool: 'euro' | 'plus_nba' | 'all';
    releaseClauseDefaultMult: number;
  };
  hofClassesInducted?: number[];
  draftType: string;
  allStarEnding?: string;
  allStarBreakStart?: string;
  allStarBreakEnd?: string;
  minGamesRequirement?: number;
  awards?: Rule[];
  trophies?: Rule[];
  awardSettings?: import('../services/awards/types').AwardSettings;
  celebrityGame?: boolean;
  globalGames?: boolean;
  hasScheduledGlobalGames?: boolean;
  hasSetCelebrityRoster?: boolean;
  celebrityRosterAutoSelected?: boolean;
  celebrityRoster?: string[];
  hasExpanded?: boolean;
  auto2029ExpansionSeeded?: boolean;
  autoOwnerSeeded?: boolean;
  euroPayrollScaleHealed?: boolean;
  staffPoolSeeded?: boolean;
  historyIdentityMigrationVersion?: number;
  pbaConference?: 'philippine' | 'commissioners' | 'governors';
  pbaConferencePhase?: 'setup' | 'regularSeason' | 'playoffs' | 'complete' | 'offseason';
  pbaYearEndRolloverPreparedSeason?: number;
  pbaLocalEligibilityMode?: 'registered_roster' | 'filipino_only';
  pbaDraftComplete?: boolean;
  pbaOpeningWatched?: boolean;
  pbaMuseSelected?: boolean;
  pbaConferenceChampions?: Array<{
    season: number;
    conference: 'philippine' | 'commissioners' | 'governors';
    teamId: number;
    teamName: string;
    finalsMvpId?: string;
    bestPlayerId?: string;
    bestImportId?: string;
  }>;
  pbaGrandSlam?: Array<{
    season: number;
    teamId: number;
    teamName: string;
  }>;
  pbaAllStarResults?: {
    season: number;
    captainA: { playerId: string; playerName: string };
    captainB: { playerId: string; playerName: string };
    teamAScore: number;
    teamBScore: number;
    mvpIds: string[];
    threePointWinnerId?: string;
    venue?: string;
  };
  hasFinalsHalftime?: boolean;
  hasAllStarHalftime?: boolean;
  hasRingCeremony?: boolean;
  hasInvitedPerformance?: boolean;
  draftEligibilityRule?: string;
  fourPointLine?: boolean;
  foulOutLimit?: number;
  teamFoulPenalty?: number;
  quarterLength?: number;
  numQuarters?: number;
  overtimeDuration?: number;
  overtimeTargetPoints?: number;
  shootoutRounds?: number;
  overtimeType?: string;
  maxTimeouts?: number;
  coachChallenges?: boolean;
  maxCoachChallenges?: number;
  challengeReimbursed?: boolean;
  shotClockEnabled?: boolean;
  shotClockValue?: number;
  backcourtTimerEnabled?: boolean;
  backcourtTimerValue?: number;
  offensiveThreeSecondEnabled?: boolean;
  offensiveThreeSecondValue?: number;
  defensiveThreeSecondEnabled?: boolean;
  defensiveThreeSecondValue?: number;
  inboundTimerEnabled?: boolean;
  inboundTimerValue?: number;
  backToBasketTimerEnabled?: boolean;
  backToBasketTimerValue?: number;
  backcourtViolationEnabled?: boolean;
  travelingEnabled?: boolean;
  doubleDribbleEnabled?: boolean;
  goaltendingEnabled?: boolean;
  basketInterferenceEnabled?: boolean;
  kickedBallEnabled?: boolean;
  flagrantFoulPenaltyEnabled?: boolean;
  clearPathFoulEnabled?: boolean;
  illegalScreenEnabled?: boolean;
  overTheBackFoulEnabled?: boolean;
  looseBallFoulEnabled?: boolean;
  chargingEnabled?: boolean;
  overtimeEnabled?: boolean;
  maxOvertimesEnabled?: boolean;
  maxOvertimes?: number;
  overtimeTieBreaker?: string;
  maxPlayersOnCourt?: number;
  substitutionLimitEnabled?: boolean;
  maxSubstitutions?: number;
  noDribbleRule?: boolean;
  multiballEnabled?: boolean;
  multiballCount?: number;
  threePointLineEnabled?: boolean;
  threePointLineDistance?: number;
  fourPointLineDistance?: number;
  dunkValue?: number;
  midrangeValue?: number;
  heaveRuleEnabled?: boolean;
  halfCourtShotValue?: number;
  salaryCapEnabled?: boolean;
  salaryCapType?: 'soft' | 'hard' | 'none';
  minimumPayrollEnabled?: boolean;
  minimumPayrollPercentage?: number;
  luxuryTaxEnabled?: boolean;
  luxuryTaxThresholdPercentage?: number;
  apronsEnabled?: boolean;
  numberOfAprons?: number;
  firstApronPercentage?: number;
  secondApronPercentage?: number;
  tradeMatchingRatioUnder?: number;
  tradeMatchingRatioOver1st?: number;
  tradeMatchingRatioOver2nd?: number;
  restrictCashSendOver2ndApron?: boolean;
  restrictAggregationOver2ndApron?: boolean;
  restrictSignAndTradeAcquisitionOver1stApron?: boolean;
  freezePickAt2ndApron?: boolean;
  restrictTPEProvenanceOver2ndApron?: boolean;
  postSigningMoratoriumEnabled?: boolean;
  twoWayContractsEnabled?: boolean;
  nonGuaranteedContractsEnabled?: boolean;
  r2ContractsNonGuaranteed?: boolean;
  minPlayersPerTeam?: number;
  maxPlayersPerTeam?: number;
  maxStandardPlayersPerTeam?: number;
  maxTwoWayPlayersPerTeam?: number;
  maxTrainingCampRoster?: number;
  minContractType?: 'static' | 'dynamic';
  minContractStaticAmount?: number;
  maxContractType?: 'static' | 'service_tiered';
  maxContractStaticPercentage?: number;
  supermaxEnabled?: boolean;
  supermaxPercentage?: number;
  supermaxMinYears?: number;
  rookieExtEnabled?: boolean;
  rookieExtPct?: number;
  rookieExtRosePct?: number;
  birdRightsEnabled?: boolean;
  minContractLength?: number;
  maxContractLengthStandard?: number;
  maxContractLengthBird?: number;
  playerOptionsEnabled?: boolean;
  tenDayContractsEnabled?: boolean;
  rookieScaleType?: 'static' | 'dynamic' | 'none';
  rookieStaticAmount?: number;
  rookieMaxContractPercentage?: number;
  rookieScaleAppliesTo?: 'first_round' | 'both_rounds';
  rookieContractLength?: number;
  rookieTeamOptionsEnabled?: boolean;
  rookieTeamOptionYears?: number;
  rookieRestrictedFreeAgentEligibility?: boolean;
  rookieContractCapException?: boolean;
  inflationEnabled?: boolean;
  inflationMin?: number;
  inflationMax?: number;
  inflationAverage?: number;
  inflationStdDev?: number;
  mleEnabled?: boolean;
  roomMleAmount?: number;
  nonTaxpayerMleAmount?: number;
  taxpayerMleAmount?: number;
  biannualEnabled?: boolean;
  biannualAmount?: number;
  roomMlePercentage?: number;
  nonTaxpayerMlePercentage?: number;
  taxpayerMlePercentage?: number;
  biannualPercentage?: number;
  mleUsage?: Record<number, { type: 'room' | 'non_taxpayer' | 'taxpayer'; usedUSD: number }>;
  backgroundNbaMleUsage?: Record<number, { type: 'room' | 'non_taxpayer' | 'taxpayer'; usedUSD: number }>;
  deadMoneyEnabled?: boolean;
  ngGuaranteeDeadlineMonth?: number;
  ngGuaranteeDeadlineDay?: number;
  stretchProvisionEnabled?: boolean;
  stretchProvisionMultiplier?: number;
  stretchedDeadMoneyCapPct?: number;
  tradableDraftPickSeasons?: number;
  stepienRuleEnabled?: boolean;
  tradeExceptionsEnabled?: boolean;
  disabledPlayerExceptionEnabled?: boolean;
  tradeDeadlineMonth?: number;
  tradeDeadlineOrdinal?: number;
  tradeDeadlineDayOfWeek?: 'Sun' | 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat';
  faStartMonth?: number;
  faStartDay?: number;
  trainingCampMonth?: number;
  trainingCampDay?: number;
  faMoratoriumDays?: number;
  regularSeasonFAEnabled?: boolean;
  postDeadlineMultiYearContracts?: boolean;
  allStarHosts?: Array<{
    year: number;
    city: string;
    arena?: string;
    teamIds: number[];
  }>;
  allNbaTeams?: number;
  allNbaPlayersPerTeam?: number;
  allDefenseTeams?: number;
  allDefensePlayersPerTeam?: number;
  allRookieTeams?: number;
  allRookiePlayersPerTeam?: number;
  positionlessAwards?: boolean;
  gamesPerSeason?: number;
  divisionGames?: number;
  conferenceGames?: number;
  numGamesDiv?: number | null;
  numGamesConf?: number | null;
  customScheduleEnabled?: boolean;
  confs?: NBAConf[];
  divs?: NBADiv[];
  tiebreakers?: string[];
  otl?: boolean;
  allStarGameEnabled?: boolean;
  allStarFormat?: string;
  allStarTeams?: number;
  allStarDunkContest?: boolean;
  allStarDunkContestPlayers?: number;
  allStarThreePointContest?: boolean;
  allStarThreePointContestPlayers?: number;
  allStarShootingStars?: boolean;
  allStarShootingStarsMode?: 'individual' | 'team';
  allStarShootingStarsTeams?: number;
  allStarShootingStarsPlayersPerTeam?: number;
  allStarShootingStarsTotalPlayers?: number;
  allStarSkillsChallenge?: boolean;
  allStarSkillsChallengeMode?: 'individual' | 'team';
  allStarSkillsChallengeTeams?: number;
  allStarSkillsChallengePlayersPerTeam?: number;
  allStarSkillsChallengeTotalPlayers?: number;
  allStarHorse?: boolean;
  allStarHorseParticipants?: number;
  allStarHorseNoPlayerRepeat?: boolean;
  allStarHorseNoGlobalRepeat?: boolean;
  allStarOneOnOneEnabled?: boolean;
  allStarOneOnOneParticipants?: number;
  allStarThroneEnabled?: boolean;
  allStarThroneFieldSize?: 8 | 16;
  allStarThroneFormat?: 'mini8' | 'full16';
  allStarThroneFirstPossession?: 'shootout' | 'higher_seed_choice';
  allStarThroneScoring?: '2s_and_3s' | '1s_and_2s';
  allStarThroneShotClock?: number;
  allStarThroneTargetScore?: number;
  allStarThroneHardCap?: number;
  allStarThronePrizePool?: number;
  allStarThroneMandatoryDefense?: boolean;
  allStarMirrorLeagueRules?: boolean;
  allStarGameFormat?: 'timed' | 'target_score' | 'elam_ending';
  allStarGameTargetScore?: number;
  allStarQuarterLength?: number;
  allStarNumQuarters?: number;
  allStarOvertimeDuration?: number;
  allStarOvertimeTargetPoints?: number;
  allStarShootoutRounds?: number;
  allStarOvertimeType?: string;
  allStarMaxOvertimesEnabled?: boolean;
  allStarMaxOvertimes?: number;
  allStarOvertimeTieBreaker?: string;
  risingStarsEnabled?: boolean;
  risingStarsFormat?: string;
  risingStarsMirrorLeagueRules?: boolean;
  risingStarsQuarterLength?: number;
  risingStarsEliminationEndings?: boolean;
  celebrityGameEnabled?: boolean;
  celebrityGameMirrorLeagueRules?: boolean;
  gameFormat?: 'timed' | 'target_score' | 'elam_ending';
  gameTargetScore?: number;
  clutchTimeoutLimit?: number;
  handcheckingEnabled?: boolean;
  illegalZoneDefenseEnabled?: boolean;
  outOfBoundsEnabled?: boolean;
  freeThrowDistance?: number;
  rimHeight?: number;
  ballWeight?: number;
  startOfPossessionMethod?: 'jump_ball' | 'coin_toss' | 'rock_paper_scissors';
  possessionPattern?: 'nba' | 'alternating';
  courtLength?: number;
  baselineLength?: number;
  keyWidth?: number;
  cornerThrowInEnabled?: boolean;
  techEjectionLimit?: number;
  flagrant1EjectionLimit?: number;
  flagrant2EjectionLimit?: number;
  fightingInstantEjection?: boolean;
  useYellowRedCards?: boolean;
  shotClockResetOffensiveRebound?: number;
}

export interface GameStats {
  publicApproval: number;
  ownerApproval: number;
  playerApproval: number;
  leagueFunds: number;
  personalWealth: number;
  legacy: number;
}
