import type { TradeProposal } from './actions';
import type { Chat, ConsequenceDto, Email, HistoricalStatPoint, HistoryEntry, NewsItem, SocialPost, UserProfile } from './communication';
import type { Bet, CommishStoreItem, OwnedRealEstateAsset, Payslip } from './finance';
import type { Game, GameResult, LazySimProgress, NBACupState, PlayoffBracket } from './game';
import type { GameStats, LeagueStats } from './league';
import type { AllStarState, CommissionerLogEntry, ExpansionTeamSpec, HistoricalAward, OffseasonChecklist, OffseasonPendingDecision, SeasonHistoryEntry, TransferBid, TransferBidType, TransferListing } from './offseason';
import type { DraftPick, NBAPlayer } from './player';
import type { StaffData, StaffMember } from './staff';
import type { HeadToHead, NBATeam, NonNBATeam } from './team';
import type { CompetitionSpec } from '../services/competition/types';

export interface GameState {
  day: number;
  date: string;
  stats: GameStats;
  leagueStats: LeagueStats;
  historicalStats: HistoricalStatPoint[];
  inbox: Email[];
  chats: Chat[];
  news: NewsItem[];
  socialFeed: SocialPost[];
  history: Array<string | HistoryEntry>;
  isProcessing: boolean;
  isWatchingGame?: boolean;
  isClubbing?: boolean;
  pendingStartPayload?: any;
  lastOutcome: string | null;
  lastConsequence: ConsequenceDto | null;
  lastSimResults?: any[];
  simCurrentDate?: string;
  prevTeams?: NBATeam[];
  lastActionType?: string;
  lastActionPayload?: any;
  teams: NBATeam[];
  nonNBATeams: NonNBATeam[];
  clubAliasMap?: Record<number, number>;
  schedule: Game[];
  activeCompetitions?: CompetitionSpec[];
  competitionHistory?: Record<string, unknown[]>;
  portalTarget?: 'nba' | string | null;
  players: NBAPlayer[];
  draftPicks: DraftPick[];
  staff: StaffData | null;
  isDataLoaded: boolean;
  followedHandles: string[];
  cachedProfiles?: Record<string, any>;
  userProfile?: UserProfile;
  commissionerName: string;
  saveId?: string;
  migratedJerseyNumbers?: boolean;
  pendingHypnosis?: { targetName: string; command: string }[];
  boxScores: GameResult[];
  salary: number;
  payslips: Payslip[];
  lastPayDate: string;
  hasUnreadPayslip: boolean;
  scheduledEvents?: any[];
  christmasGames?: { homeTid: number; awayTid: number }[];
  globalGames?: {
    homeTid: number;
    awayTid: number;
    date: string;
    city: string;
    country: string;
  }[];
  historicalAwards: HistoricalAward[];
  endorsedPlayers: string[];
  allStar?: AllStarState;
  playoffs?: PlayoffBracket;
  nbaCup?: NBACupState;
  nbaCupHistory?: Record<number, NBACupState>;
  pendingClubDebuff?: { playerId: string; playerName: string; severity: 'heavy' | 'moderate' | 'mild'; clubName: string }[];
  headToHead?: HeadToHead;
  lazySimProgress?: LazySimProgress;
  tradeFinderPreselect?: { tid: number; playerId: string };
  tradeProposals?: TradeProposal[];
  bets: Bet[];
  realEstateInventory?: OwnedRealEstateAsset[];
  commishStoreInventory?: CommishStoreItem[];
  commissionerLog?: CommissionerLogEntry[];
  pendingNarratives?: string[];
  draftLotteryResult?: any[];
  retirementAnnouncements?: import('../services/playerDevelopment/retirementChecker').RetireeRecord[];
  seasonPreviewDismissed?: boolean;
  draftComplete?: boolean;
  activeDraftPicks?: Record<number, any>;
  activeDraftOrder?: Array<{ id: number; abbrev: string; name: string; logoUrl?: string; _originalTid: number; _originalAbbrev: string; _originalName: string; _traded: boolean; _r2?: boolean }>;
  seasonHistory?: SeasonHistoryEntry[];
  gameMode?: 'commissioner' | 'gm';
  userTeamId?: number;
  leagueType?: 'fictional' | 'modded';
  moddedLeagueBase?: 'nba' | 'europe' | 'philippines';
  europeMarket?: 'spain';
  pendingFAToasts?: { playerName: string; accepted: boolean; winnerTeamName?: string; annualM: number; years: number; rejectionReason?: string }[];
  pendingTransferToasts?: { playerName: string; accepted: boolean; sellerTeamName: string; feeEUR: number; reason?: string; userInitiated?: boolean }[];
  pendingElimToast?: boolean;
  pendingInjuryToasts?: { playerName: string; injuryType: string; gamesRemaining: number; pos?: string; teamName?: string }[];
  pendingFeatToasts?: { playerName: string; teamName: string; oppName: string; homeScore: number; awayScore: number; isHome: boolean; won: boolean; pts: number; reb: number; ast: number; isOwnTeam: boolean }[];
  pendingRecoveryToasts?: { playerName: string; teamName: string; pos: string }[];
  pendingAwardToasts?: { playerName: string; teamName: string; teamAbbrev: string; awardLabel: string }[];
  pendingPlayoffsToasts?: { teamName: string; body: string }[];
  pendingOptionToasts?: { playerName: string; teamName: string; pos: string; decision: 'player-in' | 'player-out' | 'team-exercised' | 'team-declined'; amountM?: number }[];
  offseasonChecklist?: OffseasonChecklist;
  expansionTeamIds?: number[];
  expansionEligiblePlayers?: string[];
  expansionDraftProtections?: Record<number, string[]>;
  expansionProtectionSettings?: {
    perTeamLimit: number;
    maxDraftedPerTeam: number;
    picksPerExpansionTeam: number;
  };
  expansionSchedule?: {
    year: number;
    teams: ExpansionTeamSpec[];
    realignment?: Record<number, { conference: 'East' | 'West'; cid: 0 | 1; did: number }>;
  };
  faTagCounter?: number;
  offseasonExitedYear?: number;
  faTagsTotal?: number;
  pendingOfferDecisions?: OffseasonPendingDecision[];
  pendingEuroBankruptcy?: {
    teamId: number;
    teamName: string;
    cashOnHand: number;
    year: number;
  };
  staffFreeAgents?: StaffMember[];
  euroSetupSeed?: {
    teamId: number;
    leagueId: string;
    masterSeed: number;
    manualOverrides: Record<string, unknown>;
  };
  pendingTeamOfficeNav?: {
    tab?: 'home' | 'gm' | 'coaching' | 'depth' | 'intel' | 'needs' | 'trading' | 'picks' | 'scouting';
    intelTab?: 'trades' | 'fa' | 'expiring';
  };
  simFranchiseRecords?: Array<{
    tid: number;
    category: string;
    isPlayoff: boolean;
    NAME: string;
    value: number;
    DATE: string;
    OPP: string;
    TM: string;
    SearchCategory: string;
    [key: string]: any;
  }>;
  faBidding?: {
    markets: Array<{
      playerId: string;
      playerName: string;
      bids: Array<{
        id: string;
        playerId: string;
        teamId: number;
        teamName: string;
        teamLogoUrl?: string;
        salaryUSD: number;
        years: number;
        option: 'NONE' | 'PLAYER' | 'TEAM';
        isUserBid: boolean;
        submittedDay: number;
        expiresDay: number;
        status: 'active' | 'accepted' | 'rejected' | 'withdrawn' | 'outbid';
        nonGuaranteed?: boolean;
      }>;
      decidesOnDay: number;
      resolved: boolean;
      pendingMatch?: boolean;
      pendingMatchExpiresDay?: number;
      pendingMatchPriorTid?: number;
      pendingMatchOfferBidId?: string;
      matchedByPriorTeam?: boolean;
    }>;
  };
  transferListings?: TransferListing[];
  transferBids?: TransferBid[];
  transferActivity?: Array<{
    id: string;
    date: string;
    fromTid: number;
    toTid: number;
    playerId: string;
    playerName: string;
    feeEUR: number;
    bidType: TransferBidType;
  }>;
}
