export const DUNK_MADE: Record<string, string[]> = {
  default: [
    "HE RATTLES THE RIM!",
    "DOWN IT GOES!",
    "PURE POWER AT THE CUP!",
    "HE FINISHES WITH AUTHORITY!"
  ],
  two_hand: [
    "THE RIM IS SCREAMING!",
    "TWO HANDS, NO MERCY!",
    "HE NEARLY TORE THE BASKET DOWN!",
    "A VIOLENT TWO-HANDED FINISH!"
  ],
  one_hand: [
    "ONE HANDED DESTRUCTION!",
    "HE REACHED THE PEAK AND STUFFED IT!",
    "A MONSTROUS ONE-ARMED FINISH!",
    "HE RATTLED THE IRON WITH ONE HAND!"
  ],
  tomahawk: [
    "THE AXE COMES DOWN!",
    "HE BURIED THE TOMAHAWK!",
    "A VIOLENT TOMAHAWK STRIKE!",
    "THE RIM IS STILL SHAKING FROM THAT TOMAHAWK!"
  ],
  reverse: [
    "HE FLIPPED THE SCRIPT!",
    "A STUNNING REVERSE FINISH!",
    "HE RATTLED THE IRON FROM BEHIND!",
    "THE REVERSE SLAM IS GOOD!"
  ],
  rim_grazer: [
    "HE SCRAPED THE IRON!",
    "A SUBTLE BUT EFFECTIVE FINISH!",
    "HE JUST BARELY GOT IT OVER!",
    "THE RIM GRAZER RATTLES HOME!"
  ],
  back_scratcher: [
    "HE BENT THE RIM BACK!",
    "A DEEP BACK-SCRATCHING FINISH!",
    "HE REACHED THE LIMIT AND STUFFED IT!",
    "THE OVER-THE-HEAD SPECIAL IS GOOD!"
  ],
  windmill: [
    "THE PROPELLER FINISH!",
    "HE CIRCLED THE ROCK AND BURIED IT!",
    "A MONSTROUS WINDMILL STRIKE!",
    "THE TORQUE ON THAT WINDMILL WAS INSANE!"
  ],
  cradle: [
    "HE ROCKED THE RIM!",
    "A SMOOTH CRADLE FINISH!",
    "HE TUCKED IT AND STUFFED IT!",
    "THE CRADLE SLAM IS GOOD!"
  ],
  double_clutch: [
    "HE PUMPED IT AND DUMPED IT!",
    "A STUNNING DOUBLE-CLUTCH FINISH!",
    "HE ADJUSTED IN MID-AIR AND SCORED!",
    "THE DOUBLE CLUTCH RATTLES HOME!"
  ],
  side_windmill: [
    "HE SWUNG IT FROM THE WING!",
    "A LATERAL WINDMILL DESTRUCTION!",
    "HE CIRCLED IT FROM THE SIDE AND STUFFED IT!",
    "THE SIDE WINDMILL IS GOOD!"
  ],
  leaner: [
    "HE FINISHED AT AN IMPOSSIBLE ANGLE!",
    "A STUNNING LEANER SLAM!",
    "HE DEFIED GRAVITY ON THE LEAN!",
    "THE LEANER RATTLES HOME!"
  ],
  front_windmill: [
    "HE SWUNG IT OVER THE TOP!",
    "A FORWARD WINDMILL STRIKE!",
    "HE CIRCLED IT IN FRONT AND STUFFED IT!",
    "THE FRONT WINDMILL IS GOOD!"
  ],
  three_sixty: [
    "HE SPUN THE FULL CIRCLE!",
    "A PERFECT 360 FINISH!",
    "HE TWISTED AND STUFFED IT!",
    "THE 360 RATTLES HOME!"
  ],
  elbow_hang: [
    "HE'S STUCK IN THE RIM!",
    "THE ELBOW IS IN THE CYLINDER!",
    "HE HOOKED THE IRON AND HUNG THERE!",
    "THE ELBOW HANG IS GOOD!"
  ],
  behind_the_back: [
    "HE WRAPPED IT AND STUFFED IT!",
    "A SMOOTH BEHIND-THE-BACK FINISH!",
    "HE THREADED THE NEEDLE AT THE RIM!",
    "THE BEHIND THE BACK IS GOOD!"
  ],
  super_scoop: [
    "HE SCOOPED IT FROM THE DEPTHS!",
    "A STUNNING UNDERHAND FINISH!",
    "HE LIFTED THE ROCK AND STUFFED IT!",
    "THE SUPER SCOOP IS GOOD!"
  ],
  wrong_way_360: [
    "HE FOUGHT THE PHYSICS AND WON!",
    "A STUNNING COUNTER-ROTATION FINISH!",
    "HE TWISTED THE WRONG WAY AND SCORED!",
    "THE WRONG-WAY 360 IS GOOD!"
  ],
  self_alley_reverse: [
    "HE TRACKED IT AND FLIPPED IT!",
    "A STUNNING OFF-THE-LOB REVERSE!",
    "HE CAUGHT IT AND STUFFED IT BACKWARDS!",
    "THE SELF-ALLEY REVERSE IS GOOD!"
  ],
  eastbay: [
    "HE THREADED THE LEGS AND BURIED IT!",
    "A MONSTROUS EASTBAY FINISH!",
    "HE WENT UNDER THE THIGH AND STUFFED IT!",
    "THE EASTBAY FUNK IS GOOD!"
  ],
  under_legs: [
    "HE CLEARED BOTH LEGS!",
    "A STUNNING DOUBLE-LEG FINISH!",
    "HE THREADED THE NEEDLE TWICE AND SCORED!",
    "THE UNDER-BOTH-LEGS SLAM IS GOOD!"
  ],
  soccer_flip: [
    "HE KICKED IT AND STICKED IT!",
    "A STUNNING FOOT-FLICK FINISH!",
    "HE FLIPPED IT WITH HIS TOES AND SCORED!",
    "THE SOCCER FLIP IS GOOD!"
  ],
  spinning_honey: [
    "HE SPUN AND HUNG!",
    "A STUNNING 360 ELBOW-HANG!",
    "HE TWISTED INTO THE RIM AND STAYED THERE!",
    "THE SPINNING HONEY DIP IS GOOD!"
  ],
  windmill_switch: [
    "HE SWITCHED IT AND STITCHED IT!",
    "A STUNNING HAND-OFF WINDMILL!",
    "HE TRANSFERRED THE ROCK AND STUFFED IT!",
    "THE WINDMILL SWITCH IS GOOD!"
  ],
  three_sixty_windmill: [
    "HE SPUN AND SWUNG IT HOME!",
    "A STUNNING DUAL-ROTATION FINISH!",
    "HE TWISTED AND CIRCLED THE IRON!",
    "THE 360 WINDMILL IS GOOD!"
  ],
  scorpion: [
    "HE STUNG THE RIM!",
    "A STUNNING REVERSE-OVERHEAD FINISH!",
    "HE BENT HIS BODY AND STUFFED IT!",
    "THE SCORPION SLAM IS GOOD!"
  ],
  lost_and_found: [
    "HE FOUND IT AT THE RIM!",
    "A STUNNING RELEASE AND RETRIEVAL!",
    "HE DROPPED IT AND STUFFED IT!",
    "THE LOST AND FOUND IS GOOD!"
  ],
  the_540: [
    "HE SPUN INTO HISTORY!",
    "A STUNNING 540 DEGREE FINISH!",
    "HE TWISTED BEYOND THE LIMIT AND SCORED!",
    "THE 540 RATTLES HOME!"
  ],
  btl_btb: [
    "HE THREADED, WRAPPED, AND STUFFED IT!",
    "A STUNNING TRIPLE-PLANE FINISH!",
    "HE WENT UNDER AND AROUND AND SCORED!",
    "THE BTL TO BTB IS GOOD!"
  ],
  rivera_360_btb_btl: [
    "HE REWROTE THE RECORD BOOKS!",
    "A STUNNING TRIPLE-MANIPULATION FINISH!",
    "HE SPUN, WRAPPED, THREADED, AND SCORED!",
    "THE 360 BTB TO BTL IS GOOD!"
  ],
  rivera_kamikaze: [
    "HE DIVED INTO THE RIM!",
    "A STUNNING HORIZONTAL FINISH!",
    "HE LAUNCHED HIMSELF AND STUFFED IT!",
    "THE KAMIKAZE SLAM IS GOOD!"
  ],
  rivera_double_btl: [
    "HE THREADED BOTH LEGS AND BURIED IT!",
    "A STUNNING DOUBLE-EASTBAY FINISH!",
    "HE WEAVED THE ROCK AND STUFFED IT!",
    "THE DOUBLE BTL IS GOOD!"
  ],
  double_spin: [
    "HE SPUN TWICE AND STUFFED IT!",
    "A STUNNING 720 DEGREE FINISH!",
    "HE TWISTED THROUGH TWO CIRCLES AND SCORED!",
    "THE 720 RATTLES HOME!"
  ],
  double_spin_over_person_crouching: [
    "HE CLEARED THE HELPER WITH A 720!",
    "A 720 OVER HIS TEAMMATE! HE BURIED IT!",
    "HE SPUN TWICE OVER A HUMAN AND SCORED!"
  ],
  double_spin_over_person_standing: [
    "HE CLEARED THE HELPER WITH A 720!",
    "A 720 OVER HIS TEAMMATE! HE BURIED IT!",
    "HE SPUN TWICE OVER A HUMAN AND SCORED!"
  ],
};

